### ISSUE TITLE
Object connection (If connected to DB) ändert status nicht

### ISSUE THREAD

**Issue by SHSolution** [ioBroker/ioBroker.sql#100]
Ich habe den Adapter mit einer MySQL DB auf einem anderem Rechner verbunden.
Wenn ich die DB nun ausschalte erhalte ich im Log zwar Meldungen, dass die Verbindung zur DB nicht hergestellt werden kann, aber das Object "cocnection" unter "info" der swlp Adapter Instanz wird nicht auf false gesetzt.
Ich habe ein Script erstellt um die DB Verbindung zu überwachen, was aber nicht funktioniert, wenn der Wert sich nicht ändert bei Verlust der DB Verbindung.

Würde mich über eine Behebung dieses Fehlers freuen.

VG

**Comment by Apollon77** [comment]
Please check with 1.12 (soon)
