### ISSUE TITLE
Version 1.11.1 note save counter...

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.sql#107]
JS-controller 3.0; sql - 1.11.1; MySql - not save numbers into table ts_counter - logs are clean. without errors..
![Скриншот 21-04-2020 103403](https://user-images.githubusercontent.com/6728198/79839215-dcd10e80-83bc-11ea-9a1f-3ce9baa3923f.jpg)
![Скриншот 21-04-2020 103354](https://user-images.githubusercontent.com/6728198/79839219-de9ad200-83bc-11ea-8ff1-cd24c445b8d1.jpg)
![Скриншот 21-04-2020 103414](https://user-images.githubusercontent.com/6728198/79839221-dfcbff00-83bc-11ea-9c38-8e6084572620.jpg)

**Comment by Apollon77** [comment]
Counter is only stored in ts_counter if the value is reset to a lower value!
