### ISSUE TITLE
SQL Adapter kein Upgrade auf dem Slave möglich

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.sql#108]
Der Adapter lässt sich nicht updaten. Über den Admin bleiber hängen. Mache ich es manuell über das Terminal kommt die Meldung ->

Required dependency "admin" not found on this host. 

Admin 4.0.9 ist installiert
js-controller 3.0.14

**Comment by Apollon77** [comment]
Yes, the gicen dependencies are now checked ;-) 

Please try Github version 1.12.0 (soon)
