### ISSUE TITLE
Minimale Differenz zum letzten Wert in Prozent

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.sql#117]
Hallo zusammen, wäre es möglich, die minimale Differenz zum letzten Wert in Prozent anzugeben? Ich habe z.B. Werte von -20 bis 40 (Außentemperatur) und 0 bis 60.000 (Helligkeit in Lux). und würde gerne alle Werte bei einer Abweichung von 1% aufzeichnen. Im Moment muss ich das für jeden Wert ausrechnen und in absoluten Zahlen angeben.

Danke vorab und Gruß!

**Comment by GermanBluefox** [comment]
Wie viel Prozent von 0° muss die Differenz sein um aufgenommen zu werden?

Das ist der Haken.

**Comment by fu-zhou** [comment]
Ah, verstehe, klar. Da muss man dann wohl den Messbereich mit angeben, was dann im Extremfall wieder für jeden Wert einzeln anzugeben ist und dann ist das keine Erleichterung... Kann der Messwert irgendwie automatisch eingetragen werden, in dem Min und Max verwendet wird? Heißt dann natürlich, dass bei Außentemperatur über Sommer das Max ansteigt, irgendwann nicht mehr größer wird, z.B. am 25.07. dann bei 33.5°C stehen bleibt und im Winter wird das Min ermittelt und am 28.01. war es am kältesten mit -11.2 °C. Bedeutet aber, dass sich das Ergebnis des Prozentwerts im Laufe der Zeit verändern kann bis halt ein voller Zyklus durchlaufen ist. Ist vielleicht zu aufwändig...

**Comment by Apollon77** [comment]
Denke es ist praktisch nicht sinnvoll machbar ...  sorry
