### ISSUE TITLE
Adapter funktioniert nicht mit sqlite3 DB

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.sql#118]
Ich habe sqlite3 installiert und auch per Command line eine sqlite.db angelegt.
Wenn ich den Adapter starte bekomme ich 
`
sql.0 | 2020-05-13 18:26:43.086 | error | (3969) TypeError: Cannot read property 'close' of undefined
-- | -- | -- | --
sql.0 | 2020-05-13 18:26:43.080 | error | (3969) Selected SQL DB was not installed properly: "sqlite". SQLite requires build tools on system. See README.m

`

wenn ich "Verbindung testen" drücke, kommt
`TypeError: SQL[clients[msg.message.config.dbtype].name] is not a constructor
`

**Comment by Apollon77** [comment]
Did you updated nodejs?

If you Use js-Controller 3 the. Run „iobroker rebuild sql --install“ if other controller then follow nodejs update instructions in forum

**Comment by Marty56** [comment]
I am Tuning node 12. Update a couple of days ago. js-controller 3.1.4.
The instruction above did not resolve the issue.

**Comment by Apollon77** [comment]
Ok, please try 
* open shell and cd to iobroker dir
* cd node_modules/iobroker.sql
* npm install --production

Fixed after that?

**Comment by Marty56** [comment]
no change.

`npm install --production
audited 627 packages in 32.282s

3 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
pi@ioBroker-RasPi4:/opt/iobroker/node_modules/iobroker.sql $ npm fund
iobroker.sql@1.12.5
├─┬ https://github.com/sponsors/feross
│ └── safe-buffer@5.2.1
├─┬ https://www.patreon.com/feross
│ └── safe-buffer@5.2.1
├─┬ https://feross.org/support
│ └── safe-buffer@5.2.1
├─┬ https://github.com/sponsors/sindresorhus
│ └── p-limit@2.3.0
└─┬ https://github.com/sponsors/isaacs
  └── glob@7.1.6
`

**Comment by Apollon77** [comment]
no change? Strange

Ok then check where you find an "sqlite3" folder ... could be opt/iobroker/node_modules/sqlite3 or also in opt/iobroker/node_modules/iobroker.sql/node_modules/sqlite3

cd there and run "npm rebuild"

**Comment by Marty56** [comment]
Ich habe in beiden vorgeschlagenen Verzeichnissen "irgendwelche" nodejs packages. habe überall nem rebuild gemacht. Hat aber nichts geändert.

Auf eine anderen iobroker Installation (NUC) lief die Einrichtung ohne Probleme

**Comment by Apollon77** [comment]
es geht nicht um "irgendwleche" pakete, es geht um ein verzeichnis node_modules/sqlite3
Dort bitte hineinwechseln und npm rebuild ausführen

ALternativ den Adapter neu installieren.

Bei einem nodejs update ist soetwas leider nötig

**Comment by Marty56** [comment]
ok. der Sql Adapter läuft auf meinem neuen System (NUC) ohne Probleme.
Ich glaube nicht, dass die Probleme auf dem Raspberry irgendwas mit nodejs Updates zu tun hatte, weil ich den Adapter erst nach den Update von Nodejs installiert hatte.
Vielleicht lag es an den knappen Memory Resources meines Raspberries.

Ich kann leider nicht weiter testen, weil ich den Raspberry abgebaut habe.
Danke für die Unterstützung.
