### ISSUE TITLE
Exception: TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by EvilAcid** [ioBroker/ioBroker.sql#119]
Hallo zusammen, nach dem Update diverser Adapter und einem neustart  bekomme ich wieder folgende Meldungen in den Logs.

```
sql.0 | 2020-05-17 08:38:14.545 | info | (26077) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
sql.0 | 2020-05-17 08:38:14.543 | info | (26077) terminating
sql.0 | 2020-05-17 08:38:14.037 | error | (26077) TypeError: Cannot read property 'startsWith' of undefined at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6198:39 at Array.map (<anonymous>) at /opt/iobroker/no
sql.0 | 2020-05-17 08:38:14.036 | error | (26077) uncaught exception: Cannot read property 'startsWith' of undefined
sql.0 | 2020-05-17 08:38:14.028 | warn | (26077) Exception: TypeError: Cannot read property 'startsWith' of undefined

```

![image](https://user-images.githubusercontent.com/22026079/82137659-62a87400-981a-11ea-95af-70d821780f66.png)

Raspberry Info
```
raspberrypi4-iot
Betriebssystem
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.81 GB
System Betriebszeit
18:46:00
Node.js
v14.2.0 (Empfohlene Version v12.16.3)
NPM
6.14.4
Festplatte Größe
14.3 GB
Festplatte frei
9.54 GB
Anzahl der Adapter
291
Betriebszeit
19:09:56
Aktive Instanzen
13
Hostname
raspberrypi4-iot
```

Der Adapter hatte bei derersten installation die gleiche Fehlermeldung geracht, weis aber leider nicht was genau ich da gemacht habe damit es lief.

Grüsse

**Comment by Apollon77** [comment]
Ok. Du updated einfach mal eben von GitHub? Hat dir jemand gesagt du sollst das tun? Nur dort gibt es meines Wissens nach die 1.13.0 ...bitte 1.12.x aus dem latest nutzen. Die 1.13.0 ist noch nicht soweit. GitHub ist dev stand.

**Comment by EvilAcid** [comment]
Hallo @Apollon77

Danke für die Antwort. 
Nun weis ich wieder was ich gemacht habe das der Adapter lief nach der ersten installation. Ich habe ihr deinstalliert und von Git selber gezogen. Dan hatt es geklappt.

Ich habe nun ein Backup meiner DB gemacht und sie komplet gelöscht (alle tabellen) und anschliessend den sql Adapter nochmals gestartet. Nun geht auch alles wider.

Ich berde es die Tage aber auf meinem Devsystem auch nochmals mit der normalen istalation über ioBrocker testen.

Vielen dank

**Comment by Apollon77** [comment]
In fact ... which js-controller  version? The errorcomes from there and is already fixed in 3.1.4

**Comment by Apollon77** [comment]
PS: has nothing to do with sql adapter!
