### ISSUE TITLE
Absturz nach Update auf 1.13.0

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.sql#121]
Nach dem Update erhalte ich jede Menge Fehler:

sql.0 | 2020-05-19 06:21:50.963 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
sql.0 | 2020-05-19 06:21:50.963 | error | at _0x30230c._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:115328)
sql.0 | 2020-05-19 06:21:50.963 | error | at adapterObjects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1482:21)
sql.0 | 2020-05-19 06:21:50.963 | error | at autoSubscribeOn (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7066:26)
sql.0 | 2020-05-19 06:21:50.963 | error | at Array.map (<anonymous>)
sql.0 | 2020-05-19 06:21:50.963 | error | at pattern.map.id (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7066:39)
sql.0 | 2020-05-19 06:21:50.963 | error | (27526) TypeError: Cannot read property 'startsWith' of undefined
sql.0 | 2020-05-19 06:21:50.947 | error | (27526) unhandled promise rejection: Cannot read property 'startsWith' of undefined
Unhandled | 2020-05-19 06:21:50.946 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

**Comment by Apollon77** [comment]
Duplicate. Yes needs a fix.

**Comment by Marty56** [comment]
Unfortunately the downgrade function of the sql adapter is not working. After trying to downgrade it keeps on starting the latest version.

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Duplicate. Yes needs a fix.

Thanks.
I spend some hours to bring up my last image and now i have to rebuild the changes.

**Comment by Marty56** [comment]
Just deinstall the adapter and reinstall using the stable repro

**Comment by Apollon77** [comment]
duplicate #120
