### ISSUE TITLE
warnings after update to 1.13.1

### ISSUE THREAD

**Issue by smartboart** [ioBroker/ioBroker.sql#122]
log after update to 1.13.1

ok after downgrade to 1.12.5

JS controller
v 3.1.4
Node.js
    v12.16.3
NPM
    6.14.4

sql.0 | 2020-05-20 20:27:10.881 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.quarter
-- | -- | -- | --
sql.0 | 2020-05-20 20:27:10.881 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.year
sql.0 | 2020-05-20 20:27:10.880 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.15Min
sql.0 | 2020-05-20 20:27:10.880 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.delta
sql.0 | 2020-05-20 20:27:10.879 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.last
sql.0 | 2020-05-20 20:27:10.879 | warn | (8587) No realID found for statistics.0.save.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.last
sql.0 | 2020-05-20 20:27:10.878 | warn | (8587) No realID found for statistics.0.save.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.delta
sql.0 | 2020-05-20 20:27:10.878 | warn | (8587) No realID found for statistics.0.temp.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.year
sql.0 | 2020-05-20 20:27:10.877 | warn | (8587) No realID found for statistics.0.temp.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.quarter
sql.0 | 2020-05-20 20:27:10.877 | warn | (8587) No realID found for statistics.0.temp.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.month
sql.0 | 2020-05-20 20:27:10.876 | warn | (8587) No realID found for statistics.0.temp.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.week
sql.0 | 2020-05-20 20:27:10.876 | warn | (8587) No realID found for statistics.0.temp.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.day
sql.0 | 2020-05-20 20:27:10.875 | warn | (8587) No realID found for statistics.0.temp.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.hour
sql.0 | 2020-05-20 20:27:10.875 | warn | (8587) No realID found for statistics.0.temp.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.15Min
sql.0 | 2020-05-20 20:27:10.874 | warn | (8587) No realID found for statistics.0.temp.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.year
sql.0 | 2020-05-20 20:27:10.874 | warn | (8587) No realID found for statistics.0.temp.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.week
sql.0 | 2020-05-20 20:27:10.873 | warn | (8587) No realID found for statistics.0.temp.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.quarter
sql.0 | 2020-05-20 20:27:10.873 | warn | (8587) No realID found for statistics.0.temp.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.month
sql.0 | 2020-05-20 20:27:10.872 | warn | (8587) No realID found for statistics.0.temp.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.hour
sql.0 | 2020-05-20 20:27:10.872 | warn | (8587) No realID found for statistics.0.temp.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.day
sql.0 | 2020-05-20 20:27:10.871 | warn | (8587) No realID found for statistics.0.temp.sumDelta.mqtt.0.Wemo.energy.growatt.Etotal.15Min
sql.0 | 2020-05-20 20:27:10.870 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.week
sql.0 | 2020-05-20 20:27:10.870 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.month
sql.0 | 2020-05-20 20:27:10.869 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.hour
sql.0 | 2020-05-20 20:27:10.869 | warn | (8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.day
sql.0 | 2020-05-20 20:27:10.868 | warn | (8587) No realID found for modbus.0.holdingRegisters.12288_Arbeit

**Comment by Apollon77** [comment]
Hi, these are only wartnings and we try to find out why 1.13.0 crashed.

In fact: can you please check these datapoints? Is sql enabled there? Are there any settings different from the ones that work?

**Comment by Apollon77** [comment]
Are there alias defined in sql adapter or such?

**Comment by smartboart** [comment]
Hello, yes all of these data points are enabled for sql... And all settings are the same.. All of my data points do not work in this version...in the older version they are working....

**Comment by Apollon77** [comment]
Do you use aliases on these sql settings?

**Comment by Apollon77** [comment]
Please show the object definition of one such object. 
In Admin objects -> go to the object -> Klick pencil icon right side in this line. Select the json in the raw tab of the window

**Comment by smartboart** [comment]
![Screenshot_20200521_002901](https://user-images.githubusercontent.com/38385805/82503767-30d52d00-9afa-11ea-8551-17a74fc25f37.jpg)

**Comment by smartboart** [comment]
#
![Screenshot_20200521_003413](https://user-images.githubusercontent.com/38385805/82504070-d1c3e800-9afa-11ea-91a1-62a9af14f103.jpg)

**Comment by smartboart** [comment]
Oh shit.... Sorry..

**Comment by Apollon77** [comment]
In Admin these states are no longer shown?
YOu use redis? Only for states or also for objects?

**Comment by smartboart** [comment]
Yes in admin they are no longer shown... I use redis for both... States and objects

**Comment by smartboart** [comment]
Here you can see that this state is not present...
(8587) No realID found for statistics.0.save.sumDelta.modbus.0.holdingRegisters.12288_Arbeit.hour

![Screenshot_20200521_102827_org mozilla firefox](https://user-images.githubusercontent.com/38385805/82539698-247abf80-9b4e-11ea-95b7-0824f08e61cb.jpg)

Here you have a faulty one with warning which is present..
![Screenshot_20200521_102758_org mozilla firefox](https://user-images.githubusercontent.com/38385805/82539831-61df4d00-9b4e-11ea-980e-fbc21b31790e.jpg)

And here is a faulty one which is present but not activated for sql but was in the past...
![Screenshot_20200521_002901](https://user-images.githubusercontent.com/38385805/82540077-ca2e2e80-9b4e-11ea-8bef-da68bf735db3.jpg)

**Comment by smartboart** [comment]
All have in commen that they was activated for sql and was or are deleted.

**Comment by 150d** [comment]
Just tried to upgrade to v1.14.2, but the issue is still present.

I had to revert back to v1.12.5 to stop the "no RealID found" log messages.

**Comment by Apollon77** [comment]
No one told that this is adjusted in 1.14.2 ... sorry ...

**Comment by Apollon77** [comment]
Ok, das waren die ausschlagebenden Hinweise ... ich glaub ich habs. Bitte 1.15.2 testen

**Comment by 150d** [comment]
Mit v1.15.2 sehe ich die Fehlermeldungen bei mir nicht mehr.

Danke!
