### ISSUE TITLE
Examples in Readme are not working

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.sql#124]
Please check the syntax of the examples under the headline "delete state" and "change state".
the character ' is missing.

**Comment by Apollon77** [comment]
Can you provide a Pr? Simply select the file in web and hit the pencil button. Correct is in the Editor in browser and send in as proposal Forschungen. Thank you

**Comment by Marty56** [comment]
I would love to do this but even if I am correctly the syntax error in the examples, the examples are not working

**Comment by Apollon77** [comment]
which sql version dfo you use? These functions where added in sql 1.14.0

**Comment by Marty56** [comment]
v1.14.0

**Comment by Apollon77** [comment]
fixed
