### ISSUE TITLE
keine neu ausgewählte dp eingetragen

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.sql#126]
Es werden keine neu ausgewählten datenpunkte mehr in die mysql-Datenbank eingetragen bzw angelegt. Es kommt immer der Fehler 

sql.1 | 2020-06-09 13:04:07.038 | warn | (2771) Cannot get index of "javascript.1.Wasser.Wasseruhr": id not found
-- | -- | -- | --

in der Datenbank wird kein neuer datapoints angelegt

js-controller 3.1.5
sql adapter-version 1.13.1

**Comment by Apollon77** [comment]
Please retest with 1.15.2
