### ISSUE TITLE
sql-adapter verursacht hohe CPU-Auslastung

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.sql#127]
wenn der SQL adapter gestart ist, schiesst die CPU-Auslastung in die höhe 
laut "top" der sql-adapter alleine 60-80%.
habe aktuell nur ca 7 DP-Abfragen aktiv, hab auch schon eine neue mysqldb-server getestet, ohne erfolg

js-controller 3.1.5
sql  1.13.1

**Comment by Apollon77** [comment]
Bitte mal debug log aktivieren. Dann sollte man genau sehen was der Adapter tut. Kommt dabei was raus?

Wie oft werden die genannten States denn aktualisiert?

**Comment by Farmer-cb** [comment]
log wurde erstellt, kann ich dir das per Mail schicken???
habe jetzt am schluss noch 2 dp-abfrage hinzugefügt, kann es sein, das die CPU-Auslastung damit zusammen höngt, das die DPs nicht in der Datenbank eingetragen werden., zumindest sind sie darin nicht aufgelistet.

abgefragt werden die DPs mit "nur bei Änderung aufzeichnen"

**Comment by Farmer-cb** [comment]
so wie es aussieht, hab ich den Fehler gefunden.

sobald ich den Typ des DPs auf Automatisch lasse, steigt die CPU-auslastung >80%
wenn ich bei den DPs den Typ manuell setzte bleibt die CPU-Auslastung <5%

hat aber schon mal ohne Probleme funktioniert

**Comment by Apollon77** [comment]
Ohne debug log kann ich nur raten

**Comment by Farmer-cb** [comment]
Mmmmhhh
Hab ich dir doch eigentlich per mail geschickt

⁣                                                                                                
Gesendet von meinem Obstfressenden Droiden

mfg
Büchner Christian​

**Comment by Apollon77** [comment]
Ja gefunden. Mir fehlte hier der Hinweis darauf. Bei Forum, GitHub und emailed geht einem schonmal der Überblick verloren.

**Comment by Apollon77** [comment]
Wieviele States hast Du aktiviert?

Wärst Du bereit für ein Experiment?
Bitte mal die aktuelle Version nehmen. Dann das FIle /opt/iobroker/node_modules/iobroker.sql/main.js editieren und dort in Zeile https://github.com/ioBroker/ioBroker.sql/blob/master/main.js#L2660 das "count < 200" durch "count < 20" ersetzen.

Dann neu starten. wie ists dann mit CPU?

**Comment by Farmer-cb** [comment]
Servus
wie ich dir bereits geschrieben habe, ist aktuell die hohe CPU-Last weg, seit ich den Datentyp von Automatik auf Nummer etc geändert habe.

hab jetzt die 1.14.1 installiert und die 200 auf 20 geändert.
Habe auch noch ein dp-typ auf automatisch geändert
aktuell keine grosse CPU-Last vorhanden, nur etliche Log-Einträge (enabled logging of .....)

______________________________________________________________

mfg
Büchner Christian
Dietldorf 47
93133 Burglengenfeld
Mobil: 015772476055

**Comment by Apollon77** [comment]
Also Ich habe die Code Änderungen in 1.13.1 bis aktuell durchgeschaut und kann mir nicht erklären wie die CPU Last durch setzen des Datentyps weg sein könnte, es sei denn es liegt an https://github.com/ioBroker/ioBroker.sql/commit/ab1d4985b0ca2e562fcadb1d3501d7701015ff98#diff-7a9076d6d94e62c13d641aa71f19ae8e was ich aber nicht glaube ... also kann es nur das mit den Subscribes sein

**Comment by Apollon77** [comment]
Bitte auch 1.14.2 versuchen ... da gabs was was falsch lief und durchaus Last verursachen konnte
