### ISSUE TITLE
sql-client 1.2.0

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.sql#13]
Hello Apollon77, 
there is a npm sql-client 1.2.0
But in the driver used 0.7.0. Can you test it with 1.2.0?

Thanks,
Bluefox

**Comment by Apollon77** [comment]
I will have a look. for checks on all commits between 0.7 and 1.0 is bugfixing and feature addition ... but I also asked them for a changelog

I still have no real database running, so I test it with sqlite and if that works the forum should do the rest :-)

**Comment by Apollon77** [comment]
done by https://github.com/ioBroker/ioBroker.sql/pull/15
