### ISSUE TITLE
Start des Adapters führt zu mysql crash

### ISSUE THREAD

**Issue by ocfu** [ioBroker/ioBroker.sql#131]
Sobald der Adapter gestartet wird (1.12.5) crasht mysql (Server version: 10.3.22-MariaDB-0+deb10u1) auf dem Raspi 3b+

Errorlog mysql:
2020-07-04 08:56:12 0x59ab43e0  InnoDB: Assertion failure in file /build/mariadb-10.3-GK21G6/mariadb-10.3-10.3.22/storage/innobase/btr/btr0cur.cc line 310

**Comment by Apollon77** [comment]
Und was kann der Adapter dafür? Wir machen normale sql queries ... ich würde also an deiner Tele mal nach einem Marianne update schauen. Bzw dort schauen woran es liegen kann. Ggf sind auch bei dir Daten korrupt oder so?!

Ggf kannst du den Adapter auf debug stellen und schauen welche query es sein könnte und ggf so versuchen es nachzustellen.

**Comment by Apollon77** [comment]
Ps: such under testing läuft. Also kann es kein generelles Problem sein.
