### ISSUE TITLE
Storage Vorhaltezeit nicht aktiv

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.sql#135]
Es befinden sich Daten in der Datenbank, die wesentlich älter sind als in der Vorhaltezeit angegeben.
Einstellung: Storage Vorhaltezeit 3 Tage
z.B. heute 12.10.2020:   Datenbank Daten vom 1.10.2020

Es sollten doch alle Daten gelöscht werden, die älter sind als 9.10.2020

**Screenshots & Logfiles**  
keine Fehlermeldung, kein Eintrag im Log

**Versions:**  
 - Adapter version: 1.15.2
 - JS-Controller version: 3.1.6
 - Node version: <node-version> 10.19.0
 - Operating system: Linux 4.19.97-v7l+ armv7l

**Comment by Apollon77** [comment]
kann es sein das das logging für diese Datenpunkt deaktiviert ist? Wenn ja dann ist das der Grund ...

**Comment by Hans-Zwiesel** [comment]
Logging ist aktiv.

**Comment by Apollon77** [comment]
Zeige bitte mal screenshots der adaptereinstellungen generell und von so  einem datenpunkt.

**Comment by Hans-Zwiesel** [comment]
Hier bitte:

![Adapter default](https://user-images.githubusercontent.com/49147193/95818195-9339fe80-0d23-11eb-80d3-4e365bb912f7.jpg)
![Adapter](https://user-images.githubusercontent.com/49147193/95818197-93d29500-0d23-11eb-8d16-b219ccce0e49.jpg)
![Einstellung](https://user-images.githubusercontent.com/49147193/95818200-93d29500-0d23-11eb-828f-9517d2c3aa39.jpg)
![Tabelle](https://user-images.githubusercontent.com/49147193/95818202-946b2b80-0d23-11eb-997f-9c04770adfd5.jpg)

**Comment by Apollon77** [comment]
Dann bitte mal Debug log posten

**Comment by Hans-Zwiesel** [comment]
Hat sich erledigt.
Wie ich gerade festgestellt habe, werden die alten Daten erst dann gelöscht, wenn neue Daten geschrieben werden.
Solange keine neuen Daten kommen, werden die alten nicht gelöscht.
