### ISSUE TITLE
Initialising SQL impossible: log file is full of 	(2096) Error: ER_CON_COUNT_ERROR: Too many connections

### ISSUE THREAD

**Issue by RESDE** [ioBroker/ioBroker.sql#136]
**Describe the bug**  
After moving the iobroker completely on a new PI4 computer the SQL is not logging propperly anymore.
After starting the SQL adapter The error count is coming up and flashing the log file.
the io broker setup is handling roughly 4100 objects with 3600 states.
After the flagging of state #1000 the error is floating the log file.

The SQL database (MariaDB) is running on a Synology NAS, the concurrent connections are incfeased up to 10000 (there defined in the cnf file)

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
Get the SQL adapter back to stabkle running and "filing"

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/59728312/98538424-084d1500-228b-11eb-9a1d-ad27bdafa46d.png)

**Versions:**  
 - Adapter version: SQL 1.1.5.3
 - JS-Controller version: <js-controller-version> 3.1.6
 - Node version: <node-version> 10.23.0
 - Operating system: <os-name>Debian Buster on a PI 4B

**Additional context**

**Comment by Apollon77** [comment]
In this case please turn the "Write Nulls" feature off

**Comment by Apollon77** [comment]
Does it work then?

**Comment by RESDE** [comment]
Hi,

this option was not activted in the default settings. The error is still flodding my iobroker logfile.
Please support deeper.

**Comment by Apollon77** [comment]
writeNulls should be active by default. Please show settings screen and please save the adapter settings once with deactivated (in worst case click it two times to enable save buttons) is it then still happening?

**Comment by RESDE** [comment]
o.k. here are the settings:

![grafik](https://user-images.githubusercontent.com/59728312/100510655-a3405d00-316e-11eb-8b1f-8cf70e1f2101.png)


![grafik](https://user-images.githubusercontent.com/59728312/100511009-c10dc200-316e-11eb-846b-a1ea67e57c55.png)

connection to SQL DB is owrking check connections is returning message OK

**Comment by Apollon77** [comment]
Ok, then: please disable the "Schreibe NULL-Werte an Start/Stop-Grenzen"

**Comment by RESDE** [comment]
Hi I disabled this option. btw: what is the purposeof this option or what is the functionality.
The flodding of the log file is not hapenning any more.

**Comment by Apollon77** [comment]
This is an "audit trail" feature. It is there to clearly see when the adapter is not running. it inserts NULL values at the end and also on start to clearly see the "no values are ok" timeframes.

hm ... this brings e to one question: You have set 300 concurrent connections allowed in your config ... is this also that high in your SQL server? if not please make sure that the max numbers are set corectly and try again
