### ISSUE TITLE
Graphik plotting not available although SQL history is available

### ISSUE THREAD

**Issue by RESDE** [ioBroker/ioBroker.sql#138]
**Describe the bug**  
Beside the access to the SQL history of the recoreded states via the tab "table" while opening the SQL adapter of arecoreded state the tab for the graph is empty and even not clickable.
The flot adapter adapter is installed and up running.

**To Reproduce**  
1. Go to the section of the SQL adapter of a dedicted (=via SQL adapter monitored state), 
2. under the tab grafik there is not flot diagramm available. Even the tab is blanked out. 

**Expected behavior**  
As described in the SQL adapter functionality the SQL stored statae values show be plotted as a graph.

**Versions:**  
 - Adapter version: <adapter-version> 1.15.3
 - JS-Controller version: <js-controller-version> 3.1.6
 - Node version: <node-version> 10.23.0
 - Operating system: <os-name>Pi4B

**Additional context**

**Comment by Apollon77** [comment]
Please check for this topic in Admin adapter
