### ISSUE TITLE
Chart anzeige auf States ist immer leer

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.sql#140]
Auf der Objekt seite für Hisory gibt es einen Eintrag für Chart. Allerdings ist der bei mir immer leer. Ich habe Flot installiert, zum testen auch Rickshaw aber trotzdem keine Änderung. Liegt das daran dass der SQL adapter verwendet wird? 
<img width="1236" alt="Screenshot 2020-12-07 at 20 17 34" src="https://user-images.githubusercontent.com/35381530/101394799-4f99e600-38c9-11eb-8ece-5bbc5806756a.png">
<img width="1236" alt="Screenshot 2020-12-07 at 20 17 42" src="https://user-images.githubusercontent.com/35381530/101394808-5294d680-38c9-11eb-8ec9-209d44027b7a.png">
<img width="1027" alt="Screenshot 2020-12-07 at 20 19 09" src="https://user-images.githubusercontent.com/35381530/101394907-7bb56700-38c9-11eb-88eb-7b4977426f84.png">

**Comment by Apollon77** [comment]
Bitte im Admin Adapter prüfen und ggf neu anlegen. Bitte auch Browser Konsole prüfen

**Comment by nkleber78** [comment]
Sorry, da stehe ich auf dem Schlauch :( Wo kann ich da im Admin adapter was einstellen bzw. was kann ich neu anlegen?

**Comment by Apollon77** [comment]
Die Grafik kommt vom Admin Adaoter und nicht vom sql adapter. Das geht dort generisch. scheinbar hat er ein Problem die Daten vom Server zu bekommen. Kannst mal sql Adapter auf Debug stellen und schauen was dort im Log steht wenn du die Daten abrufen kannst

**Comment by nkleber78** [comment]
Irgendwie sind das wohl mehrere Probleme
1. ich habe für admin https://sub1.domain.at und für web/flot https://sub2.domain.at. Aber der Adapter versucht über  http://sub1.domain.at:8082 auf flot zuzugreifen was natürlich nicht geht da diese Ports nach aussen nicht sichtbar sind
2. Ich bin von Aussen per https, aber auf iobroker per http da mein Reverse proxy auch das Zertifikat usw. zentral bereitstellt. Daher auch die "insecure frame" Fehlermeldung.

Ich habe mal Admin und web auf https umgestellt zum testen. Aber das problem dass er über die falschen URL's / ports zugreifen will bleibt...

**Comment by Apollon77** [comment]
Dann ist es auch am Ende ein admin/web Interop problem ... sehr ungewöhnliches Setup in dem Fall ... verständlich aber sehr selten).

**Comment by nkleber78** [comment]
Siehst du hier Lösungsansätze um das in den Griff zu bekommen? Ev. die Config from WEB adapter zu lesen damit die IP und Port für den Zugriff klar ist?

**Comment by Apollon77** [comment]
.. naja die interne IP hilft dir auch nicht, oder ?!

Mach mal bei admin auf, dann muss man sehen, habe keine Lösung parat out of the box

**Comment by nkleber78** [comment]
Ok, danke schon mal für deinen Support
