### ISSUE TITLE
Minimale Differenz zum letzten Wert stimmt nicht

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.sql#141]
Hallo,
SQL History ist 1.15.3

das Objekt ist eine Zahl.
Minimale Differenz zum letzte Wert = 3
Nur Änderungen aufzeichnen ist aktiv
Änderungen ignorieren und trotzdem aufzeichnen beide 0

Wenn man nun manuell die Zahlen
1,2,3,4,5,6,7,8,9,10 einträgt, so werden die Zahlen
1,3,4,6,7,9,10 in der Datenbank gespeichert, es sollten aber die Zahlen
1,4,7,10  eingetragen werden, oder verstehe ich da etwas nicht?

ich beobachte das schon einige Monate.
Siehe auch: https://forum.iobroker.net/viewtopic.php?f=20&t=17563&p=183896#p183757
ist ein ähnliches Problem.
**Das Problem ist jederzeit schnell nachvollziehbar.**

Vielen Dank.

**Comment by Apollon77** [comment]
Am besten schalte mal das Logging auf Debug, dann siehst DU an sich genau warum ein Wert geloggt wird und wann nicht. Kommt da vllt eine Erkenntniss zu warum?

**Comment by Hans-Zwiesel** [comment]
Ich habe u.A. das hier gefunden, werde aber nicht schlau daraus:

`2020-12-12 03:10:32.365 - debug: sql.0 (25873) new value received for mqtt.0.haus.keller.Helios_KWL.Lueftung.CO2ppm, new-value=432, ts=1607739032356, relog=false
2020-12-12 03:10:32.366 - debug: sql.0 (25873) Datatype mqtt.0.haus.keller.Helios_KWL.Lueftung.CO2ppm: Currently: number, StorageType: Number
2020-12-12 03:10:32.367 - debug: sql.0 (25873) pushValueIntoDB called for mqtt.0.haus.keller.Helios_KWL.Lueftung.CO2ppm (type: undefined, ID: 136) and state: {"val":432,"ack":true,"ts":1607739032356,"q":0,"from":"system.adapter.mqtt.0","user":"system.user.admin","lc":1607739032356}
2020-12-12 03:10:32.368 - debug: sql.0 (25873) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.haus.keller.Helios_KWL.Lueftung.CO2ppm
2020-12-12 03:10:32.369 - debug: sql.0 (25873) Type set in Def for mqtt.0.haus.keller.Helios_KWL.Lueftung.CO2ppm: Number
2020-12-12 03:10:32.373 - debug: sql.0 (25873) Type (from Def) for mqtt.0.haus.keller.Helios_KWL.Lueftung.CO2ppm: 0
2020-12-12 03:10:32.375 - debug: sql.0 (25873) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for mqtt.0.haus.keller.Helios_KWL.Lueftung.CO2ppm (type: 0, ID: 136) and state: {"val":432,"ack":true,"ts":1607739032356,"q":0,"from":"system.adapter.mqtt.0","user":"system.user.admin","lc":1607739032356}
2020-12-12 03:10:32.376 - debug: sql.0 (25873) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(136, 1607739032356, 432, 1, 6, 0);
`
Kannst Du mir bitte erklären, warum das so ist:
Wenn man nun manuell die Zahlen
1,2,3,4,5,6,7,8,9,10 einträgt, so werden die Zahlen
1,3,4,6,7,9,10 in der Datenbank gespeichert, es sollten aber die Zahlen
1,4,7,10 eingetragen werden, oder verstehe ich da etwas nicht?

**Comment by Apollon77** [comment]
Dann mach doch mal debug log und mache genau mal das 1..10 und poste das log davon ... dann gehen wirs durch

**Comment by Hans-Zwiesel** [comment]
Bitte sehr: sql.1

host.raspi4 | 2020-12-12 16:49:48.342 | debug | Incoming Host message getLogs
-- | -- | -- | --
sql.1 | 2020-12-12 16:49:33.188 | debug | (30417) system.adapter.admin.0: logging true
host.raspi4 | 2020-12-12 16:49:33.130 | debug | Incoming Host message getLogs
sql.1 | 2020-12-12 16:46:59.633 | debug | (30417) system.adapter.admin.0: logging false
sql.1 | 2020-12-12 16:46:53.739 | debug | (30417) sendTo "getHistory" to system.adapter.admin.0 from system.adapter.sql.1
sql.1 | 2020-12-12 16:46:53.738 | debug | (30417) Send: 17 of: 17 in: 25ms
sql.1 | 2020-12-12 16:46:53.714 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:46:53.713 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:45:12.412 | debug | (30417) sendTo "getHistory" to system.adapter.admin.0 from system.adapter.sql.1
sql.1 | 2020-12-12 16:45:12.411 | debug | (30417) Send: 17 of: 17 in: 12ms
sql.1 | 2020-12-12 16:45:12.400 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:45:12.399 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:45:11.482 | debug | (30417) system.adapter.admin.0: logging true
host.raspi4 | 2020-12-12 16:45:11.440 | debug | Incoming Host message getLogs
sql.1 | 2020-12-12 16:45:10.917 | debug | (30417) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(137, 1607787909905, 10, 0, 4, 0);
sql.1 | 2020-12-12 16:45:10.917 | debug | (30417) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for  mqtt.0.Global.test (type: 0, ID: 137) and state:  {"val":10,"ack":false,"ts":1607787909905,"q":0,"from":"system.adapter.admin.0","user":"
sql.1 | 2020-12-12 16:45:10.916 | debug | (30417) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.Global.test
sql.1 | 2020-12-12 16:45:10.916 | debug | (30417) pushValueIntoDB called for mqtt.0.Global.test (type: 0, ID:  137) and state:  {"val":10,"ack":false,"ts":1607787909905,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1607
sql.1 | 2020-12-12 16:45:10.916 | debug | (30417) Datatype mqtt.0.Global.test: Currently: number, StorageType: Number
sql.1 | 2020-12-12 16:45:09.913 | debug | (30417) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(137, 1607787907381, 9, 0, 4, 0);
sql.1 | 2020-12-12 16:45:09.913 | debug | (30417) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for  mqtt.0.Global.test (type: 0, ID: 137) and state:  {"val":9,"ack":false,"ts":1607787907381,"q":0,"from":"system.adapter.admin.0","user":"s
sql.1 | 2020-12-12 16:45:09.912 | debug | (30417) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.Global.test
sql.1 | 2020-12-12 16:45:09.912 | debug | (30417) pushValueIntoDB called for mqtt.0.Global.test (type: 0, ID:  137) and state:  {"val":9,"ack":false,"ts":1607787907381,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":16077
sql.1 | 2020-12-12 16:45:09.911 | debug | (30417) Datatype mqtt.0.Global.test: Currently: number, StorageType: Number
sql.1 | 2020-12-12 16:45:09.910 | debug | (30417) Min-Delta reached mqtt.0.Global.test, last-value=7, new-value=10, ts=1607787909905
sql.1 | 2020-12-12 16:45:09.909 | debug | (30417) new value received for mqtt.0.Global.test, new-value=10, ts=1607787909905, relog=false
sql.1 | 2020-12-12 16:45:07.386 | debug | (30417) Min-Delta not reached mqtt.0.Global.test, last-value=7, new-value=9, ts=1607787907381
sql.1 | 2020-12-12 16:45:07.386 | debug | (30417) new value received for mqtt.0.Global.test, new-value=9, ts=1607787907381, relog=false
sql.1 | 2020-12-12 16:45:06.761 | debug | (30417) sendTo "getHistory" to system.adapter.admin.0 from system.adapter.sql.1
sql.1 | 2020-12-12 16:45:06.760 | debug | (30417) Send: 15 of: 15 in: 11ms
sql.1 | 2020-12-12 16:45:06.750 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:45:06.749 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:45:04.476 | debug | (30417) Min-Delta not reached mqtt.0.Global.test, last-value=7, new-value=8, ts=1607787904471
sql.1 | 2020-12-12 16:45:04.475 | debug | (30417) new value received for mqtt.0.Global.test, new-value=8, ts=1607787904471, relog=false
sql.1 | 2020-12-12 16:45:02.730 | debug | (30417) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(137, 1607787901714, 7, 0, 4, 0);
sql.1 | 2020-12-12 16:45:02.729 | debug | (30417) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for  mqtt.0.Global.test (type: 0, ID: 137) and state:  {"val":7,"ack":false,"ts":1607787901714,"q":0,"from":"system.adapter.admin.0","user":"s
sql.1 | 2020-12-12 16:45:02.729 | debug | (30417) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.Global.test
sql.1 | 2020-12-12 16:45:02.728 | debug | (30417) pushValueIntoDB called for mqtt.0.Global.test (type: 0, ID:  137) and state:  {"val":7,"ack":false,"ts":1607787901714,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":16077
sql.1 | 2020-12-12 16:45:02.727 | debug | (30417) Datatype mqtt.0.Global.test: Currently: number, StorageType: Number
sql.1 | 2020-12-12 16:45:01.724 | debug | (30417) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(137, 1607787899122, 6, 0, 4, 0);
sql.1 | 2020-12-12 16:45:01.723 | debug | (30417) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for  mqtt.0.Global.test (type: 0, ID: 137) and state:  {"val":6,"ack":false,"ts":1607787899122,"q":0,"from":"system.adapter.admin.0","user":"s
sql.1 | 2020-12-12 16:45:01.723 | debug | (30417) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.Global.test
sql.1 | 2020-12-12 16:45:01.722 | debug | (30417) pushValueIntoDB called for mqtt.0.Global.test (type: 0, ID:  137) and state:  {"val":6,"ack":false,"ts":1607787899122,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":16077
sql.1 | 2020-12-12 16:45:01.721 | debug | (30417) Datatype mqtt.0.Global.test: Currently: number, StorageType: Number
sql.1 | 2020-12-12 16:45:01.721 | debug | (30417) Min-Delta reached mqtt.0.Global.test, last-value=4, new-value=7, ts=1607787901714
sql.1 | 2020-12-12 16:45:01.720 | debug | (30417) new value received for mqtt.0.Global.test, new-value=7, ts=1607787901714, relog=false
sql.1 | 2020-12-12 16:45:01.418 | debug | (30417) sendTo "getHistory" to system.adapter.admin.0 from system.adapter.sql.1
sql.1 | 2020-12-12 16:45:01.418 | debug | (30417) Send: 13 of: 13 in: 5ms
sql.1 | 2020-12-12 16:45:01.414 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:45:01.413 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:44:59.128 | debug | (30417) Min-Delta not reached mqtt.0.Global.test, last-value=4, new-value=6, ts=1607787899122
sql.1 | 2020-12-12 16:44:59.127 | debug | (30417) new value received for mqtt.0.Global.test, new-value=6, ts=1607787899122, relog=false
sql.1 | 2020-12-12 16:44:56.403 | debug | (30417) Min-Delta not reached mqtt.0.Global.test, last-value=4, new-value=5, ts=1607787896397
sql.1 | 2020-12-12 16:44:56.402 | debug | (30417) new value received for mqtt.0.Global.test, new-value=5, ts=1607787896397, relog=false
sql.1 | 2020-12-12 16:44:55.406 | debug | (30417) sendTo "getHistory" to system.adapter.admin.0 from system.adapter.sql.1
sql.1 | 2020-12-12 16:44:55.405 | debug | (30417) Send: 13 of: 13 in: 10ms
sql.1 | 2020-12-12 16:44:55.396 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:44:55.395 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:44:54.348 | debug | (30417) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(137, 1607787893333, 4, 0, 4, 0);
sql.1 | 2020-12-12 16:44:54.347 | debug | (30417) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for  mqtt.0.Global.test (type: 0, ID: 137) and state:  {"val":4,"ack":false,"ts":1607787893333,"q":0,"from":"system.adapter.admin.0","user":"s
sql.1 | 2020-12-12 16:44:54.347 | debug | (30417) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.Global.test
sql.1 | 2020-12-12 16:44:54.346 | debug | (30417) pushValueIntoDB called for mqtt.0.Global.test (type: 0, ID:  137) and state:  {"val":4,"ack":false,"ts":1607787893333,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":16077
sql.1 | 2020-12-12 16:44:54.345 | debug | (30417) Datatype mqtt.0.Global.test: Currently: number, StorageType: Number
sql.1 | 2020-12-12 16:44:53.343 | debug | (30417) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(137, 1607787890375, 3, 0, 4, 0);
sql.1 | 2020-12-12 16:44:53.342 | debug | (30417) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for  mqtt.0.Global.test (type: 0, ID: 137) and state:  {"val":3,"ack":false,"ts":1607787890375,"q":0,"from":"system.adapter.admin.0","user":"s
sql.1 | 2020-12-12 16:44:53.341 | debug | (30417) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.Global.test
sql.1 | 2020-12-12 16:44:53.341 | debug | (30417) pushValueIntoDB called for mqtt.0.Global.test (type: 0, ID:  137) and state:  {"val":3,"ack":false,"ts":1607787890375,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":16077
sql.1 | 2020-12-12 16:44:53.340 | debug | (30417) Datatype mqtt.0.Global.test: Currently: number, StorageType: Number
sql.1 | 2020-12-12 16:44:53.339 | debug | (30417) Min-Delta reached mqtt.0.Global.test, last-value=1, new-value=4, ts=1607787893333
sql.1 | 2020-12-12 16:44:53.338 | debug | (30417) new value received for mqtt.0.Global.test, new-value=4, ts=1607787893333, relog=false
sql.1 | 2020-12-12 16:44:50.691 | debug | (30417) system.adapter.admin.0: logging false
sql.1 | 2020-12-12 16:44:50.380 | debug | (30417) Min-Delta not reached mqtt.0.Global.test, last-value=1, new-value=3, ts=1607787890375
sql.1 | 2020-12-12 16:44:50.379 | debug | (30417) new value received for mqtt.0.Global.test, new-value=3, ts=1607787890375, relog=false
sql.1 | 2020-12-12 16:44:50.199 | debug | (30417) sendTo "getHistory" to system.adapter.admin.0 from system.adapter.sql.1
sql.1 | 2020-12-12 16:44:50.198 | debug | (30417) Send: 11 of: 11 in: 20ms
sql.1 | 2020-12-12 16:44:50.179 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:44:50.178 | debug | (30417) SELECT ts, val, ack, `iobroker`.sources.name as 'from', q FROM  `iobroker`.ts_number INNER JOIN `iobroker`.sources ON  `iobroker`.sources.id=`iobroker`.ts_number._from WHERE   `iobroker`.ts_numb
sql.1 | 2020-12-12 16:44:47.990 | debug | (30417) Min-Delta not reached mqtt.0.Global.test, last-value=1, new-value=2, ts=1607787887985
sql.1 | 2020-12-12 16:44:47.989 | debug | (30417) new value received for mqtt.0.Global.test, new-value=2, ts=1607787887985, relog=false
sql.1 | 2020-12-12 16:44:46.169 | debug | (30417) INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(137, 1607787885159, 1, 0, 4, 0);
sql.1 | 2020-12-12 16:44:46.168 | debug | (30417) pushValueIntoDB-prepareTaskCheckTypeAndDbId RESULT for  mqtt.0.Global.test (type: 0, ID: 137) and state:  {"val":1,"ack":false,"ts":1607787885159,"q":0,"from":"system.adapter.admin.0","user":"s
sql.1 | 2020-12-12 16:44:46.168 | debug | (30417) prepareTaskCheckTypeAndDbId CALLED for mqtt.0.Global.test
sql.1 | 2020-12-12 16:44:46.167 | debug | (30417) pushValueIntoDB called for mqtt.0.Global.test (type: 0, ID:  137) and state:  {"val":1,"ack":false,"ts":1607787885159,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":16077
sql.1 | 2020-12-12 16:44:46.166 | debug | (30417) Datatype mqtt.0.Global.test: Currently: number, StorageType: Number
sql.1 | 2020-12-12 16:44:45.164 | debug | (30417) Min-Delta reached mqtt.0.Global.test, last-value=99999999, new-value=1, ts=1607787885159
sql.1 | 2020-12-12 16:44:45.163 | debug | (30417) new value received for mqtt.0.Global.test, new-value=1, ts=1607787885159, relog=false

**Comment by Apollon77** [comment]
Ja, wie ich es vermutet habe ... hier schiesst quasi ein "Audit feature" rein. Das muss man mal prüfen in wieweit das hier "Intended" ist.

Am Ende geht es da primär auch um die Grafische darstellung.

Der Adapter merkt sich die übersprungenen Werte und wenn ein neuer Wert geschrieben wird, wird auch der zuletzt übersprungene mit geschrieben mit seinem timestamp.
Das erklärt exakt das von Dir beschriebene:
1 -> wird geloggt
2 -> übersprungen, gemerkt
3 -> übersprungen, überschreibt gemerkt
4 -> wird geloggt, aber die 3 mit
5 -> übersprungen, gemerkt
6 -> übersprungen, überschreibt gemerkt
7 -> wird geloggt, aber die 6 mit
...

Muss ich mir irgendwann an ruhigen Tagen genau ansehen

**Comment by Hans-Zwiesel** [comment]
Super dass Du es verstanden hast was ich meine.
Ich wundere mich nur, dass das noch niemand sonst bemerkt hat, ich kenne das
Verhalten schon seit ca. einem Jahr.
Jetzt ist es aber wichtig, weil sonst die MySql zugedröhnt wird und ich sehr viel Aufwand hätte,
im Client die Daten zu begrenzen.

**Comment by Hans-Zwiesel** [comment]
Hallo Apollon77,
ist das Problem noch am Schirm?

**Comment by JayVee2** [comment]
@Hans-Zwiesel: Danke, dass Du das Thema so gut aufbereitet hast. Ich mache auch schon ewig an diesem Effekt herum, aber bei Floating Point wirkt es noch schräger was passiert. Deshalb danke fürs aufbereiten.
@Apollon77: Bist Du das schon dazugekommen?
Grüße
-jayvee

**Comment by Apollon77** [comment]
Ne noch keine Zeit gehabt

**Comment by Hans-Zwiesel** [comment]
Seit ungefähr 4 Wochen wird manchmal ein Wert mit 0 geschrieben.
Die Zeit zum nächsten Wert ist 1 sec. Das kann gar nicht sein, denn der Fühler wird nur
alle 5 min. abgefragt.
Es ist somit kein Wert über mqtt übertragen worden, der SQL Adapter schreibt jetzt "eigene" Werte.
Das war vorher nicht so.

**Comment by manoloxxl** [comment]
Hab übrigens das gleiche Problem und hänge mich daher hier mal ran.

**Comment by arndl** [comment]
Ich habe ebenfalls das gleiche Problem. Obwohl der Abstand auf 1 eingestellt ist, wird jeder kWh Wert doppelt in die Datenbank geschrieben. Ich möchte nicht jede Änderung vom Smartmeter speichern sondern nur wenn sich der Wert vor dem Komma ändert.

![Screenshot doppelte Werte](https://user-images.githubusercontent.com/24986855/139705648-ff806992-825b-4401-ac55-05173098693f.PNG)

**Comment by arndl** [comment]
Der History Adapter hat das gleiche Problem. Insofern ist die Fehlersuche nicht nur auf den SQL-Adapter zu beschränken.
Ich habe mir den Code in main.cs angesehen: In den folgenden Code-Zeilen in der Funktion pushHistory() ist explizit festgelegt, dass der skipped Wert vor dem eigentlichen Wert zusätzlich gespeichert wird:

            if (settings.changesOnly && sqlDPs[id].skipped) {
                sqlDPs[id].state = sqlDPs[id].skipped;
                pushHelper(id);
            }

Die gleichen Zeilen finden sich im History Adapter. Am 12.08.2017 wurde von bluefox eine "save last value" Option hinzugefügt. Da sah die if Bedingung noch so aus:

            if (settings.changesOnly && history[id].skipped && settings.saveLastValue)

Kann man das Speichern der skipped Values nicht ganz rausnehmen? Es sieht so aus, als wäre da im Laufe der Zeit etwas durcheinander gelaufen...
Wenn übersprungene Werte nachträglich doch noch gespeichert werden sollen, dann evtl. durch das timerRelog? Vielleicht war es so gedacht (steht aber so nicht im Code).

**Comment by Apollon77** [comment]
Es gibt Gründe dafür das es so ist wie es ist ... Man muss es umbauen das das Feature was die geloggten Daten für eine visualisierung sinnvoll aufbereitet (das ist der Grund) umschaltbar ist ...

**Comment by arndl** [comment]
Ich versteh's noch nicht: Wenn ich nur bestimmte Werte loggen will weil sonst z.B. viel zu viele Werte geloggt werden, warum sollte ich dann den vorletzten Wert für eine Visualisierung dazu haben wollen? Um welche Art Visualisierung geht es?

Was ich mir allerdings vorstellen kann ist folgendes Szenario:

- Ein State nimmt nacheinander die Werte 0, 1, 2, 3, 4, ..., 100 an.
- Minimale Differenz soll 10 sein. Also wird 0, 10, 20, 30, ... geloggt.
- Wenn sich über längere Zeit - sagen wir eine Stunde - der State nicht ändert, möchte ich trotzdem einen Wert aufzeichnen. Das wäre prinzipiell die Einstellung "trotzdem gleiche Werte aufzeichnen (Sekunden)" damit der Graf z.B. in Grafana nicht "abreißt".

Tritt also zwischen 10 und 20 ein Abstand von mehr als einer Stunde auf, so wäre es aufgrund der Bezeichnung dieser Option richtig, dass nach einer Stunde der Wert 10 erneut geschrieben wird. Allerdings kann kurz vor Ablauf einer Stunde der tatsächliche (übersprungene) Wert bereits 15 gewesen sein. Der ein oder andere könnte nun wollen, dass die 15 statt der 10 geloggt wird. Das würde für mich Sinn machen und der Code sieht so aus, als wäre es auch so gedacht gewesen...

Aber vielleicht meinst Du genau das mit "umbauen"?

**Comment by Apollon77** [comment]
Das ganze ist in "history 2.0.0" mal angepasst ... bevor ich den Change ausrolle auf sql wäre es cool wenn es mal mit history gegengetestet werden könnte ?!

Detals dazu: https://forum.iobroker.net/topic/54197/test-adapter-history-2-0-0

**Comment by Apollon77** [comment]
Please try 2.0.0 from GitHub

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/54662/test-adapter-sql-2-0-0
