### ISSUE TITLE
SQL Settings just "undefined"

### ISSUE THREAD

**Issue by twobeass** [ioBroker/ioBroker.sql#142]
**Describe the bug**  
After opening the SQL Settings from a Datapoint i just get the Message "undefined" 

**To Reproduce**  
1. Go to a datapoint
2. Click on settings
3. Scroll down to sql

**Expected behavior**  
I expected the settings to open

**Screenshots & Logfiles**  
Here you can see the result
![image](https://user-images.githubusercontent.com/4639195/102224429-3a830f80-3ee6-11eb-96a2-72964ae44af2.png)

**Versions:**  
 - Adapter version: 1.15.3
 - JS-Controller version: 3.1.6
 - Node version: 10.23.0
 - Operating system: Raspian Buster

**Comment by twobeass** [comment]
Seems to be a problem in combination with linkeddevices > 1.2.2
I downgraded a couple of versions, this is the first one without the error...

**Comment by Apollon77** [comment]
SO an issue at linked devices would be an idea or ?! ANd the browser console really shows no error or such?

**Comment by twobeass** [comment]
That was an [Issue ](https://github.com/Scrounger/ioBroker.linkeddevices/issues/57)with [linkeddevices-Adapter](https://github.com/Scrounger/ioBroker.linkeddevices) and it is [fixed ](https://github.com/Scrounger/ioBroker.linkeddevices/commit/f0533ccba9b7cf2ffbe7b40ba8f0346a58520216) by [Scrounger](https://github.com/Scrounger)
Thanks and close...
