### ISSUE TITLE
Adapter opens more connections than it should be allowed to

### ISSUE THREAD

**Issue by fbeister** [ioBroker/ioBroker.sql#143]
**Describe the bug**  
I recently found out, that the adapter seems to open more connections than it should. For a very long time, I was running a MySQL server alongside ioBroker on the same machine. A week ago, the SQL server got stuck again and again and after restarting it took at most some hours before it stopped accepting connections again.

The machine this is running on is not very powerful so I decided to migrate to AWS RDS MySQL 8.0.21 for my data storage. There, things seemed to be running smoothly at first, but after a while I saw that there were too many connections, although I set the adapter options to a maximum of 10 with parallel connections enabled and write NULL disabled:

![Settings](https://user-images.githubusercontent.com/7522238/102708344-b7293b80-42a2-11eb-83c1-501e413a2769.png)

Nevertheless, the number of connections grows until new connections are refused again and again. I have added a cyclic adapter restart at 4am so things went to normal then. Then, this morning, I updated from 1.12.1 to 1.15.3 - I'll report back regarding the number of connections

![RDS graph](https://user-images.githubusercontent.com/7522238/102708473-adec9e80-42a3-11eb-95e6-fc950d881d6f.png)

**To Reproduce**  
1. Use SQL adapter with limited number of connections set

**Expected behavior**  
The number of connections never goes above the maximum set in the adapter

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 1.12.1 first, now 1.15.3
 - JS-Controller version: 3.1.4
 - Node version: 12.16.3
 - Operating system: Ubuntu Linux 18.04.4

**Comment by Apollon77** [comment]
Hi - thank you for the report, very tínteresting ... then this seems to be an issue in sql-client library :-(

we set https://github.com/ioBroker/ioBroker.sql/blob/master/main.js#L347-L351 and this normally should work with the https://github.com/intellinote/sql-client/blob/master/lib/sql-client-pool.coffee#L110 ... so that would be a very deep dig :-(

**Comment by fbeister** [comment]
I now left it running for some days with 1.15.3 (was 1.13.1 before, not 1.12.1 as stated in the description). There are no more connections than allowed but once I received multiple "Cannot queue new requests, because more than 100" repeated for about 4 minutes and then everything went back to OK. Will leave this open if you don't mind

**Comment by Apollon77** [comment]
On that topic nthing was changed since 1.12.0 as original fix ... hm ... I also wonder why you get the error with 100 ... Can you please check the real settings? Admin- Objects - clear all filters - search for system.adapter.sql.0 and click right on the pencil icon - "raw" tab and post the json here please

**Comment by fbeister** [comment]
[raw.json.txt](https://github.com/ioBroker/ioBroker.sql/files/5729264/raw.json.txt)

**Comment by Apollon77** [comment]
ok, da steht 30 als connection limit

**Comment by Apollon77** [comment]
would be great to get another chart hwo it behaves ..thank you!

**Comment by fbeister** [comment]
> ok, da steht 30 als connection limit

Yes, I have played around with that setting a bit.

**Comment by fbeister** [comment]
> would be great to get another chart hwo it behaves ..thank you!

I don't think the chart would be worth posting. It's between 0 and 1 all the time - only when I connect with MySQL workbench it goes up to 4-5

**Comment by Apollon77** [comment]
I think restsrting the adapter might be good to see - or enabling the "write nulls" :-)
