### ISSUE TITLE
enableHistory in javascript beschädigt Datenpunkt

### ISSUE THREAD

**Issue by fs-plugins** [ioBroker/ioBroker.sql#144]
folgendes zerschießt mir die hm-rega.0 -Instanz:

```
sendTo('sql.1', 'enableHistory', {
    id: 'hm-rpc.3.0000D569A397CE.1.STATE',
    options: {
        changesOnly:  true,
        debounce:     1000,  //entprellzeit
        retention:    259200, //Aufbewahrungszeit
        maxLength:    2,
        changesRelogInterval:600,
        aliasId: "Bad-fenster"
    }, function (result) {
    if (result.error) {
        console.log(result.error);
    }
    if (result.success) {
        //successfull enabled
    }
    }
});
```
sql.1 (653) Cannot insert INSERT INTO iobroker.ts_number (id, ts, val, ack, _from, q) VALUES(73, 1610637778109, CLOSED, 1, 1, 0);: Error: ER_BAD_FIELD_ERROR: Unknown column 'CLOSED' in 'field list' (id: Bad-fenster)

am entsprechenden Datenpunkt ist history aktiviert und es werden wie erwartet 0/1 gespeichert bei offen/geschlossen
nach dem script steht im Datenpunkt jedoch statt "CLOSED(0)" nur noch "CLOSED" drin und im Rest des Systems (incl. VIS) funktioniert alles was auf diesen Datenpunkt zugreift nicht mehr bzw reagiert falsch
(der DP ist vom hm-adapter angelegt worden und wurde von mir nicht verändert, dp hat Eigenschaft write=false)

anschließender Neustart von hm-rega.0 repariert das dann wieder

**Comment by Apollon77** [comment]
Wie ist denn der Datenopunkt für History an sich definiert? Ich würde ja sagen das DU einfach hier nicht alle Parameter angibst. enableHitsory überschreibt aktuell den gesamten History-Daten-Teil und ich würde tippen die fehlt was.

Rufe mal den Datenpunkt im Admin unter "Objekte" auf, klicke rechts auf den Stift.Icon und schau was unter "Raw Experten only" im custom."sql.1" bereich steht und gleiche das mit deinen Daten hier ab

**Comment by fs-plugins** [comment]
dann ist es der hm-adapter der den DP falsch anlegt?
`{
  "type": "state",
  "common": {
    "name": "Fenster Bad:1.STATE",
    "def": "CLOSED",
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1,
    "states": {
      "0": "CLOSED",
      "1": "OPEN"
    },
    "role": "value.window",
    "custom": {
      "sql.1": {
        "changesOnly": true,
        "debounce": 1000,
        "retention": 259200,
        "maxLength": 2,
        "changesRelogInterval": 600,
        "aliasId": "Bad-fenster",
        "enabled": true
      }
    }
  },
  "native": {
    "MIN": "CLOSED",
    "UNIT": "\"\"",
    "OPERATIONS": 5,
    "MAX": "OPEN",
    "FLAGS": 1,
    "ID": "STATE",
    "TAB_ORDER": 0,
    "TYPE": "ENUM",
    "DEFAULT": "CLOSED",
    "VALUE_LIST": [
      "CLOSED",
      "OPEN"
    ],
    "CONTROL": "DOOR_SENSOR.STATE"
  },
  "from": "system.adapter.sql.1",
  "user": "system.user.admin",
  "ts": 1610637777957,
  "_id": "hm-rpc.3.0000D569A397CE.1.STATE",
  "acl": {
    "object": 1636,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by Apollon77** [comment]
Ja, bitte hm-rpc prüfen ... der "default" wert ist ein String, aber der Datentyp ist "number" ... das ist das issue

**Comment by fs-plugins** [comment]
ah, dann muss ich beim hm-rpc melden - sorry das ich diesen hier in Verdacht hatte (ist mir halt nicht aufgefallen das es sonst Probleme macht, erst beim Start des script sind plötzlich Fenster offen usw. ;-)

**Comment by Apollon77** [comment]
Alles gut der Fall war auch tricky ;-)

**Comment by fs-plugins** [comment]
dankeschön - issu ist erstellt, test mit händisch geändertem default erfolgreich
dennoch eine OffTopic-Frage weil beim Testen grad bemerkt: kann es sein, das die script-Funktion den jeweiligen State auf default setzt? (und muss das wirklich sein?)

**Comment by Apollon77** [comment]
Das ist ein js-controller 3.1 bug und ist im js-controller 3.2 gefixt

**Comment by fs-plugins** [comment]
dankeschön
(und nu besser zumachen onTopic ist ja erledigt) ;-)
