### ISSUE TITLE
Fehlermeldungen bei Update auf 1.15.4

### ISSUE THREAD

**Issue by testit2020** [ioBroker/ioBroker.sql#147]
Zur Info folgende Meldungen beim Update:

$ ./iobroker upgrade sql
Update sql from @1.15.3 to @1.15.4
host.raspberrypi Adapter "system.adapter.sql.0" is stopped.
NPM version: 6.14.8
npm install iobroker.sql@1.15.4 --loglevel error --prefix "/opt/iobroker" (System call)
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘strftimeFunc’:Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:22804:52: note: in expansion of macro ‘SQLITE_DYNAMIC’                       z==zBuf ? SQLITE_TRANSIENT : SQLITE_DYNAMIC);                                                    ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3ErrorWithMsg’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:31304:54: note: in expansion of macro ‘SQLITE_DYNAMIC’     sqlite3ValueSetStr(db->pErr, -1, z, SQLITE_UTF8, SQLITE_DYNAMIC);                                                      ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3VdbeMemSetStr’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:76767:15: note: in expansion of macro ‘SQLITE_DYNAMIC’     if( xDel==SQLITE_DYNAMIC ){               ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘valueFromExpr’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:77179:55: note: in expansion of macro ‘SQLITE_DYNAMIC’       sqlite3ValueSetStr(pVal, -1, zVal, SQLITE_UTF8, SQLITE_DYNAMIC);                                                       ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:77231:29: note: in expansion of macro ‘SQLITE_DYNAMIC’                          0, SQLITE_DYNAMIC);                             ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3VdbeExec’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:92894:38: warning: cast between incompatible function types from ‘int (*)(u32,  void *, void *, void *)’ {aka ‘int (*)(unsigned int,  void *, void *, void *)’} to ‘void (*)(void *, const char *)’ [-Wcast-function-type]       void (*x)(void*,const char*) = (void(*)(void*,const char*))db->xTrace;                                      ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘printfFunc’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:117034:25: note: in expansion of macro ‘SQLITE_DYNAMIC’                         SQLITE_DYNAMIC);                         ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘generateColumnNames’:Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:130871:58: note: in expansion of macro ‘SQLITE_DYNAMIC’         sqlite3VdbeSetColName(v, i, COLNAME_NAME, zName, SQLITE_DYNAMIC);                                                          ^~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:14581:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:130878:52: note: in expansion of macro ‘SQLITE_DYNAMIC’       sqlite3VdbeSetColName(v, i, COLNAME_NAME, z, SQLITE_DYNAMIC);                                                    ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3_trace’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:162428:16: warning: cast between incompatible function types from ‘void (*)(void *, const char *)’ to ‘int (*)(u32,  void *, void *, void *)’ {aka ‘int (*)(unsigned int,  void *, void *, void *)’} [-Wcast-function-type]   db->xTrace = (int(*)(u32,void*,void*,void*))xTrace;                ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3_db_status’:Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:21627:10: warning: this statement may fall through [-Wimplicit-fallthrough=]       op = SQLITE_DBSTATUS_CACHE_WRITE+1;       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:21629:5: note: here     case SQLITE_DBSTATUS_CACHE_HIT:     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3_str_vappendf’:Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:28505:19: warning: this statement may fall through [-Wimplicit-fallthrough=]         flag_long = sizeof(char*)==sizeof(i64) ? 2 :         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      sizeof(char*)==sizeof(long int) ? 1 : 0;                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:28508:7: note: here       case etORDINAL:       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:28510:19: warning: this statement may fall through [-Wimplicit-fallthrough=]         cThousand = 0;         ~~~~~~~~~~^~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:28512:7: note: here       case etDECIMAL:       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3GetToken’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:159496:9: warning: this statement may fall through [-Wimplicit-fallthrough=]       if( !sqlite3Isdigit(z[1]) )         ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:159505:5: note: here     case CC_DIGIT: {     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:159595:9: warning: this statement may fall through [-Wimplicit-fallthrough=]       if( z[1]=='\'' ){         ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:159609:5: note: here     case CC_ID: {     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3ExprCodeTarget’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:103317:25: warning: this statement may fall through [-Wimplicit-fallthrough=]     case TK_AGG_COLUMN: {                         ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:103342:5: note: here     case TK_COLUMN: {     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘exprImpliesNotNull’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:104896:9: warning: this statement may fall through [-Wimplicit-fallthrough=]       if( exprImpliesNotNull(pParse, p->pRight, pNN, iTab, seenNot) ) return 1;         ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:104899:5: note: here     case TK_SPAN:     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘impliesNotNullRow’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:105028:17: warning: this statement may fall through [-Wimplicit-fallthrough=]     case TK_GE: {                 ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:105047:5: note: here     default:     ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘resolveP2Values’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:78359:13: warning: this statement may fall through [-Wimplicit-fallthrough=]           if( pOp->p2!=0 ) p->readOnly = 0;             ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:78362:9: note: here         case OP_AutoCommit:         ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:78400:26: warning: this statement may fall through [-Wimplicit-fallthrough=]         case OP_VFilter: {                          ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:78409:9: note: here         default: {         ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘resolveExprStep’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:98612:20: warning: this statement may fall through [-Wimplicit-fallthrough=]     case TK_ISNOT: {                    ^Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:98628:5: note: here     case TK_BETWEEN:     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘fkActionTrigger’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:120160:11: warning: this statement may fall through [-Wimplicit-fallthrough=]         if( !pChanges ){           ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:120164:7: note: here       default:       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3GenerateConstraintChecks’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:122095:17: warning: this statement may fall through [-Wimplicit-fallthrough=]         onError = OE_Abort;                 ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:122098:7: note: here       case OE_Rollback:       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:122156:9: warning: this statement may fall through [-Wimplicit-fallthrough=]         sqlite3UpsertDoUpdate(pParse, pUpsert, pTab, 0, iDataCur);         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:122160:7: note: here       case OE_Ignore: {       ^~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:122377:9: warning: this statement may fall through [-Wimplicit-fallthrough=]         sqlite3UpsertDoUpdate(pParse, pUpsert, pTab, pIdx, iIdxCur+ix);         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:122381:7: note: here       case OE_Ignore: {       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘sqlite3VdbeExec’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:86166:5: warning: this statement may fall through [-Wimplicit-fallthrough=]   if( (pIn3->flags & MEM_Null)==0 ) break;     ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:86200:1: note: here case OP_Halt: { ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:86335:15: warning: this statement may fall through [-Wimplicit-fallthrough=]   pOp->opcode = OP_String;               ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:86352:1: note: here case OP_String: {          /* out2 */ ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:89617:19: warning: this statement may fall through [-Wimplicit-fallthrough=] case OP_IfNoHope: {     /* jump, in3 */                   ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:89625:1: note: here case OP_NoConflict:     /* jump, in3 */ ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:90551:38: warning: this statement may fall through [-Wimplicit-fallthrough=]   p->aCounter[SQLITE_STMTSTATUS_SORT]++;   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:90566:1: note: here case OP_Rewind: {        /* jump */ ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:91903:15: warning: this statement may fall through [-Wimplicit-fallthrough=]   pOp->opcode = OP_AggStep1;               ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:91906:1: note: here case OP_AggStep1: { ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘jsonRenderNode’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:185188:9: warning: this statement may fall through [-Wimplicit-fallthrough=]       if( pNode->jnFlags & JNODE_RAW ){         ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:185194:5: note: here     case JSON_REAL:     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘jsonReturn’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:185333:7: warning: this statement may fall through [-Wimplicit-fallthrough=]       int_as_real: /* fall through to real */;       ^~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:185335:5: note: here     case JSON_REAL: {     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘jsonEachColumn’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:187027:9: warning: this statement may fall through [-Wimplicit-fallthrough=]       if( p->bRecursive ){         ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:187037:5: note: here     default: {     ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘cellArea’:Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189401:22: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 5:  area  = p->aCoord[9].f - p->aCoord[8].f;                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189402:7: note: here       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189402:21: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189403:7: note: here       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189403:21: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189404:7: note: here       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189404:21: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189405:7: note: here       default: area *= p->aCoord[1].f - p->aCoord[0].f;       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189411:22: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 5:  area  = (i64)p->aCoord[9].i - (i64)p->aCoord[8].i;                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189412:7: note: here       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189412:21: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189413:7: note: here       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189413:21: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189414:7: note: here       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189414:21: warning: this statement may fall through [-Wimplicit-fallthrough=]       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:189415:7: note: here       default: area *= (i64)p->aCoord[1].i - (i64)p->aCoord[0].i;       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘rtreeCallbackConstraint’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188554:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+32, &c); aCoord[8] = c.f;                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188555:7: note: here       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.f;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188556:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+24, &c); aCoord[6] = c.f;                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188557:7: note: here       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.f;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188558:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+16, &c); aCoord[4] = c.f;                                              ~~~~~~~~~~^~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188559:7: note: here       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.f;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188560:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+8,  &c); aCoord[2] = c.f;                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188561:7: note: here       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.f;       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188569:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+32, &c); aCoord[8] = c.i;                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188570:7: note: here       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.i;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188571:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+24, &c); aCoord[6] = c.i;                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188572:7: note: here       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.i;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188573:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+16, &c); aCoord[4] = c.i;                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188574:7: note: here       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.i;       ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188575:56: warning: this statement may fall through [-Wimplicit-fallthrough=]                 readCoord(pCellData+8,  &c); aCoord[2] = c.i;                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188576:7: note: here       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.i;       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘rtreeNonleafConstraint’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188631:9: warning: this statement may fall through [-Wimplicit-fallthrough=]       if( p->op!=RTREE_EQ ) break;  /* RTREE_LE and RTREE_LT end here */         ^
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:188634:5: note: here     default: /* RTREE_GT or RTREE_GE,  or fallthrough of RTREE_EQ */     ^~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘fts3SnippetFunc’:Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169927:22: warning: this statement may fall through [-Wimplicit-fallthrough=]     case 6: nToken = sqlite3_value_int(apVal[5]);                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169928:5: note: here     case 5: iCol = sqlite3_value_int(apVal[4]);     ^~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169928:20: warning: this statement may fall through [-Wimplicit-fallthrough=]     case 5: iCol = sqlite3_value_int(apVal[4]);                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169929:5: note: here     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);     ^~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169929:38: warning: this statement may fall through [-Wimplicit-fallthrough=]     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169930:5: note: here     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);     ^~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169930:33: warning: this statement may fall through [-Wimplicit-fallthrough=]     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169931:5: note: here     case 2: zStart = (const char*)sqlite3_value_text(apVal[1]);     ^~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c: In function ‘fts3ColumnMethod’:
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169684:14: warning: this statement may fall through [-Wimplicit-fallthrough=]         iCol = p->nColumn;         ~~~~~^~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3320300/sqlite3.c:169688:5: note: here     default:     ^~~~~~~
../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginInitialize(node_sqlite3::Database::Baton*)’:../src/backup.cc:179:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(         ^~~~~~
In file included from ../src/backup.cc:4:../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginStep(node_sqlite3::Backup::Baton*)’:../src/macros.h:182:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/backup.cc:252:5: note: in expansion of macro ‘BACKUP_BEGIN’     BACKUP_BEGIN(Step);     ^~~~~~~~~~~~
../src/backup.cc: In static member function ‘static void node_sqlite3::Backup::Work_BeginFinish(node_sqlite3::Backup::Baton*)’:../src/macros.h:182:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/backup.cc:319:5: note: in expansion of macro ‘BACKUP_BEGIN’     BACKUP_BEGIN(Finish);     ^~~~~~~~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:../src/database.cc:153:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(         ^~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:../src/database.cc:247:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(         ^~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:../src/database.cc:560:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(         ^~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:../src/database.cc:669:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(         ^~~~~~
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)’:../src/statement.cc:122:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(         ^~~~~~In file included from ../src/statement.cc:5:../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)’:../src/macros.h:146:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/statement.cc:344:5: note: in expansion of macro ‘STATEMENT_BEGIN’     STATEMENT_BEGIN(Bind);     ^~~~~~~~~~~~~~~../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)’:../src/macros.h:146:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/statement.cc:396:5: note: in expansion of macro ‘STATEMENT_BEGIN’     STATEMENT_BEGIN(Get);     ^~~~~~~~~~~~~~~../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)’:../src/macros.h:146:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/statement.cc:468:5: note: in expansion of macro ‘STATEMENT_BEGIN’     STATEMENT_BEGIN(Run);     ^~~~~~~~~~~~~~~../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)’:../src/macros.h:146:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/statement.cc:538:5: note: in expansion of macro ‘STATEMENT_BEGIN’     STATEMENT_BEGIN(All);     ^~~~~~~~~~~~~~~../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)’:../src/macros.h:146:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/statement.cc:639:5: note: in expansion of macro ‘STATEMENT_BEGIN’     STATEMENT_BEGIN(Each);     ^~~~~~~~~~~~~~~../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)’:../src/macros.h:146:9: warning: unused variable ‘status’ [-Wunused-variable]     int status = napi_create_async_work(                                       \         ^~~~~~../src/statement.cc:766:5: note: in expansion of macro ‘STATEMENT_BEGIN’     STATEMENT_BEGIN(Reset);     ^~~~~~~~~~~~~~~
upload [5] sql.admin /opt/iobroker/node_modules/iobroker.sql/admin/words.js words.js application/javascript
Update "system.adapter.sql.0"
upload [4] sql.admin /opt/iobroker/node_modules/iobroker.sql/admin/sql.png sql.png image/png
upload [3] sql.admin /opt/iobroker/node_modules/iobroker.sql/admin/index_m.html index_m.html text/html
upload [2] sql.admin /opt/iobroker/node_modules/iobroker.sql/admin/index.html index.html text/html
upload [1] sql.admin /opt/iobroker/node_modules/iobroker.sql/admin/custom_m.html custom_m.html text/html
upload [0] sql.admin /opt/iobroker/node_modules/iobroker.sql/admin/custom.html custom.html text/html
Adapter "sql" updated
host.raspberrypi Adapter "system.adapter.sql.0" is started
process exited with code 0

**Comment by Apollon77** [comment]
just notes and warnings from sqlite3 library ... wencan not do anything
