### ISSUE TITLE
Implement Buffering for Cases where database is not available

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.sql#158]
Implement a Data Buffering comparable to InfluxDB for cases where the database is not connected

**Comment by jensb** [comment]
Yes please! I am considering switching to Postgres (with TimescaleDB) but this would be a primary feature.

**Comment by Apollon77** [comment]
This feature is implemented in v2.0.0  on GitHub

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/54662/test-adapter-sql-2-0-0
