### ISSUE TITLE
Custom settings tab not full..

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.sql#159]
In admin ver 5.0.5 custom settings tab not have option Record changes only , Debounce time, Minimum difference from last value..
![Скриншот 20-04-2021 202050](https://user-images.githubusercontent.com/6728198/115438617-4a08c100-a216-11eb-91d9-5b998dfdf2aa.jpg)
![Скриншот 20-04-2021 202046](https://user-images.githubusercontent.com/6728198/115438619-4aa15780-a216-11eb-9e18-36d1fcfe978e.jpg)

**Comment by GermanBluefox** [comment]
Fixed in 1.15.7

**Comment by itProfi** [comment]
Yes. fixed!
