### ISSUE TITLE
Datenbankname mit "-" führt zu Problemen

### ISSUE THREAD

**Issue by ThoSt81** [ioBroker/ioBroker.sql#16]
Hallo,

ich habe ein ähnliches Problem wie hier: http://forum.iobroker.net/viewtopic.php?t=2979
In meinem Fall hat die DB einen festen Namen den ich nicht ändern kann:

db1075266-ccu

Alles vor "ccu" ist vorgegeben, also auch der Bindestrich.

Ich konnte leider keine Lösung finden und bekommen immer den folgenden Fehler:

`sql.0	2016-11-25 21:55:57.278	error	Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-ccu DEFAULT CHARACTER SET utf8 DEFAULT C
sql.0	2016-11-25 21:55:57.278	error	CREATE DATABASE db1075266-ccu DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci; `

Gibts dazu einen Workaround?

Gruß,
ThoSt

**Comment by Apollon77** [comment]
"-" ist in Tabellennamen bei den meisten DBs nicht erlaubt. Also "_" nehmen stattdessen oder so. Musst halt schauen was in deiner DB erlaubt ist.

**Comment by ThoSt81** [comment]
Hi,
es geht nicht um den Tabellennamen sondern Datenbanknamen.
Dieser wird durch meinen Provider vorgegeben und enthält IMMER einen "-"

Gruß,
ThoSt

**Comment by GermanBluefox** [comment]
Es muss vermutlich so aussehen:
CREATE DATABASE 'db1075266-ccu' DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci

Was für ein Typ SQL verwendest du?

**Comment by ThoSt81** [comment]
Hi,

ich verwende MySQL 5.6 (gehostet bei HostEurope).
Die Datenbank "db1075266-ccu" existiert bereits und wenn ich die Fehlermeldung richtig verstehe dann versucht das Modul diese DB anzulegen?

mysql.js:
`
exports.init = function (dbname) {
    return [
        "CREATE DATABASE " + dbname + " DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;",
        "CREATE TABLE " + dbname + ".sources    (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, name TEXT);",
        "CREATE TABLE " + dbname + ".datapoints (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, name TEXT, type INTEGER);",
        "CREATE TABLE " + dbname + ".ts_number  (id INTEGER, ts BIGINT, val REAL,    ack BOOLEAN, _from INTEGER, q INTEGER, PRIMARY KEY(id, ts));",
        "CREATE TABLE " + dbname + ".ts_string  (id INTEGER, ts BIGINT, val TEXT,    ack BOOLEAN, _from INTEGER, q INTEGER, PRIMARY KEY(id, ts));",
        "CREATE TABLE " + dbname + ".ts_bool    (id INTEGER, ts BIGINT, val BOOLEAN, ack BOOLEAN, _from INTEGER, q INTEGER, PRIMARY KEY(id, ts));"
    ];
};
`

Nehme ich allerdings die Zeile raus, so dass nur die Tabellen erstellt werden, dann bekommen ich folgenden Fehler:

`
sql.0	2016-11-26 10:37:47.453	error	Error: ER_NO_DB_ERROR: No database selected
sql.0	2016-11-26 10:37:47.453	error	CREATE TABLE db1075266-ccu.sources (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, name TEXT);
`

Sorry ich bin leider kein Entwickler und helfe mir mit Trial-and-Error weiter :)

**Comment by GermanBluefox** [comment]
Apollon77 hast du die Lösung verstanden? Könntest du einpflegen?

**Comment by Apollon77** [comment]
Man müsste überall mindestens den DB-Namen mit ' escapen. Weisst Du ob bei MySQL

'bla-blubb'.ts_bool 

valide ist?

oder muss es überall 

'bla-blubb.ts_bool'

werden?

**Comment by Apollon77** [comment]
Ich habs. sobald travis-ci wieder gescheid klappt ist das samt tests dafür im aktuellen pull request drin und kann dann auf github getestet werden. Melde mich nochmal wenn durch (denke morgen)

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.sql/pull/19 ... sobald gemerged kannst du testen

**Comment by Apollon77** [comment]
Auf git verfügbar.

**Comment by ThoSt81** [comment]
Danke! Werde es sobald wie möglich testen.

**Comment by ThoSt81** [comment]
N'abend. Leider weiterhin ohne Erfolg:

```
sql.0	2016-12-08 19:36:23.128	error	Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-ccu' at line 1
sql.0	2016-12-08 19:36:23.128	error	use db1075266-ccu;
```

Der MySQL Syntax an  sich scheint OK zu sein (es funktioniert wenn ich die create table statements in phpmyadmin ausführe), allerdings mag das Script weder den hardcodierten DBnamen mit "-" noch wenn ich die " + dbname + " variable nutzen. Die Variable wird wohl korrekt aufgelöst, der Fehler ist der selbe wie oben.

Wenn es hilft, kann ich gerne eine MySQL DB zur Verfügung stellen.

Gruß,
ThoSt

**Comment by Apollon77** [comment]
Wann genau passiert das denn? Wenn Du eigene Queries machst? Bitte bissl mehr Log und Details

**Comment by ThoSt81** [comment]
Sorry, ich habe den Fehler gefunden. Ich habe den falschen Snapshot gestartet, dort war noch die alte mysql.js drin.
Ich habe nun den code nochmal direkt von Git kopiert (ioBroker.sql/lib/mysql.js) und es scheint nun zu klappen.

Ich denke damit kann das Ticket geschlossen werden.

**Comment by Apollon77** [comment]
*puhh* erleichtert :-) Dann mach DU mal zu (ich kanns nicht weil muss Bluefox machen)

**Comment by ThoSt81** [comment]
:) danke!
