### ISSUE TITLE
Feature Request: IDs & Groups

### ISSUE THREAD

**Issue by 1rfsNet** [ioBroker/ioBroker.sql#161]
I would find it very useful if the original id is written to the database in addition to the alias id. So for example in Grafana you can take the alias id as display name, but internally I still have the correct id as unique identifier. 

Also, I would find it helpful if there was a grouping option. For example, if you could assign each datapoint to a group, then you could query the entire group directly. 
As an example, I could then easily make a query for all thermometers in Grafana and output them in a graph. Currently, I have to either include each thermometer individually in the query or work manually in the database.

**Comment by GermanBluefox** [comment]
Do you use grafana with SQL?
