### ISSUE TITLE
Cannot queue new requests, because more than 100

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sql#167]
Wenn man versucht in iob per Script mehrere Daten nach sql in die Datenbank zu schreiben kommt folgender Fehler/Log-Eintrag:

`Cannot queue new requests, because more than 100`

Ich konnte dies bisher nur umgehen, indem ich einen timeout eingebaut habe. Müsste/sollte aber doch vom Adapter abgefangen werden.

**Comment by Apollon77** [comment]
Das kann an sich nur bei sqlite passieren. Hier muss jede DB-Anfrage sequenziell gemacht werden, daher ist ein Puffer drin und der ist momentan auf 100 Einträge begrenzt. sqlite ist nicht für wirklich große Datenmengen und Datenpunkte geeignet.

Aktuell ist das so als Limit eingebaut. N sich macht es eher sinn dann auf eine richtige Datenbank umzusteigen.

Man könnte höchstens die Nummer konfigurierbar machen was aber zu anderen komischen Effekten führen kann.

**Comment by bahnuhr** [comment]
ja, habe eingestellt ..lite.
Was heißt:... muss jede DB-Anfrage sequenziell gemacht  ...
Was heißt ... richtige Datenbank....

Wenn ich in der Instanz mysql auswähle. Wäre das dann richtiger ?

**Comment by Apollon77** [comment]
sqlite ist eine Datenbank die lokal auf dem ioBroker Rechner "läuft" (wenn man das so nennen will) und alles in lokalen Dateien schreibt. sqlite kann immer nur eine Anfrage zu einem Zeitpunkt bearbeiten (also wenn eine Query läuft kann nicht parallel ein neuer Wert geschrieben werden. Auch das Schreiben eines Wertes und so dauert recht lang und so.
heisst wenn in kurzer Folge 100 INSERTs kommen dann wird einer nach dem anderen abgearbeitet was dann mehrere Sekunden dauert. Ist halt nicht für Massendaten gemacht.

MySQL - wenn du zB eine NAS hast oder so wo die DB drauf laufen kann - auf einem Raspi mit SD Karte eher nicht empfehlenswert - ist da viel besser
