### ISSUE TITLE
Download of data is not the configured custom time frame

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.sql#190]
When using the user interface of a datapoint to download the SQL history as a CSV file for later use with for example Excel the preview displays a limited amount of data which is confusing at first but not a dealbraker. What really got me off guard was that the download in the top right corner does not download the selected timeframe either. It is limited to 500 entries which is way to few for my use case.

**To Reproduce**  
1. Go to the history settings of a datapoint which has recorded at least 510 values
2. Click on the historical data tab
3. select a custom time frame which contains at least 510 values
4. click on download in the top right corner
5. download a file with exactly 500 values even though it should contain 510 values

**Expected behavior**  
I expected the file to contain the configured timeframe no matter the amount of data. Yes the download of large files may take a second or two but non the less it should behave that way.

**Versions:**  
 - Adapter version: 1.15.7
 - JS-Controller version: 3.3.15
 - Node version: v12.22.4
 - Operating system: Ubuntu

**Additional information**
The instance is connected to a mysql database

**Comment by Apollon77** [comment]
The fucntionalty is offered by Admin Adapter. Can you please create the issue there ... and als make sure to use Admin 5.1.x and no Admin4 !
