### ISSUE TITLE
Loggin of non activated datapoints

### ISSUE THREAD

**Issue by arturDUS** [ioBroker/ioBroker.sql#202]
I have several sensors (motion detector) attached via the DECONZ adapter to my system. And had activated the SQL-Logging for the presence state of those sensors. 

![image](https://user-images.githubusercontent.com/45556368/138550392-9762458e-4f90-439d-97a2-d24328c20f66.png)

Although I have turned the SQL-logging off for this datapoint:

![image](https://user-images.githubusercontent.com/45556368/138550446-9af9e8cd-aef3-4498-8a42-65df60f46de8.png)

there are still logging informations in the ioBroker logs which say that logging is disabled.
![image](https://user-images.githubusercontent.com/45556368/138550490-f0d14427-9e38-4aac-bbf8-63a2a743975b.png)

In my opineon the logging is not correct.

Thanks,
Artur

**Comment by arturDUS** [comment]
Will there be a fix for this?
I have so many wrong entries in my logging that the realy important information in the logging is sometimes not seen and additiaonally this blows up the stored log files. E.g. I have about 2800 of these log entries in the logfile!

**Comment by Apollon77** [comment]
Yes if someone finds ztime for this.

Why you do not simply adjust the loglevel to "warn" in the meantime? Then you do not see the "info" logs anymore

**Comment by Apollon77** [comment]
will e fixed in next version

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/54662/test-adapter-sql-2-0-0
