### ISSUE TITLE
Too many Connections (MariaDB10)

### ISSUE THREAD

**Issue by jh2k19** [ioBroker/ioBroker.sql#206]
Hallo Apollon77,

seit einiger Zeit kommt es bei uns immer zu Abstürzen der Datenbank. 
Die Fehlermeldung weist auf  too many connections hin.
Wir konnten das in soweit in den Logs der DB nachvollziehen.
Eine Erhöhung der max connections auf Seiten der DB hilft nicht wirklich, da auch diese bis Anschlag volllaufen.
Es scheint so, dass die Maximum concurrent connections im ioBroker.SQL-Adapter nicht greift.
Wird der Schalter Allow parallel requests gesetzt, kommt natürlich nur eine Verbindung zustande und die DB läuft durch.
Wir haben momentan im ioBroker ca. 200 Datenpunkte die Werte in die DB schreiben.
Könntest du dir das mal ansehen?

Gruß Jürgen

**Comment by 5G7K** [comment]
Ich hatte ähnliche Probleme.
Bei mir hat es geholfen zu setzen: max_connections        = 4096 
in folgenden Config Files:
sudo nano /etc/mysql/mariadb.conf.d/50-server.cnf
/etc/mysql/mariadb.cnf

vielleicht hilft das bei dir auch?
