### ISSUE TITLE
mySQL Fehlermeldungen & Timing

### ISSUE THREAD

**Issue by tp1de** [ioBroker/ioBroker.sql#214]
Der SQL Adapter (V 1.6.1) hat folgendes Verhalten (Adapter Javascript):

1. Wenn ich per Code Objekte anlege und direkt danach mit adapter.sendTo(db, "enableHistory", {id: id, options: .....
die SQL-Fortschreibung enable, dann 
2.a Wird in der mySQL-Datenbank in der datapoints-Tabelle noch kein Eintrag erzeugt. Dieser existiert erst nach dem ersten setState.
2.b wird direkt nach (1) ein adapter.sendTo(db,"storeState", data); ausgeführt, dann gibt es Fälle in denen scheinbar das enableHistory noch nicht beendet ist.

Konsequenz:
2.a bedeutet, dass mit SQL-Befehlen keine Daten abgefragt bzw. eingefügt werden können.
2.b ergibt z.T. Fehlermeldungen beim ersten Adapter-Start:
<html>
<body>

sql.0 | 2022-01-07 10:56:44.110 | warn | TypeError: Cannot read property 'ignoreZero' of undefined at pushValueIntoDB (E:\ioBroker\node_modules\iobroker.sql\main.js:1575:39) at storeState (E:\ioBroker\node_modules\iobroker.sql\main.js:2294:9) at processMessage (E:\ioBroker\node_modules\iobroker.sql\main.js:916:9) at Adapter.<anonymous> (E:\ioBroker\node_modules\iobroker.sql\main.js:219:34) at Adapter.emit (events.js:400:28) at change (E:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:5636:34) at Immediate._onImmediate (E:\ioBroker\node_modules\@iobroker\db-states-redis\lib\states\statesInRedisClient.js:232:37) at processImmediate (internal/timers.js:464:21)
-- | -- | -- | --
sql.0 | 2022-01-07 10:56:44.110 | warn | States system pmessage io.messagebox.system.adapter.sql.0 {"command":"storeState","message":{"id":"ems-esp.0.recordings.actualPower._Hours","state":{"ts":1641402000000,"val":7.1}},"from":"system.adapter.ems-esp.0","_id":49061692} Cannot read property 'ignoreZero' of undefined

</body>
</html>  

Verbesserungsvorschlag:

zu 1.: nach enableHistory direkt den dazugehörigen Eintrag in der datapoints-Tabelle erstellen - d.h. id vergeben
zu 2.: beim storeState eine Abfrage nach enableHistory - d.h. ob common.custom.sql Eintrag im Objekt vorhanden und falls nicht eine aussagefähige Warnmeldung oder den Eintrag automatisch anlegen.

*** Wenn zwischen enableHistory und storeState wenige msec verstreichen (anderer Code oder sleep) funktioniert es einwandfrei.

P.S.: aktuell habe ich den Fehler auch nur auf meiner Windows-Testumgebung (schneller Rechner und Test-Datenbank).

**Comment by Apollon77** [comment]
The topic is the following: This error happens when the datapoint is not known/enabled in the adapter. I can fix that .-.. but in fact the question to you: Please make sure that the enable is successfully executed (aka the callback is called!!!) before assuming that you can store data, else the data will not be stored at all!

also wie sieht dein code aus? Ich hoffe nciht

`
sendTo( for enable)
sendTo( for add data)
`

Because then both call will be send out in parallel and the second run into issues.!!

**Comment by tp1de** [comment]
Already fixed, but it took a while to find out what happened .... can't you send a better error message?

What about creating a datapoints entry as soon as sql enabled in object and not when 1st state written?

**Comment by Apollon77** [comment]
The next version will not throw such an error .. this was  bug that jappened in such "unexpected cases" ...
