### ISSUE TITLE
Der Befehl adapter.sendTo(db, "deleteAll", {id: field}); funktioniert nicht mit Influxdb 

### ISSUE THREAD

**Issue by tp1de** [ioBroker/ioBroker.sql#215]
Mit Influxdb (V1.8) funktioniert der Befehl `adapter.sendTo(db, "deleteAll", {id: field});` nicht. (mySQL OK).

Wird` await adapter.sendToAsync(db, "deleteAll", {id: field});` mit Influxdb aufgerufen, dann bleibt der Programmcode stehen.

**Comment by Apollon77** [comment]
EIn InfluxDB Issue im SQL Adapter? Das gehört hier nicht hin.

UND duplicate https://github.com/ioBroker/ioBroker.influxdb/issues/167
