### ISSUE TITLE
SQL Adapter zeichnet bei Neustart Datenpunkte nicht auf

### ISSUE THREAD

**Issue by heymkeyu** [ioBroker/ioBroker.sql#216]
Siehe auch https://forum.iobroker.net/topic/51089/sql-adapter-zeichnet-bei-neustart-datenpunkte-nicht-auf?_=1641575144773 

Beim Neustart des SQL-Adapters (über die Adapterinstanz oder durch Neustart des ioBroker Containers) wird das Protokollieren der meisten Datenpunkten nicht fortgesetzt. Nur bei wenigen Datenpunkten klappt das. 
Auswahl die funktioniert:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/oliver/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/oliver/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Datenpunkt
--
go-e.0.energy.phase1.power
go-e.0.energy.phase2.power
go-e.0.energy.phase3.power
hm-rega.0.1979
hm-rega.0.2335
hm-rega.0.2336
hm-rega.0.53035
hm-rega.0.64297
modbus.0.holdingRegisters.102837_Batterieleistung
modbus.0.holdingRegisters.102853_State_of   Energy SOE

</body>

</html>

Auswahl die nicht funktioniert:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/oliver/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/oliver/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Datenpunkt
--
0_userdata.0.var.internet.MByteS.downPercent
0_userdata.0.var.internet.MByteS.upPercent
hm-rpc.0.NEQ1648753.1.HUMIDITY
hm-rpc.0.NEQ1648753.1.TEMPERATURE
hm-rpc.0.NEQ1648753.1.WIND_SPEED
hm-rpc.0.REQ0935400.1.TEMPERATURE
hm-rpc.0.REQ0935400.2.TEMPERATURE
hm-rpc.0.REQ0935554.1.TEMPERATURE
hm-rpc.0.REQ0935554.2.TEMPERATURE
hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE
hm-rpc.1.0001D3C992A921.6.POWER
hm-rpc.1.0001D3C99C9E66.6.POWER
hm-rpc.1.0001D8A9933CE1.6.POWER
hm-rpc.1.0001D8A9933CE7.6.POWER
hm-rpc.1.000C9709A66C2B.1.ACTUAL_TEMPERATURE
javascript.0.Solar.Wechselrichter.ACTotalRealPower
javascript.0.Solar.Wechselrichter.Hausverbrauch
javascript.0.Solar.Wechselrichter.PVProduktionsLeistung
viessmannapi.0.651910.0.features.heating.circuits.0.sensors.temperature.supply.properties.value.value
vr200.0.Dusty.status.charge
vr200.0.Dusty.status.isCharging
vr200.0.Dusty.status.isDocked
vr200.0.Dusty.status.state
vw-connect.1.WVGZZZE2ZMP007203.status.batteryStatus.cruisingRangeElectric_km
vw-connect.1.WVGZZZE2ZMP007203.status.batteryStatus.currentSOC_pct
worx.0.20193019930200004504.mower.batteryState
worx.0.20193019930200004504.mower.batteryTemperature
worx.0.20193019930200004504.mower.batteryVoltage
worx.0.20193019930200004504.mower.error
worx.0.20193019930200004504.mower.mowTimeExtend
worx.0.20193019930200004504.mower.status
worx.0.20193019930200004504.mower.wifiQuality

</body>

</html>

Die Leistungswerte von Messschaltsteckdosen oder der errechneten Photovoltaik Leistungswerte ändern sich bei Nutzung eigentlich ständig und sollten auf jeden Fall aufgezeichnet werden. 

Bei den problematischen Werte erfolgt erst per Workaround nach Änderung von "trotzdem gleiche Werte aufzeichnen" eine weitere Protokollierung. 
Die Einstellungen der jeweiligen Datenpunkte unterscheiden sich meiner Ansicht nach nicht: 
![image](https://user-images.githubusercontent.com/48991539/148640001-91c58ccb-807b-449e-a26e-59e4ea680166.png)
(grün, links: hier wird das Protokollieren korrekt fortgesetzt; rot, rechts: hier wird das Protokollieren **nicht** korrekt fortgesetzt)

Ich kann den Unterschied zwischen den Datenpunkten nicht erkennen - daher kann ich keine Reproduktionsanleitung liefern und bräuchte hier Unterstützung nach was ich schauen soll um weiteres sinnvolles Input liefern zu können. 

Logeintrag eines Datenpunkts, bei dem keine Protokollierung erfolgt, obwohl protokolliert werden sollte: 
`States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2398,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2398,"user":"system.user.admin"}},"id":2553,"ack":false,"time":1641458666691},"_id":70724229}`

Erwartungshaltung wäre, dass die Protokollierung bei allen Datenpunkten nach dem Neustart der Addapterinstanz oder des Containers wiederaufgenommen wird.

Eine Protokollierung findet zwischen dem Neustart ohne manuelles Anstoßen tatsächlich nicht statt: 
![image](https://user-images.githubusercontent.com/48991539/148640258-c29043df-21a8-4343-9303-2e04b2218805.png)

![image](https://user-images.githubusercontent.com/48991539/148640291-416ba11c-69bf-42f5-ac11-0173b3b96287.png)

![image](https://user-images.githubusercontent.com/48991539/148640341-82bf2a74-66b3-452a-86cc-512f0d0ebc15.png)

![image](https://user-images.githubusercontent.com/48991539/148640382-9770f353-1e6c-41df-a083-bde39c860a5c.png)

![image](https://user-images.githubusercontent.com/48991539/148640417-c6d54a90-f52e-4960-97e6-69b286a2f219.png)

![image](https://user-images.githubusercontent.com/48991539/148640433-0291c75a-4f7c-41e7-82b5-b4c52fa6eb6a.png)

Bei den meisten Werten (nicht allen) ist der letzte aufgezeichnete Wert bevor die Aufzeichnung manuell durch den Workaround wieder gestartet werden kann ein NULL-Wert.

Info:

- PLATTFORM: LINUX
- BETRIEBSSYSTEM: LINUX
- ARCHITEKTUR: X64
- CPUS: 2
- GESCHWINDIGKEIT: 2396 MHZ
- MODELL: INTEL(R) CELERON(R) CPU J3355 @ 2.00GHZ
- RAM: 7.6 GB
- SYSTEM-BETRIEBSZEIT: 2 T. 23:57:35
- NODE.JS: V14.18.2
- NPM: 6.14.15
- DATENTRÄGERGRÖSS: 7242.9 GB
- FESTPLATTE FREI: 1571.6 GB
- ADAPTER-ANZAHL: 457
- BETRIEBSZEIT: 07:38:28
- AKTIVE INSTANZEN: 32
- PFAD: /OPT/IOBROKER/

Siehe auch https://forum.iobroker.net/topic/51089/sql-adapter-zeichnet-bei-neustart-datenpunkte-nicht-auf?_=1641575144773

**Comment by Apollon77** [comment]
Ok, trotzder vielen Infos (Danke dafür) ist das nicht so wirklich hilfreich.

Am besten bitte mal den sql Adapter im "Debug" Modus starten ... dann siehst Du sehr genau wenn neue Werte reinkommen und warum er sie (nicht) loggt. Kannst Du da mal schauen bzw posten bei einem solchen Datenpunkt?

Ebenso interessant: Welche Version von sql ist betroffen? Gabs ein Update bevor es aufhörte?

**Comment by heymkeyu** [comment]
Hi @Apollon77 - Danke für die schnelle Reaktion. 

Ich habe mal das hier mal exemplarisch rausgefischt, kann das Logging aber nicht wirklich deuten. 

Log Filter auf „hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE“:
```
 
sql.0	2022-01-06 09:44:41.844	silly	States user redis pmessage */hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE:{"val":24.2,"ack":true,"ts":1641458679590,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1641458679590}
 
sql.0	2022-01-06 09:44:27.370	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210149,"end":1641458610149,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2401,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210149,"end":1641458610149,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2401,"user":"system.user.admin"}},"id":2577,"ack":false,"time":1641458666715},"_id":70724253}
 
sql.0	2022-01-06 09:44:27.344	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210149,"end":1641458610149,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2400,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210149,"end":1641458610149,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2400,"user":"system.user.admin"}},"id":2569,"ack":false,"time":1641458666704},"_id":70724245}
 
sql.0	2022-01-06 09:44:27.309	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210148,"end":1641458610148,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2399,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210148,"end":1641458610148,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2399,"user":"system.user.admin"}},"id":2561,"ack":false,"time":1641458666701},"_id":70724237}
 
sql.0	2022-01-06 09:44:27.263	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2398,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2398,"user":"system.user.admin"}},"id":2553,"ack":false,"time":1641458666691},"_id":70724229}
 
sql.0	2022-01-06 09:44:27.209	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2397,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2397,"user":"system.user.admin"}},"id":2545,"ack":false,"time":1641458666685},"_id":70724221}
 
sql.0	2022-01-06 09:44:27.189	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2396,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210147,"end":1641458610147,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2396,"user":"system.user.admin"}},"id":2537,"ack":false,"time":1641458666679},"_id":70724213}
 
sql.0	2022-01-06 09:44:27.173	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210146,"end":1641458610146,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2395,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210146,"end":1641458610146,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2395,"user":"system.user.admin"}},"id":2529,"ack":false,"time":1641458666627},"_id":70724205}
 
sql.0	2022-01-06 09:44:27.160	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210146,"end":1641458610146,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2394,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210146,"end":1641458610146,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2394,"user":"system.user.admin"}},"id":2521,"ack":false,"time":1641458666625},"_id":70724197}
 
sql.0	2022-01-06 09:44:27.140	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210146,"end":1641458610146,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2393,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210146,"end":1641458610146,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2393,"user":"system.user.admin"}},"id":2513,"ack":false,"time":1641458666609},"_id":70724189}
 
sql.0	2022-01-06 09:44:27.127	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210145,"end":1641458610145,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2392,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210145,"end":1641458610145,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2392,"user":"system.user.admin"}},"id":2505,"ack":false,"time":1641458666587},"_id":70724181}
 
sql.0	2022-01-06 09:44:27.105	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210145,"end":1641458610145,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2391,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210145,"end":1641458610145,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2391,"user":"system.user.admin"}},"id":2497,"ack":false,"time":1641458666561},"_id":70724173}
 
sql.0	2022-01-06 09:44:27.051	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210145,"end":1641458610145,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2390,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210145,"end":1641458610145,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2390,"user":"system.user.admin"}},"id":2489,"ack":false,"time":1641458666560},"_id":70724165}
 
sql.0	2022-01-06 09:44:26.642	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210144,"end":1641458610144,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2389,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210144,"end":1641458610144,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2389,"user":"system.user.admin"}},"id":2481,"ack":false,"time":1641458666535},"_id":70724157}
 
sql.0	2022-01-06 09:44:26.571	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210144,"end":1641458610144,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2388,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210144,"end":1641458610144,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2388,"user":"system.user.admin"}},"id":2473,"ack":false,"time":1641458666485},"_id":70724149}
 
sql.0	2022-01-06 09:44:26.529	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210135,"end":1641458610135,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2387,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210135,"end":1641458610135,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2387,"user":"system.user.admin"}},"id":2465,"ack":false,"time":1641458666473},"_id":70724141}
 
sql.0	2022-01-06 09:44:26.492	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210104,"end":1641458610104,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2386,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210104,"end":1641458610104,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2386,"user":"system.user.admin"}},"id":2457,"ack":false,"time":1641458666446},"_id":70724133}
 
sql.0	2022-01-06 09:44:26.444	silly	States system redis pmessage io.messagebox.system.adapter.sql.0/io.messagebox.system.adapter.sql.0:{"command":"getHistory","message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210098,"end":1641458610098,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2385,"user":"system.user.admin"}},"from":"system.adapter.web.0","callback":{"message":{"id":"hm-rpc.0.REQ1182015.4.ACTUAL_TEMPERATURE","options":{"start":1641372210098,"end":1641458610098,"aggregate":"minmax","count":"300","instance":"sql.0","sessionId":2385,"user":"system.user.admin"}},"id":2449,"ack":false,"time":1641458666443},"_id":70724125}
```

![image](https://user-images.githubusercontent.com/48991539/148680100-60861738-779a-4d2c-95ef-824768abd374.png)

Kannst Du daran was erkennen?

Was hat mir das "Ack"(nowledge?) zu sagen? Ab dem letzten protokollierten Wert mit "Null" ist "Ack" false - das offenbar auch bei jedem weiteren geloggten Eintrag, der dann nicht protokolliert wird. 

Versionen:
ioBroker 3.3.21 (buanet Image v6.0.0/RAM: 7.6 GB NODE.JS: V14.18.2 NPM: 6.14.15) auf einem QNAP NAS in der Container Station mit MariaDB 5.5.68 mit SQL-Adapter v1.16.1

Ich kann Dir leider keine zeitliche Korrelation zu Updates nennen. QNAP NAS und ioBroker Adapter sind jeweils laufend auf dem neuesten Stand, beim ioBroker Container bin ich wegen des Aufwandes eher konservativ.

**Comment by Apollon77** [comment]
Also erst so bitte kein silly log. Debug reicht. Und bitte meeehhhhrrrrrr nicht nur ein paar Sekunden. Am besten lass mal so machen das du den Adapter neu startest und dann log vom
Start bis zum erste. Fall wo so ein state sich ändert es aber nicht geloggt wird. Und nur debug bitte!!

**Comment by Apollon77** [comment]
Ps: der eine null Eintrag ist der adapterstart oder Ende.

**Comment by heymkeyu** [comment]
OK, wird gemacht. Den Logschnipsel hatte ich einfach noch parat.

**Comment by heymkeyu** [comment]
Merkwürdig. 
SQL-Adapter stoppen und starten: Es erfolgt keinerlei pushValueIntoDB - auf keinem einzigen Datenpunkt. 
Fehlermeldung beim Starten des SQL-Adapters: 
<html>
<body>


2022-01-09 14:17:28.195 | error | Cannot find search "custom" in "system"
-- | -- | --



</body>
</html>

Was hat die Meldung zu bedeuten? 

Stoppe ich den ioBroker Container und starte ihn neu, bringen die "unproblematischen Datenpunkte" wieder ihre pushs, die problematischen jedoch nicht. Die tauchen zunächst überhaupt nicht auf, sondern erst wieder, wenn ich die Protokollierungseinstellungen ändere (Workaround nach Änderung von "trotzdem gleiche Werte aufzeichnen").

Irgendwie sinnfrei ein Log für Datenpunkte zu liefern, die im Log zur fraglichen Zeitspanne gar nicht auftauchen. 
Was tun?

**Comment by Apollon77** [comment]
> Cannot find search "custom" in "system"

Jetzt wird es interesanter. Welcher js-controller ist bei Dir im EInsatz? Er findet aktuell gar keine Datenpunkte initial deswegen.

Wenn es ein Controller 3.3.x ist dann bitte einmal `iobroekr setup first` and er Kommandozeile ausführen, dann neu versuchen. Falls ein älterer js-controller ist die Frage wie DU an diese Version gekommen bist weil Admin die Installation (ausser hast ein GitHub install gemacht) verhindern sollte

**Comment by heymkeyu** [comment]
Aus der Konsole: 
Existing earlier generated certificate is invalid (too old, validity longer then 345 days or keylength too short). Generating new Certificate!
object system.certificates updated
object _design/custom updated
object _design/system updated

Aus der Doku: 
```
iobroker setup
This command must be called if ioBroker was installed not with npm or windows installer (e.g. just copied from github and unpacked). It creates the default configuration file and prepares the data directories.

You can call this command with parameter “first” to be sure that nothing will be overwritten if the config yet exists.

Usage:
iobroker setup first – create configuration files if not yet created.
```

OK - ich hatte im Dezember ein neues Container Image gezogen und in Betrieb genommen. 
Hatte angenommen, dass der Container bereits eine Minimalkonfiguration mitbringt, dass eine initiale Konfig erzeugt werden muss, war mir nicht klar. 

Sieht auf den ersten Blick in den Diagrammen gut aus. 

Ganz herzlichen Dank, Ingo! 

Gruß
Oli

**Comment by Apollon77** [comment]
Super das es geholfen hat. Schreibst es auch im Forum als gelöst bitte? Also ich sags mal so, "ganz ohne" Konfig wäre gar nichts gegangen, du hast scheinbar eine konfig von nem js.controller <3.3 aber jetzt einen controller 3.3 oder so eine Kombi die eigentlich nicht vorkommen sollte ...naja who knows.

**Comment by heymkeyu** [comment]
Ich hatte den Lösungsweg dort vorhin bereits ebenfalls dokumentiert. 
Ein [gelöst] im Titel habe ich gerade nachgerüstet. 
Vielen Dank nochmals! 
Gruß
Oli 
P.S.: Bierchen kommt per PayPal. :-)

**Comment by Apollon77** [comment]
Danke sehr!
