### ISSUE TITLE
postgresql - option to use SSL/TLS is not available

### ISSUE THREAD

**Issue by stefanjay** [ioBroker/ioBroker.sql#222]
**Describe the bug**  
I can't add the option to use SSL/TLS in preferred mode `{disable, allow, prefer, required, verify-ca, verify-full}`. Due to the missing option the connection gets aborted with an error while the connection is getting tested:

`error: SSL required`

**To Reproduce**  
1. install adapter
2. deploy hardened postgresql14
3. define `ssl: on` in postgresql.conf

**Expected behavior**  
hardened connection between the iobroker + postgresql-db host(s)
- encypt DB isn't the option to actually encrypt the connection

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.16.1
 - JS-Controller version: 3.3.22
 - Node version: 14.19.0
 - Operating system: Debian11

**Additional context**  
this is a k8s deployment using the official repo `buanet/iobroker:6.0.0` image.

.. and btw, please do not log passwords in cleartext into the log...

please refer to the official docu of postgresql
https://www.postgresql.org/docs/current/libpq-ssl.html

**Comment by Apollon77** [comment]
Plese try GitHub version

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/54662/test-adapter-sql-2-0-0
