### ISSUE TITLE
names-Tabelle wird nicht automatisch erweitert

### ISSUE THREAD

**Issue by Buddinski88** [ioBroker/ioBroker.sql#227]
**Describe the bug**  
Ich habe neue Objekte zur Protokollierung aufgenommen. Innerhalb der Tabelle 'names' wird keine neue Zeile mit den Werten zu 'name', 'sname', 'lange' und 'raum' angelegt

**To Reproduce**  
1. Füge ein neues Objekt zur Protokollierung (ioBroker > Objekte > Einstellungen eines Objektes > SQL.0)
2. Prüfe in der ioBroker Tabelle ob eine neue Zeile innerhalb der Tabelle 'names' angelegt wurde
3. Verifiziere das generell Daten zu dem neuen Objekt geschrieben werden (MySQL Datenbank > ioBroker DB > datapoints)

**Expected behavior**  
Mit dem hinzufügen eines neues Objektes zur Protokollierung erwarte ich auch das die 'names' Tabelle automatisch um dessen Inhalte erweitert wird.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.16.1
 - JS-Controller version: 4.0.15 
 - Node version: 12.20.0
 - Operating system: Ubuntu 20.04.1 LTS

**Additional context**

**Comment by Apollon77** [comment]
Which table you mean? There is no "names" table that the adapter will generate ... https://github.com/ioBroker/ioBroker.sql/blob/master/lib/mysql.js

BTW: I remember that some extra script in forumadded something like this for convenient lookups ... might it be that you mean this? But then the is not managed by the adapter

**Comment by Buddinski88** [comment]
Your answer brought the ignited thought. The table names really doesn't come from the adapter. I searched my records again and came across the actual post in the [forum](https://forum.iobroker.net/post/135419).

```
var anz=0;
var data="";
var states = $('*').each(function(id,i) {
 
    if (getObject(id)) {
        anz=anz+1;
        var devname=getObject(id).common.name;
        var channel=getObject(id).common.name.split(":");
        var dp = getObject(id,"rooms");
        var raum=dp.enumNames;
        if (raum.length>0) {
        //    log(anz+"->"+id+":::::"+devname+"----"+channel[0]+">"+raum+"<");
        } else {
        //    log(anz+"->"+id+":::::"+devname+"----"+channel[0]+">"+"----------"+"<");
            raum="-"
        }
        data = data + '"'+id+'","'+channel[0]+'","'+devname+'","'+raum+'"'+String.fromCharCode(10);
 
    }
});
  //log(data);
  var fs = require('fs');
  fs.writeFile('/home/shares/allusers/namen.csv', data,'binary', function (error) {
    console.log(' file written-'+anz);
});
```
I am closing the bug due to a misunderstanding. Thank you!
