### ISSUE TITLE
Gleiche Log-Einträge

### ISSUE THREAD

**Issue by neunteufels** [ioBroker/ioBroker.sql#229]
Bei mir kommen ständig die gleichen Log-Einträge.
Ständig = ca. alle 12 Sekunden

info: sql.0 (20687) enabled logging of xxxx, Alias=true
info: sql.0 (20687) enabled logging of yyyy, Alias=true

Das passiert immer für genau diese zwei geloggten Datenpunkte.
Beide Datenpunkte sind Zahlen.

Deaktivieren und erneutes aktivieren hat keine Abhilfe geschaffen.

lg

**Comment by Apollon77** [comment]
In dem Fall werden Objekte geändert für die Logging aktiviert ist. Die Meldung bedeutet das ggf Aktualisierungen übernommen wurden. Wenn es stört dann Loglevel der Instanz auf "warn" setzen.
Wird generell in #202 optimiert
