### ISSUE TITLE
Error: ER_NO_DB_ERROR: No database selected

### ISSUE THREAD

**Issue by Ostseeskipper** [ioBroker/ioBroker.sql#236]
Adapterversion: v1.16.2

Scheinbar wird der Datenbankname der in den Adaptereinstellungen steht nicht in die "build in" Funktionen übertragen
Die in der readme stehenden Beispiele "query" für "getHistory"' bringen dadurch Fehler.

"query"
`sendTo('sql.0', 'query', 'SELECT id FROM datapoints WHERE name="system.adapter.admin.0.memRss"', `
bringt den Fehler Error: ER_NO_DB_ERROR: No database selected

mit 
`sendTo('sql.0', 'query', 'SELECT id FROM iobroker.datapoints WHERE name="system.adapter.admin.0.memRss"', `
dem Datenbankname **iobroker** aus der Adaptereinstellung werden Ergebnisse gezeigt

Leider kann man bei "getHistory" nicht irgendwo den Datenbanknamen angeben, das muss in der BuildIn Funktion des Adapters sein.

**Comment by Ostseeskipper** [comment]
Bitte BUG in Normales Issue ändern und die Beispiele prüfen.
siehe auch [https://forum.iobroker.net/topic/53843/sql-gethistory-abfrage/19?_=1648835495084](url)

**Comment by Apollon77** [comment]
Readme already contains this info after the custom query examples
