### ISSUE TITLE
Error: connect ETIMEDOUT sowie Too many connections

### ISSUE THREAD

**Issue by ChrMaass** [ioBroker/ioBroker.sql#248]
** English version below

Hallo zusammen, 

Seit dem Update auf 2.0.2 von Version 1.X.X habe ich ständig Probleme mit der Verbindung zu meiner MariaDB Datenbank (Version 10). Im Protokoll steht erst mehrfach "Error: Too many connections", und dann hundertfach "Error: connect ETIMEDOUT".

Bei den Einstellungen des Adapters habe ich schon verschiedene Einstellung bzgl. maximal gleichzeitiger Verbindungen versucht, aktuell steht diese bei 50. Wenn ich "Gleichzeitige Verbindung zulassen" deaktiviere, kommt der Adapter mit den Loggen nicht hinterher und hat zu viel in seiner Queue.
Die Datenbank habe ich auch schon gewechselt, die aktuelle befindet sich auf dem gleichen System. Ebenfalls habe ich dort die Anzahl der Verbindungen erfolgreich auf 500 konfiguriert. Sobald der Fehler auftritt steht die MySQL Variable "Max Used Connections" auch auf 501. Der Datenbankserver bedienst ausschließen Biobroker und hat keine zusätzlichen Datenbanken laufen.

iobroker läuft in Version 4.0.23
SQL in Version 2.0.2
Javascript in Version 5.7.0

Anbei eine Logdatei.

[SQL Error.log](https://github.com/ioBroker/ioBroker.sql/files/8762808/SQL.Error.log)

Gerne helfe ich mit weiteren Informationen um das Problem zu finden. Neuinstalliert habe ich die SQL Instanz bisher noch nicht.

+++++++++++

Hi together,

Since the update to 2.0.2 from version 1.X.X I have constant problems with the connection to my MariaDB database (version 10). In the log it shows multiple times "Error: Too many connections", and after that hundreds of times "Error: connect ETIMEDOUT".

In the settings of the adapter I have already tried different settings regarding the maximum number of simultaneous connections, currently it is set to 50. If I deactivate "Allow simultaneous connection", the adapter does not keep up with the logging and has too much in its queue.
I have also changed the database, the current one is on the same system. I have also successfully configured the number of connections to 500. As soon as the error occurs, the MySQL variable "Max Used Connections" is also set to 501. The database server is running Biobroker and has no additional databases.

iobroker runs in version 4.0.23
SQL in version 2.0.2
Javascript in version 5.7.0

Attached is a log file.

[SQL Error.log](https://github.com/ioBroker/ioBroker.sql/files/8762808/SQL.Error.log)

I'm happy to help with more information to find the problem. I have not reinstalled the SQL instance yet.

**Comment by Apollon77** [comment]
oooh ... I digged through code and foudn at least one place where  connection was not given back on error ... do you do user queries?

**Comment by Apollon77** [comment]
Let me fix that first and I add a debug log for connection counte ... maybe we see more then

**Comment by ChrMaass** [comment]
No, I do not currently use user queries. But what could be interesting is that I have a flot running in the background.

Okay, I'll gladly wait for your update. Thanks for your effort.

**Comment by Apollon77** [comment]
The basic "good" news is that at least the running test suite end with a "0 connections", so there is no leak in general ... now we need to find whats up

**Comment by ChrMaass** [comment]
Ich habe über admin nun „Aus eigener Quelle“ installieren gewählt und dort dann Github ausgewählt. Wie kann ich erkennen das es wirklich die aktuelle version ist? Es steht wieder 2.0.2

**Comment by ChrMaass** [comment]
There are many messages, but I can't find it.

If you just had a minute, you can ask to look on my screen with teamviewer ID 609 652 799.

**Comment by Apollon77** [comment]
bsically caused by https://github.com/intellinote/sql-client/issues/7

**Comment by ChrMaass** [comment]
Thanks @Apollon77 for the hotfix/workaround (installable per Github install/update)

**Comment by Apollon77** [comment]
2.1.0
