### ISSUE TITLE
Werte < 1.1.2000

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sql#249]
Hallo @Apollon77 

der "Fehler" besteht immer noch:

Daten mit Daten < 1.1.2000 (ts < 994481200000) werden nicht in zB Flot angezeigt
siehe https://forum.iobroker.net/topic/44738/sql-wert-per-script-speichern/48

Gibt es da schon eine Lösung ?

mfg
Dieter

**Comment by Apollon77** [comment]
Naja jetzt kann man weiter schauen. Ich vermute das flog auch noch so eine Konvertierung drin hat. 

Schritt 1 ist debug log vom sql Adapter um zu sehen was der tut und zurückgibt. Dann muss ich wohl mal in flot schauen.
