### ISSUE TITLE
There are more columns in the INSERT statement than values specified in the VALUES clause

### ISSUE THREAD

**Issue by hngfngzl** [ioBroker/ioBroker.sql#258]
Sehr geehrte Damen und Herren,

ich habe erst angefangen mich mit iobroker zu beschäftigen. 

Ich habe 3 Xiaomi Feuchtigkeitssensoren gekauft und eingerichtet um mich mit dem Thema vertraut zu machen. 
Die Sensoren sind gleich eingerichtet, aber leider ist das Ergebnis nicht gleich. 
Probleme bereitet vor allem die Fehlermeldung:

Cannot insert INSERT INTO iobroker.dbo.ts_counter (id, ts, val, ack, _from, q) VALUES(1, 1655783729700, 64);: RequestError: There are more columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement. (id: 2022-01-02 H)

Die Meldung kommt leider auch für andere Werte. Ein Vergleich mit den Werten die er korrekt verarbeiten kann konnte ich bislang nicht finden. Kann man sich deren Code anzeigen lassen um auf Fehlersuche zu gehen?

Grüße
Daniel Wolf

**Comment by Apollon77** [comment]
Hallo, welche Adapter-Version?

**Comment by hngfngzl** [comment]
Hallo,
Sql.0 Version 1.16.2
Admin.0 V5.3.8
Ble.0 v0.12.0
Soweit ich sagen kann aktuell – da ja auch erst recht frisch installiert.

Von: Ingo Fischer ***@***.***>
Gesendet: Dienstag, 21. Juni 2022 11:48
An: ioBroker/ioBroker.sql ***@***.***>
Cc: Daniel Wolf ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.sql] There are more columns in the INSERT statement than values specified in the VALUES clause (Issue #258)


Hallo, welche Adapter-Version?

**Comment by Apollon77** [comment]
Im beta Repository ist eine 2.x von sql ... Bitte die mal versuchen. Code-Seitig sollte das dort gefixt sein.

Installierbar via Admin - Adapter- Expertenmodus aksitiveren .Custom install Button, dann dort "von NPM" Tab und dort sql Adapter wählen.
