### ISSUE TITLE
ab V2 Binärwerte werden immer als "1" geloggt

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.sql#259]
Hallo Entwickler,

mit Umstellung von der V1.6.2 auf die V2 am 12.05. werden Binärwerte, die zur Aufzeichnung parametriert sind, als "1" geloggt, auch wenn sie "0" sind. Aktuell habe ich die V2.1.7 laufen.

Wenn der Adapter neu gestartet wird, z.B. manuell oder durch Config-Änderung, wird der Binärwert zunächst richtig aufgezeichnet, bis die Stunde um ist, die ich parametriert habe, um auch gleiche Werte aufzuzeichnen, dann steht bei "0" im Objekt wieder "1" im Chart (Flot). 

Analogwerte (z.B. Sollwert Raum), die sich seit einigen Tagen nicht geändert haben, werden nicht mehr angezeigt (kein Eintrag in der DB?), erst wenn man im Flot Chart zurück zu einem entsprechend zurückliegenden Tag zoomt/ scrollt wird der Wert wieder angezeigt. Auch hier ist eingestellt, dass nur Änderungen aufgezeichnet, aber trotzdem stündlich gleiche Werte geloggt werden. Debounce und Block Time steht für die Datenpunkte (401 Stck) auf jeweils 100ms.

Ich bin mir nicht sicher, ob ich das Verhalten schon 100% identifiziert habe. Was kann ich tun, um dem Phänomen auf die Spur zu kommen?

**Comment by fu-zhou** [comment]
Ich sehe gerade, dass der Effekt schon am 12.05. begonnen hat, ich habe leider kein VM Backup mehr von dem Zeitraum...

**Comment by Apollon77** [comment]
Na dann ein Debug log bitte.

1.) Für den genannten Datenountk in dessen History-Settings  das erweitere Debug aktivieren
2.) Loglevel der Instanz auf Debug

Dann warten bis mal wieder so ein wert geloggt wird (amm besten einmal was was in 0 und auch was was in 1 enden sollte) und Log zeigen.

Bitte ebenso screenshot der Settings des Datenpunkts hinzufügen

**Comment by fu-zhou** [comment]
is in Arbeit...

**Comment by fu-zhou** [comment]
Auszug aus dem Log von gerade eben:
`<html>
<body>


sql.0 | 2022-07-08 09:38:07.293 | info | Do not store value "NULL" for lg-ess-home.0.installer.setting.batt.soh_1 because no number
-- | -- | -- | --
sql.0 | 2022-07-08 09:38:07.293 | info | Do not store value "NULL" for s7.0.DBs.DB23.OG_SZ_HZG_T_SW_aktiv because no number
sql.0 | 2022-07-08 09:38:07.293 | info | Do not store value "NULL" for s7.0.DBs.DB23.OG_KB_HZG_T_SW_aktiv because no number
sql.0 | 2022-07-08 09:38:07.290 | info | Do not store value "NULL" for s7.0.DBs.DB23.OG_K2_HZG_T_SW_aktiv because no number
sql.0 | 2022-07-08 09:38:07.284 | info | Do not store value "NULL" for s7.0.DBs.DB23.OG_K1_HZG_T_SW_aktiv because no number
sql.0 | 2022-07-08 09:38:07.280 | info | Do not store value "NULL" for s7.0.DBs.DB23.OG_FL_HZG_T_SW_aktiv because no number
sql.0 | 2022-07-08 09:38:07.277 | info | Do not store value "NULL" for s7.0.DBs.DB23.OG_EB_HZG_T_SW_aktiv because no number
sql.0 | 2022-07-08 09:38:07.276 | info | Do not store value "NULL" for s7.0.DBs.DB23.OG_AN_HZG_T_SW_aktiv because no number


</body>
</html>`

Die Werte der Objekte sind "15", also nicht "0" oder "NULL", da läuft irgendwas schief. In Konsequenz werden sie auch nicht in die Datenbank geschrieben und Flot bleibt leer... Abgesehen davon habe ich ja nicht parametriert, dass Null-Werte nicht geschrieben werden sollen

**Comment by fu-zhou** [comment]
seltsamerweise funktioniert das Logging manchmal richtig bei einem Neustart des SQL Adapters und in den Objekten stehen ja die richtigen Werte drin, da steht ja nicht zwischen drin mal "0" anstatt "15"...

**Comment by fu-zhou** [comment]
Habe den SQL Adapter um 12:08 neu gestartet - jetzt zeichnet er wieder korrekt auf...
![Zwischenablage02](https://user-images.githubusercontent.com/11984960/177987058-46c13e5e-1719-4c60-9cb9-a075646487db.jpg)
.

**Comment by Apollon77** [comment]
Im Log oben Sieht man schon da sich die Werte scheinbar eher selten ändern ... damit kommt es immer darauf an ob der letzte Wert ein "sinnvoller "war oder ein blödsinniger ...je nachdem Loggt er danach sinnvoll oder Blödsinn.

Also as said-> s7 Adpater!!
