### ISSUE TITLE
UNION ALL instead of UNION in mysql getHistory?

### ISSUE THREAD

**Issue by riversource** [ioBroker/ioBroker.sql#264]
After playing around with the SQL statements for the getHistory functionality, it turned out, that using UNION ALL is much faster than using UNION. From my point of view it should make no big difference, since the combination of id and timestamp should be unique.

Is there a reason for using "UNION"?

`SELECT ts, val FROM `iobroker`.ts_number WHERE `iobroker`.ts_number.id=36 AND `iobroker`.ts_number.ts < 1659945600000 AND `iobroker`.ts_number.ts >= 1659859200000 UNION **ALL** ( SELECT ts, val FROM `iobroker`.ts_number WHERE `iobroker`.ts_number.id=36 AND `iobroker`.ts_number.ts < 1659859200000 ORDER BY `iobroker`.ts_number.ts DESC LIMIT 1) UNION **ALL** ( SELECT ts, val FROM `iobroker`.ts_number WHERE `iobroker`.ts_number.id=36 AND `iobroker`.ts_number.ts >= 1659945600000 ORDER BY `iobroker`.ts_number.ts ASC LIMIT 1) ORDER BY ts ASC;`

**Comment by Apollon77** [comment]
Hi, thank you for these infos. Honestly ... I'm no SQL expert, so thsi is indeed a good question ... I need to read into DB documentation to have an opinion :-)
