### ISSUE TITLE
SendTo getEnabledDPs findet keine Alias.0

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.sql#271]
Mit der Funktion getEnabledDPs werden keine Objekte gefunden die im Alias.0 sind.

**To Reproduce**  
1. sql.0 für einen Datenpunkt außerhalb erstelle
2. sql.0 für einen Datenpunkt in Alias.0 erstellen
3. folgendes Script ausführen:

`let enabledDPs = await sendToAsync2('sql.0', 'getEnabledDPs', {})
console.warn(enabledDPs)
async function sendToAsync2(instanz, message, parameters) {
    return new Promise((resolve, reject) => {
        sendTo(instanz, message, parameters, function (result) {
            if (!result.error) {
                resolve(result);
            } else {
                //console.error(result.error);
                reject(result.error);
            }
        });
    });
}`

5. Im Log sieht man, dass nur die Datenpunkt außerhalb alias.0 gefunden werden:

`{'0_userdata.0.abc':{'enabled':true,'storageType':false,'counter':false,'aliasId':'','debounceTime':0,'blockTime':0,'changesOnly':false,'changesRelogInterval':0,'changesMinDelta':0,'ignoreBelowNumber':'','disableSkippedValueLogging':false,'retention':31536000,'customRetentionDuration':365,'maxLength':10,'enableDebugLogs':false,'debounce':0,'ignoreZero':false,'round':10000}}
`

**Expected behavior**  
alias.0 sollte gleich behandelt werden.

**Versions:**  
 - Adapter version: 2.1.8
 - JS-Controller version: 4.0.23
 - Node version: 15.17.1
 - Operating system: Linux-Docker

**Additional context**

**Comment by Omega236** [comment]
Es liegt nicht am Alias.0 aber ich habe noch nicht rausgefunden, warum manche Datenpunkte in alias gefunden werden und andere nicht trotz gleicher Configuration

**Comment by Apollon77** [comment]
The adapter logs the enablement on startup ... if it is not listend then it is unknown. if it is listed there it is known.

How does they that can not be found look like fromman object perspective?

**Comment by Omega236** [comment]
Ich habe mitlerweile rausgefunden woran es lag.

ich habe folgende Datenpunkte:
alias.0.Geräte.Arbeitsplatz.Leistung  (sql.0 ohne besonderheiten aktiviert)

und den Datenpunkt der zu dem alias verlinkt ist:
sonoff.0.Arbeitsplatz.ENERGY_Power (sql.0 aktiviert mit alias "alias.0.Geräte.Arbeitsplatz.Leistung")

Wenn ich nun getEnabledDPs aufrufe, wird nur der Datenpunkt "sonoff.0.Arbeitsplatz.ENERGY_Power" zurückgeliefert. Obwohl der "alias.0.Geräte.Arbeitsplatz.Leistung" auch sql.0 aktiviert hat.

wird vermutlich an der internen Arbeitsweise liegen aber trotzdem nicht ganz logisch.

**Comment by Apollon77** [comment]
>  sonoff.0.Arbeitsplatz.ENERGY_Power (sql.0 aktiviert mit alias "alias.0.Geräte.Arbeitsplatz.Leistung")

was genau meinst du "mit alias" ? hast du bei dem Datenpunkt in der Dstenpunkt-Konfig beim Feld "alias" die gleiche ID wie die des Alias reingeschrieben? Das Feld alias in der sql Definition sagt auf welchen Datenpunkt ID zu loggen ist. Der Fall das zwei Datenpunkte auf das gleiche Ziel loggen ist quasi nicht supportet. Bitte das "Alias" Feature von sql nicht verwechseln mit den "Aliases" von ioBroker! Heisst gleich ist aber was anderes
