### ISSUE TITLE
Nach Update auf 2.2.0 Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.sql#272]
Habe gestern Abend die neue Beta vom o. g. Adapter installiert 2.2.0. Danach liefer alles wie erwartet.

Heute Nacht stand das wöchentliche Backup an. In der kurzen Zeit vom Backup hatte ich im Log von ioBroker schon immer (also mit allen Versionen davor) kurz die Meldung'Error: connect ETIMEDOUT'

Leider bleibt die Meldung auch nach dem Backup und der Adapter bekommt keine Verbindung mehr zur Datenbank. Dafür wird das Log mit o. g. Meldung alle paar Minuten geflutet.

Hat jemand eine Idee wo das Problem sein kann? Oder was ich prüfen kann. Wie gesagt einzige Änderung Adapterupdate.

iobroker läuft auf einer Synolgy im Docker. Über die Pakete ist die Maria DB installiert. Mit dem installierten Paket phpmyadmin habe ich auch Zugriff auf die DB.

Im Adapter ist als Server: nas3.fritz.box eingetragen.
Port3307

Hat sich aber alles nicht verändert und lief mit den Einstellungen eigentlich.

Adapter auf Debug bringt auch keine andere Meldung ausser Timeout

Testweise neue Datenbank erstellt. Beim Adapter Verbindung testen bekomme ich ebenfalls Meldung "Zeitüberschreitung".

`

sql.0
--
  | 2022-10-04 18:27:24.347	debug	Borrow connection from pool: 1 now
  |  
  | sql.0
  | 2022-10-04 18:26:54.346	error	Error: connect ETIMEDOUT
  |  
  | sql.0
  | 2022-10-04 18:26:44.342	debug	Borrow connection from pool: 1 now
  |  
  | sql.0
  | 2022-10-04 18:26:14.340	error	Error: connect ETIMEDOUT
  |  
  | sql.0
  | 2022-10-04 18:26:04.329	debug	Borrow connection from pool: 1 now
  |  
  | sql.0
  | 2022-10-04 18:26:04.169	info	starting. Version 2.1.8 in /opt/iobroker/node_modules/iobroker.sql, node: v14.19.1, js-controller: 4.0.23
  |  
  | sql.0
  | 2022-10-04 18:26:03.780	debug	Plugin sentry Initialize Plugin (enabled=true)
  |  
  | sql.0
  | 2022-10-04 18:26:03.511	debug	States connected to redis: 127.0.0.1:9000
  |  
  | sql.0
  | 2022-10-04 18:26:03.412	debug	States create User PubSub Client
  |  
  | sql.0
  | 2022-10-04 18:26:03.411	debug	States create System PubSub Client
  |  
  | sql.0
  | 2022-10-04 18:26:03.377	debug	Redis States: Use Redis connection: 127.0.0.1:9000
  |  
  | sql.0
  | 2022-10-04 18:26:03.325	debug	Objects connected to redis: 127.0.0.1:9001
  |  
  | sql.0
  | 2022-10-04 18:26:03.317	debug	Objects client initialize lua scripts
  |  
  | sql.0
  | 2022-10-04 18:26:03.213	debug	Objects create User PubSub Client
  |  
  | sql.0
  | 2022-10-04 18:26:03.211	debug	Objects create System PubSub Client
  |  
  | sql.0
  | 2022-10-04 18:26:03.209	debug	Objects client ready ... initialize now
  |  
  | sql.0
  | 2022-10-04 18:26:03.139	debug	Redis Objects: Use Redis connection: 127.0.0.1:9001
  | host.iobroker_V61
  | 2022-10-04 18:26:02.052	info	instance system.adapter.sql.0 started with pid 8676
  | host.iobroker_V61
  | 2022-10-04 18:26:01.590	info	"system.adapter.sql.0" enabled

`

Ja mein System ist nicht aktuell :-) Node: v14.19.1 aber sollte ja trotzdem laufen.

**Comment by Apollon77** [comment]
Welche Adapterverison war denn vorher drauf wo das Problem nicht bestand?

**Comment by Baenker** [comment]
2.1.8.

**Comment by Apollon77** [comment]
Hm ... MSSQL and PostGres were updated on library side, but no change on MySQL driver between 2.1.8 and 2.2.0 ... no idea honestly. Can you please try if the issue appears again?

**Comment by Apollon77** [comment]
And please verify that the DB is really reachable on your NAS, mmaybe restart it ... it seems that the DB do not react on a connect try

**Comment by Baenker** [comment]
Gerade nochmal probiert. Gleicher Fehler. Neustart NAS und ioBroker habe ich gestern schon gemacht.

Mit phpmyadmi habe ich Zugriff auf die DB. Wie kann ich es anderweitig testen?

**Comment by Apollon77** [comment]
mal vom iobroker rechner mit nem mysql client oder telnet auf den port versuchen?  Ist ggf die IP vopm iobroker host wegen zuviele requests irgendwie von der DB gesperrt worden? (Ich stocher im dunkeln). Mal den iobroker host restartet?

**Comment by Baenker** [comment]
Achso vergessen der Container läuft im Hostmodus (schon immer) So das man auch keine Probleme hat mit Netzwerkverbindungen oder so

**Comment by Apollon77** [comment]
Das mit "borrow" ist schon ok, das ist eine connection instanz. Das er immer wieder neu versucht zu verbinden siehst Du ja daran das sich die Fehlermeldung geändert hat als de DB weg war. Was im Docker-Container verfügbar ist kann ich nicht sagen.

Der Standard connect Timeout sind 10s ... ich habe keine AHhnung ob das vllt ein Problem ist das das zu wenig ist (aber auch dann würde des der NAS bzw der DB nicht so gut gehen denke ich.
Versuche gern es mal hochzusetzen.

Editiere /opt/iobroker/node_modules/iobroker.sql/main.js an der Stelle https://github.com/ioBroker/ioBroker.sql/blob/master/main.js#L463 und füge eine Zeile mit 

```
connectTimeout = 30000,
```

ein ... (wären dann 30s).

Bringt das was?
Sagen die Logs der DB irgendwas?

**Comment by Baenker** [comment]
ich habe versucht das timeout hochzusetzen bin aber gnadenlos gescheitert weil anscheinend kein Editor im bauet docker installiert ist. Ist aber auch egal.

Ich habe mal versucht in phpmyadmin eine neue Tabelle zu erstellen und wollte dann die mit iobroker verbinden (meine Vermutung war die evtl die alte Tabelle einfach zu voll bzw zu groß ist). Dazu habe ich erstmal den Adapter gestartet und bin dann auf Einstellungen und habe dort meine bestehende Datenbank gegen die test-DB getauscht und dann auf Verbindung testen. Ergebnis ok. Danach habe ich wieder die alte Tabelle eingetragen und es erneut versucht auch diesmal kam ein ok beim test.

Mit anderen Worten es läuft wieder. Soweit so gut. Hast Du evtl eine Idee wieso es nun wieder geht? Ich habe ja eigentlich nichts verändert. Eigentlich kann es dann doch  nur sein das die Datenbank den User abgelehnt hat!? Und nach einer Zeit die Sperre aufhebt? Ich habe leider keine Ahnung wie ich mir Protokolle von der Maria DB angucken kann. Dort müsste man ja eigentlich dann auch sehen wo das Problem war.

**Comment by Apollon77** [comment]
naja das bringt mich zu der Frage was ggf im Logfile der DB steht? Das muss ja irgendwo auf der NAS sein :-)

**Comment by Baenker** [comment]
ich mache hier mach zu da es ja durch wundersame Selbstheilung plötzlich wieder funktioniert hat. Keine Ahnung wo das Problem damals lag.
