### ISSUE TITLE
Adapter SQL (Mysql) Instance Version 1.4.2

### ISSUE THREAD

**Issue by fjjat** [ioBroker/ioBroker.sql#28]
Beim Konfigurieren der sql.0 Instanz habe ich alle Felder (Host, Port,Datenbank, User und Passwort) ausgefüllt, dies führt zu folgender Fehlermeldung und vielen Einträgen im LOG:

 error   getaddrinfo ENOTFOUND localhost:3306 localhost:3306:3306

Nachdem ich den Port gelöscht und leer gelassen habe funktioniert die Instanz einwandfrei.

Prüfung der Eingabefelder oder Zusammenfügen des DSN bei Standartport fehlerhaft ? 

Synology DS214play Pakete: Nodejs v4, MariaDB

**Comment by Apollon77** [comment]
Bitte SQL-Version vom Github testen
