### ISSUE TITLE
keine Daten in DB

### ISSUE THREAD

**Issue by frankhirsch** [ioBroker/ioBroker.sql#29]
Ich habe den Adapter installiert, konfiguriert und gestartet - die Tabellen in der Datenbank wurden auch abgelegt, allerdings werden keine Daten geloggt. Habe ich noch etwas übersehen? 

PS: SQL History 1.4.5 wurde auf iobroker nach meinen Homematic Adaptern installiert..

`2017-02-25 19:36:43.588  - info: host.storage instance system.adapter.sql.0 started with pid 315                                        
2017-02-25 19:36:44.891  - info: sql.0 starting. Version 1.4.5 in /opt/iobroker/node_modules/iobroker.sql, node: v4.7.3                 
2017-02-25 19:36:45.117  - info: sql.0 Connected to mysql `

**Comment by Apollon77** [comment]
Du musst jetzt unter "Objekte" noch die einzelnen gewünschten Objekte aktivieren. Da ist ganz rechts ein Zahnrad. Klick da mal draus.

Massenaktionen gehen auch - da oist dann ein Zahnrad oben in der Navigation rechts

**Comment by frankhirsch** [comment]
Cool, danke - hatte ich wohl übersehen ;-)
