### ISSUE TITLE
alte Daten werden nicht gelöscht !

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sql#293]
In der Anleitung steht:
![image](https://user-images.githubusercontent.com/25694404/216814388-1a49ef5b-cbd7-4349-9353-5cdad9c648a9.png)

Dies funktioniert aber nicht.
vgl. iob.forum
https://forum.iobroker.net/topic/62659/sql-aufbewahrungsdauer?_=1675587697216

mfg
Dieter

**Comment by Apollon77** [comment]
First of all the "deleting" is not done "exatly in time" but maximum every 6 hours after a change because the query over all data might be expensive.
So:
1.) Deleting is only checks when new data are written. Not changing states might not get deleted right now - or only afetr an adapter restart +6h
2.) delayed 6h

Ideally turn on Debug log then we would need to check the logs

**Comment by bahnuhr** [comment]
Wie im Forum geschrieben habe ich die sql gelöscht.

**Comment by bahnuhr** [comment]
Habe die alte wieder eingespielt und am Anfang des nächsten Tages waren die alten Daten weg. Zumindest in flot nicht mehr sichtbar.
Aber:
Dies hat aber nicht zu Verringerung der Dateigröße geführt !
Weiterhin 1,1 GB.

Was bedeutet dies nun:
Im flot werden die Daten nicht mehr angezeigt.
Dies hat aber nicht wirklich zur Dateigrößenreduzierung geführt.

Ist also nicht unbedingt der sinnvolle Weg.
Wenn die Daten gelöscht sind, dann muss ! dies auch zur Reduzierung der Dateigröße führen.
Ansonsten hat das ganze keinen Sinn.

Noch jemand eine Idee ?

**Comment by Apollon77** [comment]
Naja laaangsam :-)) ... Datenbanken verwalten Ihre Speicherbereiche teilweise sehr dynamisch. Einige bleiben auf einer mal erreichten größe auch wenn Daten gelöscht werden - es wird dann aber dieser Speicherplatz "zuerst wieder beschrieben" - Sie werden also nicht mehr so schnell größer.
Einige Datenbanken komprimieren das beim Beenden oder beim Starten ... oder es gibt spezielle befehle dafür. 

Da müsstest Du jetzt genau recherchieren wie Sich "genau deine DB" da verhält. Dazu kann aber der Adapter nichts.

Beispiel zB https://dba.stackexchange.com/questions/310566/how-to-free-up-hard-drive-space-after-deleting-millions-upon-millions-of-records ...
