### ISSUE TITLE
Zeitstempel umwandeln

### ISSUE THREAD

**Issue by 09Dragon90** [ioBroker/ioBroker.sql#299]
Hallo,
ich versuche den Zeitstempel in der Datenbank für Grafana wieder in ein Datumsformat zu bekommen.
Aber irgendwas mache ich falsch.
Kann mir hier jemanden helfen?

Hier ist mein Code.

`SELECT FROM_UNIXTIME(ts, '%Y-%d-%m %h:%i:%s')AS TIME, val 
FROM iobroker.ts_number
WHERE (id = 13 AND val <> 'null')
ORDER BY ts 
`
![Screenshot 2023-03-29 193329](https://user-images.githubusercontent.com/49090343/228620948-9df41879-974e-4d39-8b66-8978db1121c9.png)

**Comment by Apollon77** [comment]
Ich glaube solche Fragen sind im Forum besser aufgehoben als hier in GitHub.
