### ISSUE TITLE
Request history data from external webpage

### ISSUE THREAD

**Issue by StephanBeutel** [ioBroker/ioBroker.sql#30]
Hi,

don't know how to directly send an email.

Is there a way to get the data from Jacascript on an external webpage?
Here's only a description how to access from Javascript adapter.

**Comment by Apollon77** [comment]
You want to publish results from JS /SQL to a webpage or what exactly you try to do?
In general if it is not a bug try to ask your question in http://forum.iobroker.net first and try to get support there for such things.
