### ISSUE TITLE
sqlite3 not working due to missing sql package

### ISSUE THREAD

**Issue by daniel-2k** [ioBroker/ioBroker.sql#306]
I updated the iobroker.sql adapter (to latest 2.2.0) and after that, the adapter does not start.
I get an error in the log

`SQL package "SQLite3Client" is not installed.`

I checked the installation of node.js "sql-client". The "sqlite3" package is installed and up to date.

What is missing here to start the adapter?

My environment is a raspberry pi.
Node v16

**Comment by Apollon77** [comment]
If this comes then most likely the native build of sqlite3 failed somehow. An install log would help.

YOu can try to do "npm rebuild" or "nom install" in the sqlite3 directory

**Comment by daniel-2k** [comment]
npm rebuild in sqlite3 directory worked, but first after upgrading my python3 to >= 3.6 (3.8).
Otherwise rebuild failed.
