### ISSUE TITLE
Ошибки при использовании удаленного сервера баз данных

### ISSUE THREAD

**Issue by badenbaden** [ioBroker/ioBroker.sql#31]
При попытке подключения к удаленной базе данных MySQL выводятся следующие ошибки:

sql.0	2017-04-19 11:29:12.061	error	Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'badaev_555'@'%' (using password: YES)
sql.0	2017-04-19 11:29:12.059	error	CREATE DATABASE `badaev_555` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

Хочет создать базу, но ему не разрешают. Да и зачем, если она уже есть и ее явно указали в настройках. Понятно, что это удобно для локального сервера MySql, но при удаленном - он не создает таблицы, зацикливается на создании базы.

Решил проблему закоментировав строку: 

"CREATE DATABASE `" + dbname + "` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;",

в /opt/iobroker/node_modules/iobroker.sql/lib/mysql.js.

Хорошо бы ввести проверку на наличие такой базы (проверил, если нет, то создать, если есть, то продолжить создавать таблицы) или в настройках галку, которая будет отключать создание базы.

**Comment by GermanBluefox** [comment]
**The adapter is maintained by non-russian person, so here is google translation:**
If you try to connect to a remote MySQL database, the following errors are displayed:

sql.0	2017-04-19 11:29:12.061	error	Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'badaev_555'@'%' (using password: YES)
sql.0	2017-04-19 11:29:12.059	error	CREATE DATABASE badaev_555 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

He wants to create a base, but he is not allowed to. And why, if it already exists and it was clearly indicated in the settings. It is clear that this is convenient for the local MySql server, but when it is remote it does not create a table, it fixes on creating the database.

Solved the problem by commenting on the line:
"CREATE DATABASE " + dbname + " DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;",

in /opt/iobroker/node_modules/iobroker.sql/lib/mysql.js.

It would be nice to enter a check for the presence of such a database (checked, if not, then create, if there is, then continue to create the table) or in the settings daw, which will disable the creation of the database.

**Comment by Apollon77** [comment]
Hi, could you test if

"CREATE DATABASE IF NOT EXISTS " + dbname + " DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"

works to prevent the error? Or will the following create tebales throw then errors too?

**Comment by badenbaden** [comment]
sql.0	2017-04-19 12:31:35.504	error	Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'badaev_555'@'%' (using password: YES)
sql.0	2017-04-19 12:31:35.502	error	CREATE DATABASE IF NOT EXISTS badaev_555 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

**Comment by Apollon77** [comment]
Is the problem still existing? Why it is an Access delined? Or do the user not have Create DB rights?
