### ISSUE TITLE
Warn Meldung : getOneCachedData: got null states 1 times for javascript.0.Geräte.Wemos....

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.sql#311]
vgl.
https://forum.iobroker.net/topic/66349/sql-warn-meldung

Bekomme warn Meldungen im log:
sql.0 | 2023-06-22 20:02:57.188 | warn | getOneCachedData: got null states 1 times for javascript.0.Geräte.Wemos.Wemos-Buero.BME280_Luftfeuchtigkeit
sql.0 | 2023-06-22 20:02:57.186 | warn | getOneCachedData: got null states 1 times for javascript.0.Geräte.Wemos.Wemos-Buero.CO2

Wenn die DP angelegt sind und sql aktiviert kommen keine warn Meldungen.
Lösche ich die DP (weil diese nicht mehr benötigt werden) erhalte ich weiterhin diese Meldungen.

Wie bekomme ich diese Meldungen weg ?

**Comment by Apollon77** [comment]
> Wie bekomme ich diese Meldungen weg ?

In jedem Fall durch einen Adapterrestart ... Muss mal schauen ob da beim Löschen von Objekten bvllt was nicht korrekt behandelt wird.

**Comment by bahnuhr** [comment]
Adapterrestart bringt nix. hab ich schon versucht.

Hab aber auch die Lösung:
Es lag an einem flot, das noch auf diese DP zugreifen wollte.
flot geändert und die warn waren weg.
mfg
Dieter
