### ISSUE TITLE
Error Massage since backup

### ISSUE THREAD

**Issue by mcbirne** [ioBroker/ioBroker.sql#328]
Since restoring a backup, I can't get the SQL Adapter to connect to my MariaDB. 
![image](https://github.com/ioBroker/ioBroker.sql/assets/38691204/672b1349-c981-4cd8-b19b-dfb2e52af7ba)
The setting seams to be correct.
The error massage is
![image](https://github.com/ioBroker/ioBroker.sql/assets/38691204/990e98be-1698-4dee-a85d-b79582eeb8d0)
The SQL Adapter Version is 3.0.0

**Comment by mcbirne** [comment]
the logfile:
![image](https://github.com/ioBroker/ioBroker.sql/assets/38691204/6433a8d9-b1df-4452-b459-41c5ed2f060b)

**Comment by Apollon77** [comment]
Is the DB process running? That error says that no connection is allowed to that port
