### ISSUE TITLE
DB in Azure

### ISSUE THREAD

**Issue by pioschek** [ioBroker/ioBroker.sql#33]
Hi,

can ioBroker.sql be used for databases in Azure? I got following message, when I start the corresponding instance:
"CREATE TABLE myTableName.dbo.sources (id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1), name varchar(255));"

The connection test failed too. Maybe a firewall issue? Although the ports should be "unlocked", on Azure and on our side.

I am new in ioBroker etc. 

So, does anyone have any hints? 

config:
DB Type: MS-SQL
Database name: myDB
Host: ourserver.database.windows.net
Port: 1433
User: ourUser@ourServer
PW: :)
Encrpyt: Yes

When I click on "Reset DB", the following message appears:
"RequestError: Reference to database and/or server name in 'myDB.dbo.ts_number' is not supported in this version of SQL Server."

Best wishes,
Pio

**Comment by Apollon77** [comment]
Which version of SQL server is running there?

**Comment by pioschek** [comment]
"Microsoft SQL Azure (RTM) - 12.0.2000.8   Aug 29 2017 13:06:11   Copyright (C) 2017 Microsoft Corporation "

In another program, I play now a little bit with 'tedious' for connecting and querying. Seems to be fine, but I need to do more tests. Here the link from MS: https://docs.microsoft.com/de-de/azure/sql-database/sql-database-connect-query-nodejs

**Comment by UweSeifner** [comment]
Hi, are there any News about database on azure?
thx

**Comment by Apollon77** [comment]
No not really because I have no idea about the possible reasons and, to be honest, had not time to setup Azure to reproduce.

Here (https://github.com/ioBroker/ioBroker.sql/blob/master/lib/mssql.js) you can see the queries used to create the tables ... are they now working on azure?!

**Comment by UweSeifner** [comment]
I managed to connect to an MySQL Database on Azure, it sems that SQL is not working. Preview of Azure MySQL is working.

**Comment by Apollon77** [comment]
So the main question to find out what is different from Azire SQL Db to a "normal" one

**Comment by rarnken** [comment]
Can we re-open this issue. I think the query is not the problem, its more about how you connect to the azure sql db.

**Comment by rarnken** [comment]
> So the main question to find out what is different from Azire SQL Db to a "normal" one

**Comment by rarnken** [comment]
> So the main question to find out what is different from Azire SQL Db to a "normal" one

Can we re-open this issue. I think the query is not the problem, its more about how you connect to the azure sql db.

**Comment by Apollon77** [comment]
In fact you can always create a new Issue ... but in this case - when you have knowledge about Azure then a PR would be better I think ...
