### ISSUE TITLE
Change check of number

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.sql#35]
https://github.com/ioBroker/ioBroker.sql/blob/78c4e9cf3a5d73b95461570e684525219e833c9e/main.js#L897

`f.toString() !== state.val.replace(/^\+|[\.,]0+$/, '')`

"0.00" or "+6" now are not numbers.

This must be done for all adapters...

**Comment by Apollon77** [comment]
Is this really everything?
I would exect that we need to remove "trailing 0" in any case ... because elsoe an "0.20" would also be problematic but not get's detected. Or !? Will think of it ...

**Comment by GermanBluefox** [comment]
Yes, you are right with the trailing 0.

**Comment by Apollon77** [comment]
Short: isNan() is exactly what we searched for :-)

**Comment by Apollon77** [comment]
And in combination with isFinite()

**Comment by Apollon77** [comment]
Done in 2.0.0
