### ISSUE TITLE
The filter in the "table" section does not work

### ISSUE THREAD

**Issue by SpectreKr** [ioBroker/ioBroker.sql#40]
![default](https://user-images.githubusercontent.com/25300325/35719387-5c91b8b8-07fa-11e8-98ab-ae1f0766922d.png)

**Comment by Jey-Cee** [comment]
I can confirm this issue. sql adapter version 1.9.2.
The filter shows data from february of 2018 if there wasn't set a filter in the past. If there was a filter it shows data of the last day(s). 
I can not see a pattern for this behaivior.

**Comment by Apollon77** [comment]
a bug in Admin repo exists when I remember
