### ISSUE TITLE
Active Checkbox not rendering

### ISSUE THREAD

**Issue by tops4u** [ioBroker/ioBroker.sql#42]
Using actual Versions of Safari, Firefox or Chrome on MacOS, parts of the SQL Configuration Panel do not render correctly. Currently it is not possible to Activate/Deactivate SQL Logging on the Datapoint via GUI. 
IOBroker on current Versions as to date. 

<img width="540" alt="sqlpanel" src="https://user-images.githubusercontent.com/6877067/37951015-233c9e3c-319b-11e8-8248-7a8ecc73f28f.png">

**Comment by Apollon77** [comment]
Seems like you are using a very old Admin 3 version. Please update first. If then still happening, reopen please

**Comment by tops4u** [comment]
Just Updated today to 3.3.5 and still the same. Intentionally used Chrome and Firefox where ioBroker has never been used before. Same Problem. This does not happen with the "History" Adapter, there the Checkbox is correctly rendered. Either this is a Mac Specific Issue or a difference between History and SQL Adapter.

**Comment by Apollon77** [comment]
Ok, which SQL version you use? Make sure to also use the current one here

**Comment by tops4u** [comment]
Should be? 

<img width="310" alt="sql" src="https://user-images.githubusercontent.com/6877067/37956688-51021f7a-31ac-11e8-9151-5ddff7234e33.png">

**Comment by Apollon77** [comment]
Nope. Klick on reload in the Adapter overview (the small button with the two arrows). Stable is 1.6.9 :-) latest is 1.7.2 I think ...

**Comment by tops4u** [comment]
Thanks. For some reason the Admin did not show the latest version. I tried to manually force it by taking the latest Github Version, and it worked. Thanks.
