### ISSUE TITLE
Can not run sequence query separated with ';'

### ISSUE THREAD

**Issue by Andrey2509** [ioBroker/ioBroker.sql#43]
I need to run hundreds of queries in one query, separated by a ';'
A simple example:
```
 var query='UPDATE iobroker.faces SET   prob=43  where  id= 168; UPDATE iobroker.faces SET  prob=42  where  id= 169';
  sendTo('sql.0', 'query',query , function (result) {
        if (result.error) {
            console.error(result.error);
        } 
        else
        {
        }
});
```
But seems driver does not parse ";".
I get error:

javascript.0 script.js.test.test2: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE iobroker.faces SET prob=42 where id= 169' at line 2
--

**Comment by Apollon77** [comment]
This error is returned by your database i assume. Where you got the idea from that this should work?
You can indeed send one message per query.

**Comment by BuZZy1337** [comment]
Its not a fault from ioBroker..
That Error comes up because the Database does not accept ;

**Comment by BuZZy1337** [comment]
Suggestion:
You can define an array with your statements and loop through that array and send all the queries to the database server.

**Comment by Andrey2509** [comment]
In this case I get: 2018-04-20 13:16:27.191  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.192  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.193  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.193  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.198  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.198  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.198  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.198  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.199  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.199  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.199  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.199  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.199  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.199  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.199  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.200  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections2018-04-20 13:16:27.200  - [31merror[39m: javascript.0 script.js.face.fr_web: Error: ER_CON_COUNT_ERROR: Too many connections  I have no problem to exec hundreds queries separated by ";" in native mysql client. 20.04.2018, 14:39, "BuZZy1337" <notifications@github.com>:Suggestion:You can define an array with your statements and loop through that array and send all the queries to the database server.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Apollon77** [comment]
... but think about that not too many run in parallel ...

**Comment by BuZZy1337** [comment]
Of course you should add some "safety time" after each query.. Avoid to send 100 queries in 1 Second to the Database.. :smile:

**Comment by Apollon77** [comment]
Ideally no delay but normal callback structure from JavaScript. So „iterate through array using callbacks“ and/or as feature request we add array possibility to the query message. Will think about it

**Comment by BuZZy1337** [comment]
https://mariadb.com/kb/en/library/delimiters/

**Comment by Apollon77** [comment]
@Andrey2509 What do you want to do? As soon as you select a different database you screw up the whole adfapter because it assumes that it is in the correct database to handle all the data. The "query" method is mainly to query data. The connection should always already be in the "iobroker" Database, so you do not need to select this

**Comment by Andrey2509** [comment]
If run:
```
var query1= "CREATE TABLE `test` ( \
  `id` int(11) NOT NULL AUTO_INCREMENT,\
  PRIMARY KEY (`id`))";
console.log('query1='+query1);
sendTo('sql.0', 'query', query1, function (result) {
    if (result.error) {
    console.error(result.error);
    } 
    else
   {console.log('SQL table created');      }
    
});
```

Got error:

```

12:47:13.009 | [info] | javascript.0 script.js.test.test3: query1=CREATE TABLE `test` ( `id` int(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY (`id`))
-- | -- | --
12:47:13.009 | [info] | javascript.0 script.js.test.test3: registered 0 subscriptions and 0 schedules
12:47:13.012 | [error] | javascript.0 script.js.test.test3: Error: ER_NO_DB_ERROR: No database selected


```

**Comment by Apollon77** [comment]
The adapter is designed to work with his own data and is no generic sql access adapter
