### ISSUE TITLE
Add foreign keys to mysql Database

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.sql#46]
Please add foreign keys on create table statements to keep data consistency

**Comment by Apollon77** [comment]
PRs are welcome. For which databases they are needed?

**Comment by mesche** [comment]
For all databases:
e. g. 
 - ts_numbers#id -->  datapoints#id
 - ts_numbers#_from -->  sources#id

**Comment by Apollon77** [comment]
sure, Can you provide the relevant SQL queries for all DBs? 
SQLite( if supported), MySQL, PostgreSQL, MSSQL ... then it should be faster

**Comment by mesche** [comment]
Nein kann ich leider nicht. Ich denke aber Google kann Ihnen dabei gut helfen.

**Comment by Apollon77** [comment]
für alle neuen crreations sind PKs und ggf Indeizes jetzt inzwischen drauf. Migration is tricky
