### ISSUE TITLE
Error - database already exists

### ISSUE THREAD

**Issue by user-51** [ioBroker/ioBroker.sql#47]
I am running ioBroker on Freebsd with the sql adapter connecting to a Postgresql database. Initially everything worked fine, but since a reboot the adapter does not connect to the database any more, with the error message "ERROR: database "iobroker" already exists".

**Comment by Apollon77** [comment]
Please show full log. Normally the error is ignored silently and taken as „dB already initialized“

**Comment by user-51** [comment]
sql.0 | 2018-07-29 18:13:26.611 | warn | No connection to SQL-DB
sql.0 | 2018-07-29 18:13:26.611 | warn | No connection to SQL-DB
sql.0 | 2018-07-29 18:13:26.610 | warn | No connection to SQL-DB
sql.0 | 2018-07-29 18:13:21.596 | info | enabled logging of mqtt.0.ESP_Easy.BME280.Pressure, Alias=false, 14 points now activated
sql.0 | 2018-07-29 18:13:21.596 | info | enabled logging of mqtt.0.ESP_Easy.BME280.Humidity, Alias=false, 13 points now activated
sql.0 | 2018-07-29 18:13:21.596 | info | enabled logging of mqtt.0.ESP_Easy.BME280.Temperature, Alias=false, 12 points now activated
sql.0 | 2018-07-29 18:13:21.587 | error | Error: ERROR: database "iobroker" already exists
sql.0 | 2018-07-29 18:13:21.530 | info | starting. Version 1.9.2 in /var/db/iobroker/node_modules/iobroker.sql, node: v6.14.3
host.auto | 2018-07-29 18:13:20.351 | info | instance system.adapter.sql.0 started with pid 16901
host.auto | 2018-07-29 18:13:16.543 | info | Restart adapter system.adapter.sql.0 because enabled

**Comment by Apollon77** [comment]
The already exist error canned ignored. The no connection is the real problem. 

Please set loglevel to debug and post this log. And check dB connection settings that also some parallel connections are allowed ...

**Comment by user-51** [comment]
OK, but increasing the loglevel for the sql adapter did not produce any useful debug information...
The connection check works by the way.

sql.0 | 2018-08-01 16:47:16.588 | error | Error: ERROR: database "iobroker" already exists
-- | -- | -- | --
sql.0 | 2018-08-01 16:46:54.837 | warn | No connection to SQL-DB
sql.0 | 2018-08-01 16:46:54.837 | debug | Datatype mqtt.0.ESP_Easy.BME280.Pressure: Currently: number, StorageType: false
sql.0 | 2018-08-01 16:46:54.837 | warn | No connection to SQL-DB
sql.0 | 2018-08-01 16:46:54.836 | debug | Datatype mqtt.0.ESP_Easy.BME280.Humidity: Currently: number, StorageType: false
sql.0 | 2018-08-01 16:46:54.684 | warn | No connection to SQL-DB
sql.0 | 2018-08-01 16:46:54.684 | debug | Datatype mqtt.0.ESP_Easy.BME280.Temperature: Currently: number, StorageType: false
sql.0 | 2018-08-01 16:46:53.835 | debug | Min-Delta reached mqtt.0.ESP_Easy.BME280.Pressure, last-value=1011.91, new-value=1011.9, ts=1533134813832
sql.0 | 2018-08-01 16:46:53.835 | debug | new value received for mqtt.0.ESP_Easy.BME280.Pressure, new-value=1011.9, ts=1533134813832, relog=false
sql.0 | 2018-08-01 16:46:53.835 | warn | No connection to SQL-DB
sql.0 | 2018-08-01 16:46:53.835 | debug | Datatype mqtt.0.ESP_Easy.BME280.Humidity: Currently: number, StorageType: false
sql.0 | 2018-08-01 16:46:53.835 | debug | Min-Delta reached mqtt.0.ESP_Easy.BME280.Humidity, last-value=49.29, new-value=49.3, ts=1533134813831
sql.0 | 2018-08-01 16:46:53.835 | debug | new value received for mqtt.0.ESP_Easy.BME280.Humidity, new-value=49.3, ts=1533134813831, relog=false
sql.0 | 2018-08-01 16:46:53.680 | warn | No connection to SQL-DB
sql.0 | 2018-08-01 16:46:53.680 | debug | Datatype mqtt.0.ESP_Easy.BME280.Temperature: Currently: number, StorageType: false
sql.0 | 2018-08-01 16:46:53.680 | debug | Min-Delta reached mqtt.0.ESP_Easy.BME280.Temperature, last-value=30.37, new-value=30.36, ts=1533134813677
sql.0 | 2018-08-01 16:46:53.680 | debug | new value received for mqtt.0.ESP_Easy.BME280.Temperature, new-value=30.36, ts=1533134813677, relog=false

**Comment by Apollon77** [comment]
Please try again wirth 1.12.3 from GitHub
