### ISSUE TITLE
Feldtexte bei den Einstellungen korrigieren

### ISSUE THREAD

**Issue by mhandschuher** [ioBroker/ioBroker.sql#48]
Oberfläche ist nicht selbsterklärend bzw. mißverständlich:
- "Änderungen aufzeichnen" -> "nur Änderungen aufzeichnen"
- "Nach Intervall aufzeichnen(s)" -> "trotzdem gleiche Werte aufzeichnen (Sekunden)"
(analog zur verständlichen Beschreibung auf der ioBroker-/sql-Seite)

**Comment by Apollon77** [comment]
WIll be changed in 1.9.4, now on GitHub
