### ISSUE TITLE
Aktivierung der Datenspeicherung für Objekt geht verloren

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.sql#49]
Guten Abend Ingo, mir ist die Tage jetzt schon des öfteren aufgefallen, das bei manchen Datenpunkten die Aktivierung zur Protokollierung mittels sql-Adapter verloren geht. Sprich, die Speicherung stoppt dann auch logischer Weise. Den Auslöser dazu konnte ich bisher leider nicht lokalisieren. Speziell Aufgefallen ist dies bei meinem Thermometer HmIP-STHD und dem Bewegungsmelder HmIP-SMO-A.

Ist dir so ein Verhalten bekannt? Als ich vorhin bei Thermometer Temperatur Obejkt in die SQL-Einstellungen ging, sah ich noch kurz den Haken bei 'aktiviert' - dann wars deaktiviert.

Werde das weiter beobachten ...

**Comment by Apollon77** [comment]
Wenn ist der Adapter schuld der die datenpunkte kontrolliert. Im Fall von hm-rpc und hmip ist bekannt das teilweise Objekte bei bestimmten Aktualisierungen oder raspimatic updates/Backup einspielen neu anlegt. Das ist ein bug in ccu Firmware weil das bei hmip falsch gemeldet wird. Hm-rpc hat dafür eine Einstellung keine Objekte zu löschen. Setz die mal. Dann sollte das nicht mehr auftreten.
