### ISSUE TITLE
Error when nothing is logged for a while

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.sql#52]
I installed and configured the adapter yesterday but didn't set up any datapoint. Starting the adapter worked but after a timeout the MySQL server closed the connection. That caused an unhandled exception in the instance and caused a bunch of logging. 
That the connection is closed by the MySQL server is expected behaviour and should not cause an unhandled exception. It can cause a warning log. What I would like best would be an option to "silently reconnect if the server closes the connection".
![image](https://user-images.githubusercontent.com/13995942/45914682-af228d00-be48-11e8-962c-bbb5980eebe4.png)

**Comment by Apollon77** [comment]
Please make sure the SQL server is not closing the connection :-)

**Comment by Apollon77** [comment]
no answer
