### ISSUE TITLE
Entprellzeit wird nicht berücksichtigt

### ISSUE THREAD

**Issue by DrBakterius** [ioBroker/ioBroker.sql#53]
Siehe folgenden Thread: https://forum.iobroker.net/viewtopic.php?f=20&t=17563&p=183896#p183757

**Comment by Apollon77** [comment]
still relevant

**Comment by Apollon77** [comment]
Für History habe ich das in der neuen "History 2.0.0" mal gefixt weil dort das gleiche Problem besteht. Wäre es möglich im vergleich sql/history mal anzusehen und zu sagen ob es in History 2.0.0 gefixt ist?

Details: https://forum.iobroker.net/topic/54197/test-adapter-history-2-0-0

**Comment by Apollon77** [comment]
Please try 2.0.0 from GitHub

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/54662/test-adapter-sql-2-0-0
