### ISSUE TITLE
The driver stops and starts by itself.

### ISSUE THREAD

**Issue by saykl** [ioBroker/ioBroker.sql#63]
Can you help?

I used various databases. Error everywhere.

host.server	2019-02-03 14:04:36.485	error	instance system.adapter.sql.0 terminated with code 6 (uncaught exception)
host.server	2019-02-03 14:04:36.485	error	Caught by controller[1]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.server	2019-02-03 14:04:36.485	error	Caught by controller[1]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.server	2019-02-03 14:04:36.485	error	Caught by controller[1]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
host.server	2019-02-03 14:04:36.485	error	Caught by controller[1]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.server	2019-02-03 14:04:36.484	error	Caught by controller[1]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.server	2019-02-03 14:04:36.484	error	Caught by controller[1]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
host.server	2019-02-03 14:04:36.484	error	Caught by controller[1]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
host.server	2019-02-03 14:04:36.483	error	Caught by controller[1]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.sql/main.js:1117:17)
host.server	2019-02-03 14:04:36.483	error	Caught by controller[1]: at pushHistory (/opt/iobroker/node_modules/iobroker.sql/main.js:1089:13)
host.server	2019-02-03 14:04:36.483	error	Caught by controller[1]: at pushHelper (/opt/iobroker/node_modules/iobroker.sql/main.js:1148:63)
host.server	2019-02-03 14:04:36.480	error	Caught by controller[1]: TypeError: Cannot read property 'toString' of undefined
sql.0	2019-02-03 14:04:35.491	warn	Exception: TypeError: Cannot read property 'toString' of undefined
sql.0	2019-02-03 14:04:35.491	error	TypeError: Cannot read property 'toString' of undefined at pushHelper (/opt/iobroker/node_modules/iobroker.sql/main.js:1148:63) at pushHistory (/opt/iobroker/node_modules/iobroker.sql/main.js:
sql.0	2019-02-03 14:04:35.490	error	uncaught exception: Cannot read property 'toString' of undefined

**Comment by Apollon77** [comment]
Bitte die Version vom GitHub versuchen.

**Comment by saykl** [comment]
> 
> 
> Bitte die Version vom GitHub versuchen.

Made. It did not help

**Comment by Apollon77** [comment]
Then great that you are reporting it!
Please provide new error log from the latestGitHub version (line numbers could be different) ad I will have a look

**Comment by Apollon77** [comment]
PS: Did you restarted the instance after GitHub update??

**Comment by saykl** [comment]
Yes, i restarted it.

host.server | 2019-02-05 19:35:38.971 | error | instance system.adapter.sql.0 terminated with code 6 (uncaught exception)
-- | -- | -- | --
host.server | 2019-02-05 19:35:38.971 | error | Caught  by controller[0]:     at Manager.ondecoded  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
host.server | 2019-02-05 19:35:38.971 | error | Caught  by controller[0]:     at Manager.Emitter.emit  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.server | 2019-02-05 19:35:38.970 | error | Caught by controller[0]:     at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.server | 2019-02-05 19:35:38.970 | error | Caught  by controller[0]:     at Socket.onpacket  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
host.server | 2019-02-05 19:35:38.970 | error | Caught  by controller[0]:     at Socket.onack  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
host.server | 2019-02-05 19:35:38.970 | error | Caught by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.sql/main.js:1124:17)
host.server | 2019-02-05 19:35:38.970 | error | Caught by controller[0]:     at pushHistory (/opt/iobroker/node_modules/iobroker.sql/main.js:1096:13)
host.server | 2019-02-05 19:35:38.970 | error | Caught by controller[0]:     at pushHelper (/opt/iobroker/node_modules/iobroker.sql/main.js:1174:9)
host.server | 2019-02-05 19:35:38.970 | error | Caught by controller[0]:     at pushValueIntoDB (/opt/iobroker/node_modules/iobroker.sql/main.js:1497:26)
host.server | 2019-02-05 19:35:38.970 | error | Caught by controller[0]:     at Object.exports.insert (/opt/iobroker/node_modules/iobroker.sql/lib/mysql.js:29:66)
host.server | 2019-02-05 19:35:38.969 | error | Caught by controller[0]: TypeError: Cannot read property 'toString' of undefined
sql.0 | 2019-02-05 19:35:38.017 | warn | Exception: TypeError: Cannot read property 'toString' of undefined
sql.0 | 2019-02-05 19:35:38.017 | error | TypeError: Cannot read property 'toString' of undefined     at Object.exports.insert (/opt/iobroker/node_modules/iobroker.sql/lib/mysql.js:29:66)     at pushValueIntoDB (/opt/iobroker/node_modules/iob
sql.0 | 2019-02-05 19:35:38.016 | error | uncaught exception: Cannot read property 'toString' of undefined

**Comment by Apollon77** [comment]
Ok, this is very strange. state.val is undefined ... this can only happen if there is a state without a value where logging is enabled ... If it is reporducable please do me one favor: Set sql instance to debug and send the log of this please 8yes the fill, best as textfile attachment). Then I can see what exactly happens there

**Comment by saykl** [comment]
I uploaded log https://yadi.sk/d/qn48bfqkPUlvZA
The debug mode for the driver is turned on a few hours ago. Logs of all drivers as the host gives the same error. They may be related

**Comment by Apollon77** [comment]
Ok, Somehow one of your states have "undefined" as value which is uncommon, but hey ... everything is possible :-)
Please try Version from GitHub. Do it solve the problem? The version should show "undefined" as texual value in this case
