### ISSUE TITLE
Getting Error: Request failed to complete in 15000ms

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.sql#67]
I'm continously getting the following error:

sql.0 RequestError: Timeout: Request failed to complete in 15000ms

Database writes failing a many times. Does it mean sql adapter is not able to transmit to db in time and datapoints are missing?

SQL logging based on changes activated for:

EDIT: Objekte: 6710, Zustände: 5695

**Comment by Apollon77** [comment]
Sieht mir danach aus das der sql Server ein Problem hat. Worauf läuft der? Wie geht es dem? Was sagen deine Logs?

**Comment by passuff** [comment]
MS SQL Server läuft im Docker auf einer emulierten (Xpenology) Synology DS 3617 und tatsächlich auf einem Dell T420.
Ich habe leider keine Ahnung von SQL. Es hat bisher immer alles funktioniert. Die Anzahl der Datenpunkte steigt natürlich kontinuierlich.
Ich habe MS SQL Server Manager installiert und werde nochmal versuchen die logs zu finden. Bisher war ich erfolglos.

**Comment by Apollon77** [comment]
Ich lese so einen Fehler das erste mal. 

Du kannst versuchen die sql Instanz mal in debug loglevel laufen zu lassen und schauen ob das log dann ggf mehr Aufschluss gibt.

**Comment by passuff** [comment]
`2019-02-24 18:51:45.553  - [34mdebug[39m: sql.0 value not changed viessmann.1.get.VitoStatusPumpe1_M1, last-value=0, new-value=0, ts=1551030705548
2019-02-24 18:51:48.289  - [31merror[39m: sql.0 RequestError: Timeout: Request failed to complete in 15000ms
2019-02-24 18:51:48.289  - [34mdebug[39m: sql.0 sendTo "getHistory" to system.adapter.web.0 from system.adapter.sql.0`

**Comment by Apollon77** [comment]
Aaaahhh it seems to be a gethistory call, so it is not about inserting values but about selecting them. How many data you have in there?

**Comment by passuff** [comment]
Versuchen wir das hier in EN oder DE? Bei dem hin und her wird mir schwindelig.
Was meinst du mit "dort"?

**Comment by Apollon77** [comment]
Hihi. Sorry. Auf dem Handy verliert man mal schnell überblick. 
Dort=in der DB .... weil das select >15 Sekunden dauert heißt entweder das du sehr langen Zeitraum abfragst oder zu viele Daten da sind.

**Comment by Apollon77** [comment]
Ps: je nach dB Server gab es schon mal die info das zusätzliche Indizes helfen könnten

**Comment by passuff** [comment]
Mir ist schon aufgefallen, dass nach meinem Wechsel von influxdb auf ms sql die Abfragezeiten im Flot deutlich länger dauern.  Scheint, als ob bei zeitbasierten Daten influx deutlich performanter ist. 
Deine Frage nach "zu vielen Daten" auf dem Server kann ich nicht quantifizieren. Ich speichere in Folge von Änderungen, mit einem Debounce von 10sek. Datenpunkte gibt es knapp 1000. Ich denke damit sollten SW (Synology DS/MS SQL)  und HW (DELL T420) eigentlich klarkommen.
Was meinst du mit zusätzlichen Indizes? Instanzen? Ich glaube dann würde ich lieber wieder zu influxdb wechseln. Dort hatte ich lediglich das Problem, dass ich nicht in der Lage war den Datentyp eines bestehenden Kanals zu ändern (String->Int). Die Performance war aber wie gesagt spürbar besser.
