### ISSUE TITLE
Wunsch, in der Adapterkonfig Auswahl "Daten löschen älter als..."

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.sql#7]
In der Adapterkonfig gibt es einen Button: "alle Daten löschen".

Schön wäre eine zusätzliche Auswahl mit:
- alles löschen, was älter als 2 Wochen,
- 1 Monat
- 3 Monate ist

**Comment by Apollon77** [comment]
Bitte mit Admin 5 checken, dort umgesetzt
