### ISSUE TITLE
SQL - Doppelte Einträge im table

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.sql#71]
Bei mir werden Einträge doppelt & dreifach gespeichert. Lt. Script soll der Wert einmal um 0 Uhr gespeichert werden (als Beispiel). Trotzdem steht er mehrfach drin.
![bildschirmfoto 2019-03-01 um 15 33 18](https://user-images.githubusercontent.com/8560588/53655112-a59b1d80-3c4f-11e9-807c-938308399eb5.png)

**Comment by Apollon77** [comment]
Wie genau sind die Einstellungen?

**Comment by Apollon77** [comment]
Was sind die Spalten?

**Comment by LJSven** [comment]
![bildschirmfoto 2019-03-01 um 18 53 56](https://user-images.githubusercontent.com/8560588/53656420-7b4b5f00-3c53-11e9-9a63-09b5c9423b4e.png)
![bildschirmfoto 2019-03-01 um 18 53 48](https://user-images.githubusercontent.com/8560588/53656421-7be3f580-3c53-11e9-93ef-615a1d0d23b9.png)
![bildschirmfoto 2019-03-01 um 18 52 37](https://user-images.githubusercontent.com/8560588/53656422-7be3f580-3c53-11e9-8f91-b64a921f9faf.png)
![bildschirmfoto 2019-03-01 um 18 50 06](https://user-images.githubusercontent.com/8560588/53656423-7be3f580-3c53-11e9-8fc8-535970d1b8d2.png)
![bildschirmfoto 2019-03-01 um 18 49 48](https://user-images.githubusercontent.com/8560588/53656424-7be3f580-3c53-11e9-8a82-4e0c11b25a5d.png)

**Comment by Apollon77** [comment]
Hm ... komisch. Kann ich ohe weitere Infos nicht erklären. Version ist die latest vom npm?

Es kann vorkommen das bei "log changes only" augenscheinlich ein Wert doppelt geloggt wird ... aber so oft habe ich noch nicht gesehen (ausser in früheren buggy versionen).

Ansonsten: Bitte Instanz auf Debug Log setzen und dann mal bei so einem Datenpunkt genau ansehen was passiert. Im Log steht was rein kommt und was er damit tut sehr genau
