### ISSUE TITLE
doc: describe what it does better

### ISSUE THREAD

**Issue by shaunc** [ioBroker/ioBroker.sql#74]
I found your tool while looking for a pub/sub wrapper for Postgres notify/listen. I don't think this is what I am looking for, but as it looks like a serious project, thought I'd say that, to an uninitiated person like myself, its hard to say just what it is for from the Readme. 

"This adapter saves state history into SQL DB" -- that could be anything... what state history ... for what purpose ... any purpose? Is this for streaming history (logs, ... ??? ...etc) to a database? In any case, a short paragraph describing a/the typical use case would be very helpful at the top of the documentation.

**Comment by Apollon77** [comment]
This is a Plugin for ioBroker, a smart home system ... and it only works within this and allows to store all available state data that are available in there.
