### ISSUE TITLE
UI: changes for Diff/Type are not persisted correctly

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.sql#75]
Inzwischen habe ich herausgefunden, dass die Einstellung:
Minimale Differenz zum letzten Wert
nur funktioniert, wenn der Messwert als Nummer abgespeichert wird.

Aber: der Wert ist ein Integer, es funktioniert also nur mit ganzen Zahlen.

Wer immer diesen Adapter erstellt hat: Bitte, bitte die Differenz als float einstellen.

So wie es jetzt ist, habe ich die Wahl zwischen Pest und Colera:
Mein Temperatursensor springt immer um 0,1°C und bekomme so unsinnig viele
Messwerte. Oder ich stelle die Differenz auf 1. Dann ist aber die Genauigkeit
viel zu gering.

**Comment by Apollon77** [comment]
Nimm mal einen Punkt und kein Komma. Differenzen gehen auch mit Kommastellen, ggf müssen wir schauen das , in . umgewandelt wird beim speichern.

**Comment by Hans-Zwiesel** [comment]
Hallo Ingo,

 

Vielen Dank, Komman geht auch nicht, da kommt sogar ein Hinweis (MouseOver)

dass z.B. der nächste Wert 1 oder 2 ist.

 

Hast Du da schon einmal einen Punkt eingeben können? 

Wenn ich einen Punkt eingebe, dann ist der nach dem Speichern wieder weg.

 

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. April 2019 10:50
An: ioBroker/ioBroker.sql
Cc: Hans-Zwiesel; Author
Betreff: Re: [ioBroker/ioBroker.sql] SQL nur Änderungen aufzeichnen funktioniert nicht (#75)

 

Nimm mal einen Punkt und kein Komma. Differenzen gehen auch mit Kommastellen, ggf müssen wir schauen das , in . umgewandelt wird beim speichern.

**Comment by Apollon77** [comment]
Kann es vllt sein das es nur ein Anzeigeprüblem ost? Also mach bitte mal :
* Diff mit Punkt eingeben und speichern
* Dann unter "Objekte" zu dem objekt gehen und rechts mit dem "Stift Symbol" und dort "Raw experts only" mal das JSON posten was.da steht. Ist der der Wert mit . drin?
* Was siehst Du dann wenn Du die Seite neu lädst? (Nicht das nur bei der neuen Anzeige der . verschwindet)

**Comment by Hans-Zwiesel** [comment]
Hallo Ingo,

 

-          Wenn ich 0.2 eingebe und speichere, dann anschließend ist der Wert Min.Differenz leer.

-           

-          {

-            "from": "system.adapter.mqtt.0",

-            "user": "system.user.admin",

-            "ts": 1555704624576,

-            "common": {

-              "name": "haus/keller/HumiFan/Sensor/Aussen/aFeuchte",

-              "role": "variable",

-              "desc": "mqtt server variable",

-              "type": "string",

-              "write": true,

-              "read": true,

-              "custom": {

-                "sql.0": {

-                  "enabled": true,

-                  "changesOnly": true,

-                  "debounce": 0,

-                  "maxLength": 10,

-                  "retention": "31536000",

-                  "changesRelogInterval": 0,

-                  "changesMinDelta": "",

-                  "storageType": "Number",

-                  "aliasId": ""

-                }

-              }

-            },

-            "native": {

-              "topic": "haus/keller/HumiFan/Sensor/Aussen/aFeuchte"

-            },

-            "acl": {

-              "object": 1636,

-              "owner": "system.user.admin",

-              "ownerGroup": "system.group.administrator",

-              "state": 1636

-            },

-            "_id": "mqtt.0.haus.keller.HumiFan.Sensor.Aussen.aFeuchte",

-            "type": "state"

-          }

 

-Wenn ich in dem Json bei MinDelta 0.2 eingebe, dann steht bei  Min.Differenz 0,2

-Es steht da auch "type": "string", obwohl der Typ als Nummer eingetragen ist und

in der mySQL der Wert aber unter ts_number abgelegt wird.

 

ich kann erst mal damit leben, wäre aber schön, wenn Du das fixen könntest.

 

Bei diesen Wert war changesMinDelta 0.2 und Min.Differenz 0,2

Aber die Werte: werden mit 0,1 Increment aufgezeichnet:

 

34.3       true       mqtt.0 2019-04-23 13:11:14.908               

34.4       true       mqtt.0 2019-04-23 13:11:07.945               

34.5       true       mqtt.0 2019-04-23 13:10:11.957               

34.6       true       mqtt.0 2019-04-23 13:10:04.939               

34.8       true       mqtt.0 2019-04-23 13:07:58.895               

34.9       true       mqtt.0 2019-04-23 13:07:51.945

 

Damit werden viel zu viele Datensätze erzeugt. Offensichtlich wird das changesMinDelta nicht berücksichtigt.

 

Bist Du eigentlich der Urheber von dem SQL Adapter?

 

Dann meine Hochachtung. Es ist vieles sehr praxisnahe vorgesehen, da steckt viel Erfahrung dahinter.

Wenn es dann noch so funktioniert wäre umso schöner

 

 

Vielen Dank,

Mit freundlichen Grüßen

Hans Stöckl

 

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. April 2019 12:59
An: ioBroker/ioBroker.sql
Cc: Hans-Zwiesel; Author
Betreff: Re: [ioBroker/ioBroker.sql] SQL nur Änderungen aufzeichnen funktioniert nicht (#75)

 

Kann es vllt sein das es nur ein Anzeigeprüblem ost? Also mach bitte mal :

*	Diff mit Punkt eingeben und speichern
*	Dann unter "Objekte" zu dem objekt gehen und rechts mit dem "Stift Symbol" und dort "Raw experts only" mal das JSON posten was.da steht. Ist der der Wert mit . drin?
*	Was siehst Du dann wenn Du die Seite neu lädst? (Nicht das nur bei der neuen Anzeige der . verschwindet)

**Comment by Apollon77** [comment]
ok, UI muss ich checken.

Zur Aufzeichnung: Es kann einen Grund geben das es in 0.1er Schritten passiert ... muss ich aber sehen. Bitte mal Instanz auf Debug setzen und dann mit 0.2 einstellen und dann log ansehen/posten.

SQL ist nicht von mir, aber habe in letzter Zeit sehr viel daran gemacht und es quasi übernommen.

**Comment by Hans-Zwiesel** [comment]
Habe ich einmal gemacht, Log im Anhang

 

Hoffentlich findest Du da etwas heraus.

Wenn Du sonst noch Infos benötigst, melde Dich bitte.

 

VG

Hans Stöckl

 

 

 

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. April 2019 14:08
An: ioBroker/ioBroker.sql
Cc: Hans-Zwiesel; Author
Betreff: Re: [ioBroker/ioBroker.sql] SQL nur Änderungen aufzeichnen funktioniert nicht (#75)

 

ok, UI muss ich checken.

Zur Aufzeichnung: Es kann einen Grund geben das es in 0.1er Schritten passiert ... muss ich aber sehen. Bitte mal Instanz auf Debug setzen und dann mit 0.2 einstellen und dann log ansehen/posten.

SQL ist nicht von mir, aber habe in letzter Zeit sehr viel daran gemacht und es quasi übernommen.

**Comment by Apollon77** [comment]
Sorry kein attachement

**Comment by Hans-Zwiesel** [comment]
Hallo Ingo,

 

bist Du inzwischen weitergekommen oder brauchst Du noch irgendwelche Infos?

 

Ich kann mir nicht vorstellen, daß ein Vergleich von abs( aktueller Wert – sql.letzter.Wert) > Differenz so große

Probleme bereiten kann. Woran liegt das Problem?

 

VG

Hans

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. April 2019 14:08
An: ioBroker/ioBroker.sql
Cc: Hans-Zwiesel; Author
Betreff: Re: [ioBroker/ioBroker.sql] SQL nur Änderungen aufzeichnen funktioniert nicht (#75)

 

ok, UI muss ich checken.

Zur Aufzeichnung: Es kann einen Grund geben das es in 0.1er Schritten passiert ... muss ich aber sehen. Bitte mal Instanz auf Debug setzen und dann mit 0.2 einstellen und dann log ansehen/posten.

SQL ist nicht von mir, aber habe in letzter Zeit sehr viel daran gemacht und es quasi übernommen.

**Comment by Apollon77** [comment]
siehe letztes Kommentar: Es waren keine Attachements dran, mir fehlen noch die Debug Files!

Meine Vermutung ist das es "as designed" ist und mit dem "Log changes only" zu tun hat und der Logik die dann genutzt wird. Das System speichert sich verworfene Werte die nicht geloggt wurden aus gründen und loggt diese bei einer Änderung zusätzlich damit man eine korrekte Darstellung in Graphen hat. Ich denke das sich hier also "Log changes only " it dem "Diff Logging" beisst -- du könntest mal versuchen "log changes only zu deaktivieren" und ich tippe das es dann so tut wie Du willst. Aber genau das wollte ich in den Logs checken

**Comment by Hans-Zwiesel** [comment]
Ich habe die schon am 24.4. gemailt, hänge sie aber noch einmal dran.

 

Du bist aber schon auch der Meinung, daß die Kombination "Log changes only " und "Diff Logging" 

sinnvoll ist?

 

 

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Freitag, 26. April 2019 10:17
An: ioBroker/ioBroker.sql
Cc: Hans-Zwiesel; Author
Betreff: Re: [ioBroker/ioBroker.sql] UI: changes for Diff/Type are not persisted correctly (#75)

 

siehe letztes Kommentar: Es waren keine Attachements dran, mir fehlen noch die Debug Files!

Meine Vermutung ist das es "as designed" ist und mit dem "Log changes only" zu tun hat und der Logik die dann genutzt wird. Das System speichert sich verworfene Werte die nicht geloggt wurden aus gründen und loggt diese bei einer Änderung zusätzlich damit man eine korrekte Darstellung in Graphen hat. Ich denke das sich hier also "Log changes only " it dem "Diff Logging" beisst -- du könntest mal versuchen "log changes only zu deaktivieren" und ich tippe das es dann so tut wie Du willst. Aber genau das wollte ich in den Logs checken

**Comment by Hans-Zwiesel** [comment]
Leider zeichnet er immer noch in 0,1 Schritten auf, auch wenn „changes only“ deaktiviert ist und „Diff.Logging“ auf 0,2

steht.

 

VG

Hans

 

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Freitag, 26. April 2019 10:17
An: ioBroker/ioBroker.sql
Cc: Hans-Zwiesel; Author
Betreff: Re: [ioBroker/ioBroker.sql] UI: changes for Diff/Type are not persisted correctly (#75)

 

siehe letztes Kommentar: Es waren keine Attachements dran, mir fehlen noch die Debug Files!

Meine Vermutung ist das es "as designed" ist und mit dem "Log changes only" zu tun hat und der Logik die dann genutzt wird. Das System speichert sich verworfene Werte die nicht geloggt wurden aus gründen und loggt diese bei einer Änderung zusätzlich damit man eine korrekte Darstellung in Graphen hat. Ich denke das sich hier also "Log changes only " it dem "Diff Logging" beisst -- du könntest mal versuchen "log changes only zu deaktivieren" und ich tippe das es dann so tut wie Du willst. Aber genau das wollte ich in den Logs checken

**Comment by Apollon77** [comment]
Dann bitte Debug Log und bitte am besten direkt auf GitHub hochladen, scheinbar ignoriert GitHub deine E-mail Attachements!
