### ISSUE TITLE
Datenpunkt String wird (oft) als null gespeichert

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.sql#8]
siehe:
[http://forum.iobroker.net/viewtopic.php?f=22&t=2772#p24892](http://forum.iobroker.net/viewtopic.php?f=22&t=2772#p24892)

**Comment by GermanBluefox** [comment]
Ist noch da?

**Comment by ruhr70** [comment]
Ist mir nicht mehr aufgefallen.
Ich schliesse.
