### ISSUE TITLE
Datenpunkte und ihre Daten in der Datenbank löschen

### ISSUE THREAD

**Issue by m50434** [ioBroker/ioBroker.sql#80]
Es wäre toll, wenn es eine Möglichkeit gäbe, Datenpunkte auch in der Datenbank zu löschen.
Bei besonders vielen Datenpunkten (und durch mehrfaches Probieren mit ähnlichen Bereichnungen) verliert man schnell den Überblick.
Sicherlich kann man das auch in der Datenbank manuell durchführen, aber praktisch fände ich es, wenn es durch den Adapter dort ein Möglichkeit gäbe. Am besten so, dass man eine Übersicht über alle Datapoints bekommt mit einer Information, wann der letzte Eintrag zu dem jeweiligen Datenpunkt geloggt worden ist.
Dann könnte man sehen, welche Datenpunkte schon länger nicht mehr benutzt worden sind und diese dann ggf. löschen.

**Comment by Apollon77** [comment]
Funktioniert die Aufbewahrungszeit nicht? Die kannst du in Fall vom löschen auf sehr kurz setzen. Aber ja komfortabel ist das nicht.

**Comment by m50434** [comment]
Ja klar, das würde so funktionieren.
Aber ist tatsächlich nicht komfortabel: Ich habe beispielsweise inzwischen 27 Datapoints in der Datenbank, allerdings sind hiervon nur noch 12 aktiv. Der Rest sind Datapoints aus irgendwelchen Tests etc. Da sie teilweise dann auch vom gleichen Gerät kamen (allerdings dann nur einen leicht unterschiedlichen Namen haben), fällt es natürlich auch schwer, dann die überflüssigen Datapoints zu löschen (daher die Idee, auf der Oberfläche eine Möglichkeit zu haben, Datapoints zu löschen, bei denen man erkennt, wann zu dem Datapoint das letzte Mal Daten eingetragen worden sind).

**Comment by darkiop** [comment]
Würde die Funktion auch sehr begrüßen. Gerade während der Entwicklung können Datensätze auch mal ungewollt geschrieben werden und aktuell geht es dann eben per SQL delete Statement in DB-Client. Hier wäre ein Löschnkopf im Admin schon eine Zeitersparniss :)
Für den Statistik PR von Scrounger habe ich aktuell eigene SQLer geschrieben - diese Funktion würde sich aber auch im Adapter gut machen.

**Comment by GermanBluefox** [comment]
Die Admin Version, die gerade in der Entwicklung ist, unterstützt das:
![image](https://user-images.githubusercontent.com/4582016/82480989-ea210c00-9ad4-11ea-93c5-480ce74d6003.png)

**Comment by Apollon77** [comment]
But it will need some time till this is available for all so stay tuned

**Comment by WernerSch** [comment]
Hallo GermanBluefox

ich bin an so einem Adapter wo man die SQL Daten editieren und exportieren kann wie in phpmyadmin stark interessiert. Wann wird das ungefähr kommen?

Gruß
Werner

**Comment by Apollon77** [comment]
Admin5 wird solche Features in der UI mitbringen, dauert aber noch etwas

**Comment by Hardwarefreak** [comment]
Ist es möglich diese Version vorab zu testen?

Viele Grüße an die genialen Entwickler!

**Comment by Apollon77** [comment]
Admin5 is still deep in development, will be available once good enough

**Comment by WernerSch** [comment]
Hallo

wie sieht es denn mit dem Adapter aus?
Ich habe immer wieder Datenpunkte die nach bestimmten kriterien gelöscht werden müssten. Am besten per Script.

Gruß
Werner

**Comment by Apollon77** [comment]
Admin 5.1 ist im Beta test im Latest ... ausprobieren gern

**Comment by WernerSch** [comment]
muss ich das per hand installieren oder geht das über iobroker?

**Comment by darkiop** [comment]
Aktuell nur über das Beta-Repo: https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/

Zur Roadmap wann das ganze in Stable kommt kann sicher @Apollon77 was sagen.

So Schaut dann die Verwaltung der DB-Einträge aus:

![image](https://user-images.githubusercontent.com/205119/119540775-1a595580-bd8e-11eb-93eb-c8b4f3997bff.png)

**Comment by Apollon77** [comment]
Ist mit Sdmin5 seit mehreren Monaten live ... bitte mal nutzen und Feedback geben, auf das hatten wir hier gewartet :-) Dann mach ich mal zu,

**Comment by heckmic** [comment]
Eine Funktion zum Aufräumen ohne alle Datenpunkte durchzugehen und zu kennen wäre super. "Lösche alles was älter ist als ein Jahr" und lösche alles was seit X Tagen nicht befüllt wurde.

**Comment by Apollon77** [comment]
@heckmic Schlechte idee auf ein Seit >4 Monaten geschlossenes Issue zu antworten ... das ist damit unsichtbar.

Bitte Issues durchschauen und ggf auf ein offenes Antworten oder ein neues Erstellen
