### ISSUE TITLE
Entprellzeit wird nach Änderung der Einstellungen eines Objekts nicht mehr berücksichtigt 

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/ioBroker.sql#81]
Nach Änderung der Einstellung eines laufenden Objekts fängt der Adapter an die werte zu logen trotz eingestellter Entprellzeit.
Siehe folgenden Thread: https://forum.iobroker.net/topic/22788/adapter-sql-einstellungen/16

**Comment by itProfi** [comment]
Same problem -
![Скриншот 31-05-2019 100612](https://user-images.githubusercontent.com/6728198/58688175-57033980-838c-11e9-8aea-7e538adf8b8a.jpg)
![Скриншот 31-05-2019 100619](https://user-images.githubusercontent.com/6728198/58688176-57033980-838c-11e9-920d-043ef924d3eb.jpg)

**Comment by Apollon77** [comment]
@itProfi  What is set as debounce in the adapter config? Because your 0 here is ignored and falls back to the default

**Comment by itProfi** [comment]
Yes, all right!. I set debounce 500 msec!

**Comment by Apollon77** [comment]
Bitte mit 1.11 nochmal versuchen und Rückmeldung geben. Danke
