### ISSUE TITLE
Adapter startet nicht von Docker Buanet IOBroker

### ISSUE THREAD

**Issue by Obsthaendler** [ioBroker/ioBroker.sql#82]
Ich bekomme beim starten des Adapters folgende Fehlermeldung:

> 

host.io | 2019-06-11 10:18:55.008 | error | instance system.adapter.sql.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-06-11 10:18:55.008 | error | by controller[0]:     at Module.load (module.js:566:32)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at Object.Module._extensions..js (module.js:664:10)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at Module._compile (module.js:653:30)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.sql/node_modules/mmmagic/lib/index.js:1:75)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at require (internal/module.js:11:18)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at Module.require (module.js:597:17)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at Function.Module._load (module.js:498:3)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at tryModuleLoad (module.js:506:12)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at Module.load (module.js:566:32)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:     at Object.Module._extensions..node (module.js:682:18)
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]: Error:  /opt/iobroker/node_modules/iobroker.sql/node_modules/mmmagic/build/Release/magic.node:  failed to map segment from shared object
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:                  ^
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]:   return process.dlopen(module, path._makeLong(filename));
Caught | 2019-06-11 10:18:55.007 | error | by controller[0]: module.js:682

Habe bereit mit unterschiedlichen node versionen es versucht. Ich vermute es liegt am Docker Image von Buanet, allerdings weiß ich nicht wo ich noch gucken soll. Ein Tipp der auch nicht geholfen hatte, war dass der SQL Adapter kein TMP verzeichnis hat.

**Comment by Apollon77** [comment]
Hast du das - wenn du vermutest es liegt am Docker - mal dort eingestellt und erfragt? Irgendwie sieht mir das nach was mir Shared mem oder so aus ... müsste jetzt googeln danach.

**Comment by Apollon77** [comment]
Keine Antwort ... closed
