### ISSUE TITLE
Retention logic tries to clean up "un-initialized" fields

### ISSUE THREAD

**Issue by Fiiti** [ioBroker/ioBroker.sql#83]
Im Log sind viele 
`2019-07-05 11:22:50.614  - error: sql.0 Cannot delete DELETE FROM `iobroker`.undefined WHERE id=100 AND ts < 1530782520591;: Error: ER_NO_SUCH_TABLE: Table 'iobroker.undefined' doesn't exist`
enthalten. Im iobroker Forum https://forum.iobroker.net/topic/23628/sql-er_no_such_table-table-iobroker-undefined/2 bat appollon77 um Eröffnung eines Isues.

Hinweis: Die "changesMinDelta":0.5 Einstellungen sind es nicht. Es passiert auch mit 0.

Einen Auszug des Logs auf SILLY ist im ersten Beitrag unter Spoiler.

Gruß,
Fitti

**Comment by Scrounger** [comment]
Der Fehler tritt bei nur in Verbindung mit dem befehl
` sendTo(instance_history, 'enableHistory', {....}` und wenn beim Datenpunkt der sql adapter bereits aktiviert ist. 

Ist mir beim skript [homematic_verbrauchszaehler](https://github.com/hdering/homematic_verbrauchszaehler) aufgefallen, dort wird es wiefolgt aufgerufen - [siehe hier](https://github.com/hdering/homematic_verbrauchszaehler/blob/14523ef7d689569e41e08388a8fb94ddb6670600/Zaehlerstande_protokollieren.js#L711). Deaktiviere ich die `sendTo` Methode, kommt die Fehlermeldung nicht mehr - ist reproduzierbar.

**Comment by Anzic23** [comment]
any news?

**Comment by Apollon77** [comment]
no time till now ...

**Comment by Apollon77** [comment]
should be already prevented in current versions of the adapter. Please check 0.10+

**Comment by Fiiti** [comment]
**What does 0.10+mean?**
My **SQL Adapter is 1.95** - and this failure is **still happen**. Log ist very very full with red entrys  :-(
I wonder, what this costs on performance.

**Comment by Apollon77** [comment]
Sorry was a typo. 

Current latest should be 1.10 and 1.11 is on GitHub. Please check with GitHub version as best idea.

**Comment by Fiiti** [comment]
This issue is fixed - **but it results in a new issue:**
used and testet 1.11.1 AND 1.12.0

sql.0 | 2020-04-21 17:30:56.489 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Verbrauch.Jahr. Retention is not possible.
-- | -- | -- | --
sql.0 | 2020-04-21 17:30:56.488 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Verbrauch.Monat. Retention is not possible.
sql.0 | 2020-04-21 17:30:56.487 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Kosten.Jahr. Retention is not possible.
sql.0 | 2020-04-21 17:30:56.486 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Verbrauch.Quartal. Retention is not possible.
sql.0 | 2020-04-21 17:30:56.435 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Kosten.Quartal. Retention is not possible.

The error probably means that the type should be "undefined", which surprises me a lot.
Why should a type be "undefined"?
I did not have this error with 1.9.5 or before.

**Comment by Fiiti** [comment]
This issue is fixed - **but it results in a new issue:**
used and testet 1.11.1 AND 1.12.0

sql.0 | 2020-04-21 17:30:56.489 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Verbrauch.Jahr. Retention is not possible.
-- | -- | -- | --
sql.0 | 2020-04-21 17:30:56.488 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Verbrauch.Monat. Retention is not possible.
sql.0 | 2020-04-21 17:30:56.487 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Kosten.Jahr. Retention is not possible.
sql.0 | 2020-04-21 17:30:56.486 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Verbrauch.Quartal. Retention is not possible.
sql.0 | 2020-04-21 17:30:56.435 | error | (29497) No type undefined found for javascript.0.Verbrauchszaehler.GartenSchalterPumpeMesswertkanal.Kosten.Quartal. Retention is not possible.

The error probably means that the type should be "undefined", which surprises me a lot.
Why should a type be "undefined"?
I did not have this error with 1.9.5 or before.

**Comment by Apollon77** [comment]
Can you please provide a full debug log of such a case. I need to see what happens before this error. Best full log from start to such a first error. Please grab log from logfile on disk and not admin!!
