### ISSUE TITLE
Unambiguous column naming for relationship/foreign key columns

### ISSUE THREAD

**Issue by mesche** [ioBroker/ioBroker.sql#85]
Please use unambiguous column naming:
- Better naming: ts_number#id --> datapoints_id 

Do not use "id" for relationship/foreign key columns

**Comment by Apollon77** [comment]
I think this will be possible to change because it will be 100% backward breaking unless we offer an "automatic DB scheme upgrade" logic for all databases, So I think we need to live with this.

**Comment by mesche** [comment]
Wie Sie schon sagten, müsste natürlich bei einem Upgrade eine Migration der Datenbankstrukur erfolgen. Warum wurde dieses Ticket geschlossen bzw. warum müssen wir jetzt damit leben?

**Comment by Apollon77** [comment]
So eine Automatisierte Datenstrukturanpassung bei der Vielfältigkeit der Installationen u.ä. ist nahezu unmöglich. Dieser Adapter ist über 2.800 mal genutzt. Meine Erfahrungen mit dieser Art DB-Migrationen ist das es mit hoher Wahrscheinlichkeit, egal wie gut man es vorbereitet, in genügend Fällen kaputt gehen wird und in komischen Zuständen endet.

Geschlossen weil an der Stelle ein "cleaneres DB Schema Design" (was keine auswirkung auf die Funktionalität hat die ich gerade sehe) dieses Risiko und Aufwand nicht aufwiegt und ich daher dieses Thema nicht als relevant genug ansehe.

Ich lasse mich mit guten Argumenten gern überzeugen und werde auch ggf einem PR damit nicht im Wege stehen.
