### ISSUE TITLE
Add maximal deviation

### ISSUE THREAD

**Issue by m-s-b** [ioBroker/ioBroker.sql#87]
A minimal deviation ist already implented. I need a maximum deviation to get rid of some wrong values send from several devices sometimes. 
Additional information is here:
https://forum.iobroker.net/topic/25204/hm-rpc-sql-ausrei%C3%9Fer-filtern

**Comment by Apollon77** [comment]
2.0.0 has feature to ignore values above and below a certain value, this should fix this requirement, or?
Please try GitHub verson

**Comment by m-s-b** [comment]
Jein...
Absolute Obergrenze würde in dem Fall nicht reichen. Müsste dann tatsächlich eine relative Grenze sein. Allerdings hab ich für mich nen akzeptablen Umgang gefunden. 
Ergo, wäre schön zu haben, kann aber auch ohne Leben ;-)

**Comment by Apollon77** [comment]
Finde es recht speziell etwas wie "änderungen größer als absolut X ignorieren" zu machen ... und prozemtuell geht nicht (weil x% von 0  ??) ;-)

**Comment by m-s-b** [comment]
Speziell liegt im Auge des Betrachters ;-) Momentan gibt es die Möglichkeit eine Änderung nicht aufzuzeichnen wenn der Betrag der Änderung <X. Das analog für Betrag der Änderung >Y finde ich nicht so abwegig. Also nicht abwegiger als alle Werte <x oder >y zu ignorieren. Das sind im Zweifel zwei SQL Abfragen und die Werte sind raus. 
Egal, ich kann es nicht im Adapter programmieren also kann das hier dann auch zu gemacht werden.

**Comment by Apollon77** [comment]
Ne können ja auf lassen und sehen ob sich noch andere User dafür interessieren :-)

**Comment by Apollon77** [comment]
AM Ende gab es die gleiche diskussion gerade in History adapter. Das Problem an "maximal derivation" ist in meinen Augen das er ohne eine zeitliche Einschränkung ggf dazu führtdas nichts mehr geloggt wird weil der Wert einen großen Sprung gemacht hat ... wenn der wert dann nicht wieder "runter" kommt dann wars das ... ich denke das ist eher schwierig zu verstehen (vor allem weil ein neustart das problem dann magisch behebt :-) )
