### ISSUE TITLE
Please check ioBroker.sql with js-controller 2.0

### ISSUE THREAD

**Issue by ioBrokerChecker** [ioBroker/ioBroker.sql#88]
Hi,

the new js-controller 2.0 will come into latest repository in the next days and we want to make sure that all adapters are working well. We already did a 2 weeks Beta test and so some adapter were aleady checked and some needed slight adjustments.

You can find more information in https://github.com/ioBroker/ioBroker.js-controller/issues/482 and in the ioBroker Forum. If you have more technical questions please write in the referenced issue or in the Developer thread please. General questions are best in the genral thread.

Please update your systems to js-controller 2.0 and check your adapter.

Please close this issue once you have checked your adapter or received successfull reports from users.

Thank you very much for your support. Please contact us in the other Threads or Forum on any question.

**Comment by fuzzyy0815** [comment]
I have a big problem since updating to js-controller 2.0.
the sql adapter fills the 4GB ram until it crashes. Is there a way to run the sql adapter? I currently have 2.0.42 installed.

**Comment by Apollon77** [comment]
which version of the sql adapter you use? This is the first report about that

**Comment by fuzzyy0815** [comment]
Version 1.10.0

**Comment by fuzzyy0815** [comment]
I tested again. Without encryption everything goes great.

The problem only occurs when I encrypt the connection. In debug mode you can see that the data is transferred to the sql database, only the memory of the iobroker runs full until the sql adapter crashes. I hope this helps you further.

I can help me first with an unencrypted connection.

**Comment by Apollon77** [comment]
How you encrypt the connection? OR do you mean that you use username and password? Or what?/how?

**Comment by fuzzyy0815** [comment]
i use  username and password without encrypt. so it works. thank you for your patience. I will keep it going like this.

**Comment by Apollon77** [comment]
But still (because new as problem) ... how you did encrypted dB connection?
