### ISSUE TITLE
Wunsch: Datenbankname individuell einstellbar machen

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.sql#9]
Ein mySQL Server kann derzeit nciht für zwei ioBroker Installationen genutzt werden, da jeweils auf die selbe Datenbank zugegriffen wird (Datenbankname).

Wunsch:

Den Namen der ioBroker Datenbank konfigurierbar machen, gerne mit iobroker am Anfang als feste Einstellung.

**Comment by GermanBluefox** [comment]
Ist schon längst gemacht. Kann ich zumachen?

**Comment by ruhr70** [comment]
ja, funktioniert ;-)
