### ISSUE TITLE
duplicate primary key error - primary key is NOT "id"-"ts"

### ISSUE THREAD

**Issue by IO-Link** [ioBroker/ioBroker.sql#90]
Hi,
i'm not sure if it the same issue as #2 , but i also get the error-message `

- (14912) Cannot insert INSERT INTO `ioBroker`.ts_number (id, ts, val, ack, _from, q) VALUES(114, 1576524586515, 186.284, 0, 11, 0);: Error: ER_DUP_ENTRY: Duplicate entry '1576524586515' for key 'PRIMA

- (14912) Cannot insert INSERT INTO `ioBroker`.ts_number (id, ts, val, ack, _from, q) VALUES(117, 1576524586515, 13.052, 0, 11, 0);: Error: ER_DUP_ENTRY: Duplicate entry '1576524586515' for key 'PRIMAR

- (14912) Cannot insert INSERT INTO `ioBroker`.ts_number (id, ts, val, ack, _from, q) VALUES(116, 1576524586515, 1432376, 0, 11, 0);: Error: ER_DUP_ENTRY: Duplicate entry '1576524586515' for key 'PRIMA`

I use SQL adapter version 1.9.4

I think the problem is, that i log several datapoints, and some of them are logged at the same time  - e.g. every full hour (like the examples above). As you can see, the sql adapters tries to update more than one entry with the same ts.

I've also seen in the forum, that the logs of some users show, that the primary key is generated with "id" - "ts" (e.g. "23-1450179321000"). But in my case, it is only "ts" (e.g. 1576524586515). How can i switch to a primary key generated with "id" - "ts"?

**Comment by Apollon77** [comment]
Please check if the values are logged. There is logic in the code to write the value again if sichtbar error happens. There is 1ms added in such a case. 

The PK indeed is id+ts ... this works correctly.  The problem is that for the same id two values should be logged at the same time. This happens sometimes. 

If you like enable debug logging and you will see in log what exactly happens in such a case. You can also provide the log for me to check.

**Comment by IO-Link** [comment]
Thank you for your quick reply and sorry for my late response

> Please check if the values are logged. There is logic in the code to write the value again if sichtbar error happens. There is 1ms added in such a case.
> 
Unfortunately, it is not logged. Example:
Error log: `
sql.0 | 2019-12-17 18:00:03.433 | error | (14912) Cannot insert INSERT INTO `ioBroker`.ts_number (id, ts, val, ack, _from, q) VALUES(99, 1576601999000, 0.165499999999156, 1, 21, 0);: Error: ER_DUP_ENTRY: Duplicate entry '1576601999000' for k
`
In the database, there is no entry for 18:00 clock:
`
| 99 | 1576604699000 | 0.1525999999976193 | 1 | 21 | 0 | 2019-12-17 18:44:59.0000
| 99 | 1576603799000 | 0.2121000000006461 | 1 | 21 | 0 | 2019-12-17 18:29:59.0000
| 99 | 1576602899000 | 0.21640000000115833 | 1 | 21 | 0 | 2019-12-17 18:14:59.0000
| 99 | 1576601099000 | 0.10389999999824795 | 1 | 21 | 0 | 2019-12-17 17:44:59.000
`

> The PK indeed is id+ts ... this works correctly. The problem is that for the same id two values should be logged at the same time. This happens sometimes.
> 
> If you like enable debug logging and you will see in log what exactly happens in such a case. You can also provide the log for me to check.

Please see attached file. 
In row 2: You see, that SQL writes an entry with ID "115" and the ts "1576607385294"
In row 4 and 6: SQL tries to write an entry with the same ts and ID "116" and "117"
In row 7 and 8: the corresponding error messages for row 4 and 6
[iobroker.2019-12-17.log](https://github.com/ioBroker/ioBroker.sql/files/3974863/iobroker.2019-12-17.log)

**Comment by Apollon77** [comment]
ok, could it be that the DB is setup incorrectly somehow?

Can you please get an SQL client and display the table structure for `ioBroker`.ts_number ?

The code used to create the DB table in this case is:

        "CREATE TABLE `" + dbname + "`.ts_number  (id INTEGER, ts BIGINT, val REAL,    ack BOOLEAN, _from INTEGER, q INTEGER, PRIMARY KEY(id, ts));",

And as you see it should setup an combined PK ... but this seems not have happened in your case.
If this is the case you need to fix that DB structure, after this the problem should be gone

**Comment by IO-Link** [comment]
I use phpMyAdmin on a Synology. I made a screenshot of the tab "Struktur" of the ioBroker.ts_number table:
![2019-12-18 18_59_14png](https://user-images.githubusercontent.com/45272881/71110985-b0b43f80-21c8-11ea-8c8d-2029da1201b7.png)
I'm not sure where i can find you mentioned code for table creation.

Can i update the DB structure without deleting the data? There are vaules since over 2 years there :-(

**Comment by Apollon77** [comment]
Yes the primary key is wrong. On your page at „Indizes“ click „bearbeiten“ for the primary row. And add „Id“ together with ts

**Comment by IO-Link** [comment]
Thank you very much for your help! Now, it works without any error-messages - perfect!
