### ISSUE TITLE
Zeitfenster für Darstellung der mysql Daten stimmt nicht

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.sql#93]
Wenn man in den Objekten die Anzeige der mysql Daten nach Datum u. Uhrzeit eingrenzt,
dann stimmt die Anzeige nicht:

![mqtt](https://user-images.githubusercontent.com/49147193/72233837-ee3e9980-35c9-11ea-87d7-77dbbd6485fb.jpg)

Wäre sehr schön, wenn das einmal jemand fixen könnte.
Vielen Dank

**Comment by Apollon77** [comment]
This is an admin issue. I cannot move the ticket... could you please recreate it in th admin repo? Thank you!
