### ISSUE TITLE
gelöst: mysql query liefert falsche Werte bei Datum < xy

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.sql#96]
Hallo,
ich habe ein Problem:

SELECT val AS wert, ts AS datum
FROM iobroker.ts_number 
WHERE id=(SELECT id FROM iobroker.datapoints
WHERE NAME='javascript.0.haus.Heizung.Kueche.Temperatur')
`AND  ts > UNIX_TIMESTAMP('2020-02-02  05:00:00')*1000`
LIMIT 1

liefert korrekt: 1580616720008 =  02.02.2020 - 05:12:00

jedoch:
``
AND  ts < UNIX_TIMESTAMP('2020-02-02 06:00:00')*1000 
``

liefert falsch: 1578014400020 = 03.01.2020 - 02:20:00
es sollte doch ein Datum >=  02.02.2020 05:12 geliefert werden!

Ich bin sicher, jemand kennt das Problem und wäre sehr dankbar für die Lösung.

**Comment by Apollon77** [comment]
keine Idee ... aber das ist ja wenn irgendwas mit deinem SQL Server oder der Query oder? passt denn der Wert der bei dem "UNIX_TIMESTAMP('2020-02-02 06:00:00')*1000" rauskommt?

**Comment by Hans-Zwiesel** [comment]
> 
> 
> keine Idee ... aber das ist ja wenn irgendwas mit deinem SQL Server oder der Query oder? passt denn der Wert der bei dem "UNIX_TIMESTAMP('2020-02-02 06:00:00')*1000" rauskommt?

Habe inzwischen einen Tipp vom Spezialisten erhalten, der funktioniert:
AND ts < UNIX_TIMESTAMP('2020-02-02 06:00:00')*1000
ORDER BY ts DESC LIMIT 1

Ohne order by ist der Rückgabewert willkürlich und nicht das, was ich möchte.
Trotzdem vielen Dank für die Rückmeldung
