### ISSUE TITLE
SQL Adapter Log läuft über

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.sql#97]
Ich bekomme haufenweise Einträge wie diesen hier ins Log:

`

dwd.0 | 2020-02-09 00:20:02.478 | info | (8375) starting. Version 2.4.3 in /opt/iobroker/node_modules/iobroker.dwd, node: v10.19.0
-- | -- | -- | --
sql.0 | 2020-02-09 00:20:02.402 | info | (4740) enabled logging of dwd.0.warning.map, Alias=false
sql.0 | 2020-02-09 00:20:02.352 | info | (4740) enabled logging of dwd.0.warning.object, Alias=false
sql.0 | 2020-02-09 00:20:02.302 | info | (4740) enabled logging of dwd.0.warning.description, Alias=false
sql.0 | 2020-02-09 00:20:02.252 | info | (4740) enabled logging of dwd.0.warning.headline, Alias=false
sql.0 | 2020-02-09 00:20:02.202 | info | (4740) enabled logging of dwd.0.warning.text, Alias=false
sql.0 | 2020-02-09 00:20:02.153 | info | (4740) enabled logging of dwd.0.warning.type, Alias=false
sql.0 | 2020-02-09 00:20:02.101 | info | (4740) enabled logging of dwd.0.warning.level, Alias=false
sql.0 | 2020-02-09 00:20:02.052 | info | (4740) enabled logging of dwd.0.warning.severity, Alias=false
sql.0 | 2020-02-09 00:20:01.998 | info | (4740) enabled logging of dwd.0.warning.end, Alias=false
sql.0 | 2020-02-09 00:20:01.991 | info | (4740) enabled logging of dwd.0.warning.begin, Alias=false

`

Aktiviert habe ich nur das Loggen sehr weniger Datenpunkte. Die Datenpunkte, die im Log angezeigt werden, sind keine Datenpunkte die ich logge.

Viele Grüße

Markus

**Comment by Apollon77** [comment]
Welcher js-controller? 2.1.x? Dann bitte auf 2.2.8 updaten

**Comment by MC-1984** [comment]
Hi, nein ist 2.2.8.

**Comment by Apollon77** [comment]
Und du bist sicher das für diese Datenpunkt History Logging nicht aktivieiert ist?

**Comment by Apollon77** [comment]
Schau bitte mal nach bzw zeige mal ein Objekt von denen (Admin - objekte - in der zeile hinten rehcts auf den Stift, dort Tab "Raw" und das JSON mal posten

**Comment by MC-1984** [comment]
Ja, weil ganz viele Datenpunkte so durch Log durchlaufen und ich nur das loggen von ca. 10 bis 20 Datenpunkten aktiviert habe. Und das Wetter war definitiv nicht dabei. Und ich habe auch schon seit Wochen keine neuen Datenpunkte hinzugefügt oder entfernt. Auch habe ich weder den RPI noch irgendeinen Adapter neu gestartet...

Hier ein Log des ersten oben angegebenen Datenpunktes:

`{
  "from": "system.host.raspberrypi4-iobroker.cli",
  "ts": 1576028763139,
  "user": "system.user.admin",
  "common": {
    "name": "Link to chart",
    "type": "string",
    "role": "weather.chart.url",
    "read": true,
    "write": false,
    "custom": {
      "sql.0": {
        "enabled": true,
        "changesOnly": false,
        "debounce": "",
        "maxLength": 10,
        "retention": 0,
        "changesRelogInterval": 0,
        "changesMinDelta": "",
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "dwd.0.warning.map",
  "type": "state"
}`

**Comment by Apollon77** [comment]
Hier steht eindeutig drin das logging aktiviert ist und Admin sollte das auch mit nem "blauen Schraubenschlüssel" anzeigen. Also irgendwas hast Du wohl getan ...

**Comment by Apollon77** [comment]
Vllt ausversehen mal ganz oben auf den schraubenschlüssel geklickt? Und damit viele Datenpunkte auf einmal aktiviert?
Deaktiviere Sie und das Logging ist wieder vorbei

**Comment by MC-1984** [comment]
Ich hab das jetzt seit Wochen ignoriert und gehofft, dass sich das Problem alleine löst. Auch wenn ich gar nichts mache läuft mir das log mit immer wieder denselben Meldungen voll...

**Comment by MC-1984** [comment]
1x kann ja gut ein Versehen gewesen sein, aber das ständig das logging aktiviert wird?

**Comment by Apollon77** [comment]
Scheinbar werden ständig die Objekte neu geschrieben. Und ja das er dabei zu viel loggt ist bekannt und wird geändert. Du kannst aktuell einfach das loglevel der Instanz auf warm setzen. Das ist das ganze Info log weg.  Instanzen - expertenmodus - Spalte logstufe

Aber generell lights danke gerade mehr Objekte als du eigentlich willst ;-)
