### ISSUE TITLE
sqllitle gelb

### ISSUE THREAD

**Issue by daxemann** [ioBroker/ioBroker.sql#98]
sql.0	2020-02-19 17:12:38.576	error	(23251) TypeError: Cannot read property 'borrow' of undefined
sql.0	2020-02-19 17:12:38.575	error	(23251) Selected SQL DB was not installed properly: "sqlite". SQLite requires build tools on system. See README.md
sql.0	2020-02-19 17:12:08.574	error	(23251) TypeError: Cannot read property 'borrow' of undefined
sql.0	2020-02-19 17:12:08.573	error	(23251) Selected SQL DB was not installed properly: "sqlite". SQLite requires build tools on system. See README.md
sql.0	2020-02-19 17:12:08.538	info	(23251) starting. Version 1.10.0 in /opt/iobroker/node_modules/iobroker.sql, node: v10.19.0

---

**System data:**

Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v10.19.0
NPM: 6.13.4
Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
JS-Controller (1): 2.2.8
Admin: 4.0.3
SQL History: 1.10.0

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
> Selected SQL DB was not installed properly: "sqlite". SQLite requires build tools on system. See README.md

did that?

**Comment by daxemann** [comment]
jaa , how i make wrong ?

**Comment by Apollon77** [comment]
Somehoe sqlite was not compiled correctly. you can try to reinstall sql adapter or find the node_modules/sqlite* or node_modules/iobroker.sql/node_modules/sqlite* folder and run "npm rebuild" there

**Comment by daxemann** [comment]
ohh kompliziert :(

**Comment by daxemann** [comment]
habe probleme meine zugbee werden nicht mehr in History.0 aufgezeichnent und ich wollte versuchen auf sqlitle auszuweichen um wieder meine Tabele zum laufen zu bringen aber irgend wie will jetzt garnichts mehr laufen

**Comment by Apollon77** [comment]
Warum werden Sie nicht mehr in history aufgezeichnet? Wäre nicht da den Grund suchen einfacher?

**Comment by daxemann** [comment]
hab mal alle Adapter aktualisiert , seit da an geht nichts mehr , Homatic adapter wird aktualisiert aber meine Xiaomi nicht mehr , hab auch runter downgrade gemacht aber geht nicht mehr keine werte im Flot :(

**Comment by Apollon77** [comment]
dann am besten im Forum mal melden, das ist eher nichts um hier auf github zu solve,
Da wären exakte Logs interessant

**Comment by daxemann** [comment]
ja bin leider noch am lernen wie alles geht und muss noch viel suchen wie wo was , versuche auch vieles so zu machen wie in Youtube beschrieben und dann gehts halt auch nicht , Tuya adapter bekomme ich auch nicht hin , leider und jetzt sql datenbank auch nicht , hab sql gelöscht und über github neu installiert aber will immer noch nicht laufen , gleicher fehler

**Comment by Apollon77** [comment]
Bitte mach einen FOrum Thread auf. Da ist es einfacher zu helfen. Und das Log vom Install bitte dazu packen
